// Isolated component fixtures: no login/session, household API or production data.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync,realpathSync,existsSync} from 'node:fs';
import {createServer} from 'node:http';
import {resolve} from 'node:path';
const require=createRequire(import.meta.url),{build}=createRequire(realpathSync('node_modules/wrangler/package.json'))('esbuild');
const pixel='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aKJkAAAAASUVORK5CYII=';
const imageUrl='https://jvjwyalusdygvkyzmiez.supabase.co/storage/v1/object/sign/nous-deux-chat/0/fixture/photo.png?token=isolated-test';
const source=`import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import HouseHeader from './app/house-header';import HomeMoments from './app/home-moments';import HouseCalendar from './app/house-calendar';import HouseShopping from './app/house-shopping';import {BudgetOverview} from './app/design-overviews';import {AttachmentMessage,AttachmentComposer} from './app/chat-attachments';import {TabBar} from './app/navigation-bar';import {parisDate} from './lib/life';
const noop=()=>{},names=['Alex','Camille'],date=parisDate();
const ideas=['restaurant','outing','home','trip','surprise'].map((category,i)=>({id:'idea-'+i,owner:0,category,title:category,status:'accepted'}));
const appointments=ideas.map((idea,i)=>({id:'event-'+i,sourceIdeaId:idea.id,title:'Un moment à deux',date,time:'',category:['party','party','home','travel','personal'][i],status:'scheduled',visibility:'shared',person:-1}));
const base={kind:'shopping',quantity:'',assignee:-1,due:'',priority:0,note:'',version:1,weekStart:'2026-10-05',owner:0};
const initial=[{...base,id:'shopping-1',title:'Les bananes',done:false},{...base,id:'shopping-2',title:'Une longue description de céréales pour notre petit déjeuner du dimanche',done:false},{...base,id:'shopping-3',title:'Les pommes',done:true,purchasedBy:1}];
function Fixture(){const[items,setItems]=useState(initial),[busy,setBusy]=useState(false);const view=new URLSearchParams(location.search).get('view')||'home';
async function save(action,payload){if(action!=='shopping-check')throw Error('Unexpected fixture action');setBusy(true);await new Promise(r=>setTimeout(r,150));if(window.failNext){window.failNext=false;setBusy(false);return false;}setItems(items=>items.map(i=>i.id===payload.id?{...i,done:payload.done,purchasedBy:0,version:i.version+1}:i));setBusy(false);return true;}
const avatar=<span className="avatar profile-avatar"><img src="data:image/png;base64,${pixel}" alt="Profil de test"/></span>;
return <div className="app-shell"><div className="workspace"><HouseHeader synced online name={names[0]} avatar={avatar} onHome={noop} onRefresh={noop} onNotifications={noop} onProfile={noop}/><main>{view==='home'?<HomeMoments plants={[]} appointments={appointments} ideas={ideas} onGarden={noop} onCalendar={noop}/>:view==='calendar'?<HouseCalendar appointments={appointments} names={names} onOpen={noop} initialDate="2026-10-11"/>:view==='shopping'?<HouseShopping items={items} templates={[]} names={names} active={0} week="2026-10-05" setWeek={noop} busy={busy} online save={save} onEdit={noop} onExpense={noop}/>:view==='budget'?<BudgetOverview month="2026-10" allEntries={[]} entries={[]} names={names} total={0} paid={[0,0]} credit={0} budget={0} monthPicker={null} onSettle={noop} onSettings={noop} onBudgets={async()=>true} busy={false} error=""/>:<><AttachmentMessage id="fixture" name="Photo.png" mime="image/png" bytes={68}/>{view==='preview'&&<AttachmentComposer files={[new File([Uint8Array.from(atob('${pixel}'),c=>c.charCodeAt(0))],'Photo.png',{type:'image/png'})]} onClose={noop} onSent={async()=>{}}/>}</>}</main></div><div className="app-tabbar"><TabBar active="home" onChange={noop} onAdd={noop}/></div></div>;}
createRoot(document.getElementById('root')).render(<Fixture/>);`;
const bundle=await build({stdin:{contents:source,loader:'tsx',resolveDir:process.cwd()},bundle:true,platform:'browser',format:'esm',write:false,jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'isolated-network',setup(b){b.onResolve({filter:/api-client$/},()=>({path:'api-client',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:`export const APP_BASE='/Nous-deux/';export async function apiFetch(path){if(!path.startsWith('/api/attachments?id=fixture'))throw Error('No household network allowed: '+path);return Response.json({url:${JSON.stringify(imageUrl)},download:${JSON.stringify(imageUrl)}});}`}));}}]});
const css=['design-system/tokens/tokens.css','design-system/components/bundle.css','app/application.css'].map(p=>readFileSync(p,'utf8')).join('\n');
const csp=readFileSync('index.html','utf8').match(/http-equiv="Content-Security-Policy" content="([^"]+)"/)[1];
const html=`<!doctype html><html lang="fr" data-theme="light"><head><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta http-equiv="Content-Security-Policy" content="${csp}"><link rel="stylesheet" href="/fixture.css"></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>`;
const server=createServer((req,res)=>{const path=new URL(req.url,'http://local').pathname;if(path==='/fixture.js'){res.setHeader('Content-Type','text/javascript');res.end(bundle.outputFiles[0].text);}else if(path==='/fixture.css'){res.setHeader('Content-Type','text/css');res.end(css);}else if(path.startsWith('/Nous-deux/')){const file=resolve('public',path.slice('/Nous-deux/'.length));if(file.startsWith(resolve('public')+'/')&&existsSync(file)){res.setHeader('Content-Type',file.endsWith('.svg')?'image/svg+xml':'application/octet-stream');res.end(readFileSync(file));}else{res.writeHead(404);res.end();}}else{res.setHeader('Content-Type','text/html');res.end(html);}});
if(process.argv.includes('--bundle-only')){console.log('PASS: isolated browser fixtures compile.');process.exit(0);}
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const {webkit,chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
try{for(const engine of [webkit,chromium]){
 const browser=await engine.launch({headless:true});
 try{const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,reducedMotion:'reduce'});
 await context.route('**/*',route=>{const u=route.request().url();if(u.startsWith(base))return route.continue();if(u===imageUrl)return route.fulfill({contentType:'image/png',body:Buffer.from(pixel,'base64')});return route.abort();});
 await context.addInitScript(()=>{window.cspFailures=[];document.addEventListener('securitypolicyviolation',e=>window.cspFailures.push({directive:e.violatedDirective,uri:e.blockedURI}));});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const width of [320,390,430,768,1024,1440]){
  await page.setViewportSize({width,height:1000});
  for(const view of ['home','calendar','shopping','budget']){
   await page.goto(base+'/?view='+view);await page.locator('.topbar').waitFor();
   const measurements=await page.evaluate(()=>{const center=el=>{const r=el.getBoundingClientRect();return r.y+r.height/2;};const nodes=[...document.querySelectorAll('.topbar .brand-mark:not(.dark-logo),.topbar-right>button,.topbar .profile-avatar')].filter(el=>el.getBoundingClientRect().width>0);const overflow=[...document.querySelectorAll('.topbar,main,.calendar-panel,.calendar-month-list,.shopping-columns,.shopping-row,.countdown-card,.budget-charts,.nd-chart,.couple-navigation')].filter(el=>el.scrollWidth>el.clientWidth+2).map(el=>({className:el.className,width:el.clientWidth,scroll:el.scrollWidth}));return{centers:nodes.map(center),overflow};});
   assert(Math.max(...measurements.centers)-Math.min(...measurements.centers)<=1.5,`${engine.name()} ${width}: header centers ${measurements.centers}`);
   assert.deepEqual(measurements.overflow,[],`${engine.name()} ${width} ${view}: horizontal overflow`);
  }
 }
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/?view=photo');await page.waitForFunction(()=>document.querySelector('.chat-image-preview img')?.naturalWidth===1);assert.deepEqual(await page.evaluate(()=>window.cspFailures),[]);
 await page.goto(base+'/?view=preview');await page.waitForFunction(()=>document.querySelector('.chat-upload-row img')?.naturalWidth===1);assert.deepEqual(await page.evaluate(()=>window.cspFailures),[]);
 await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base+'/?view=shopping');const first=page.locator('[data-item-id="shopping-1"]');await first.locator('.purchase-check').click();await page.locator('.purchase-saving').waitFor();await page.locator('.purchase-leaving').waitFor();await page.locator('.purchased-list [data-item-id="shopping-1"]').waitFor();assert.equal(await first.locator('button.purchase-check').count(),0);await first.locator('.undo-purchase').click();await page.locator('.shopping-list [data-item-id="shopping-1"]').waitFor();await first.locator('.purchase-check').waitFor({state:'visible'});
 await page.waitForFunction(()=>!document.querySelector('.purchase-arriving'));await page.evaluate(()=>{window.failNext=true;});await first.locator('.purchase-check').click();await page.waitForFunction(()=>!document.querySelector('.purchase-saving'));assert.equal(await page.locator('.shopping-list [data-item-id="shopping-1"]').count(),1);assert.equal(await page.locator('[data-item-id="shopping-3"] .undo-purchase').count(),0);
 await page.goto(base+'/?view=home');await page.locator('.moment-pupils').first().waitFor();await page.getByRole('button',{name:'Mettre les personnages en pause'}).click();assert.equal(await page.locator('.moment-pupils').first().evaluate(el=>getComputedStyle(el).animationPlayState),'paused');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.moment-pupils').first().evaluate(el=>getComputedStyle(el).animationName),'none');assert.deepEqual(errors,[]);
 await context.close();console.log('PASS: '+engine.name()+' header alignment and layouts at 320/390/430/768/1024/1440 px, image/blob previews under real CSP, purchase/undo/failure feedback and reduced motion.');
 }finally{await browser.close();}
}}finally{await new Promise(r=>server.close(r));}
