import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import {realpathSync} from 'node:fs';
import path from 'node:path';
import {createECDH} from 'node:crypto';
import {buildPushPayload} from '@block65/webcrypto-web-push';
const root=process.cwd();
const {build}=createRequire(realpathSync(path.join(root,'node_modules/wrangler/package.json')))('esbuild');
const {Miniflare}=createRequire(realpathSync(path.join(root,'node_modules/wrangler/package.json')))('miniflare');
const compiled=await build({stdin:{contents:`import {AsyncLocalStorage} from 'node:async_hooks';import * as household from './app/api/household/route';import * as notifications from './app/api/notifications/route';import * as calls from './app/api/calls/route';const context=new AsyncLocalStorage();globalThis.__requestContext=context;export default{fetch(r){return context.run(r.headers,()=>{const route=new URL(r.url).pathname.endsWith('notifications')?notifications:new URL(r.url).pathname.endsWith('calls')?calls:household;return route[r.method](r);});}}`,resolveDir:root,loader:'ts'},bundle:true,format:'esm',platform:'neutral',external:['cloudflare:workers','node:async_hooks'],write:false,plugins:[{name:'test-headers',setup(b){b.onResolve({filter:/^next\/(headers|navigation)$/},a=>({path:a.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path.endsWith('headers')?'export const headers=async()=>globalThis.__requestContext.getStore();':'export function redirect(){throw new Error("unused")}'}));}}]});
const pair=()=>{const e=createECDH('prime256v1');e.generateKeys();return {publicKey:e.getPublicKey().toString('base64url'),privateKey:e.getPrivateKey().toString('base64url')};};const vapid=pair(),subscriber=pair();
const sub={endpoint:'https://web.push.apple.com/Q/test',keys:{p256dh:subscriber.publicKey,auth:Buffer.alloc(16,9).toString('base64url')}};
const push=await buildPushPayload({data:'Test privé',options:{ttl:60}},sub,{...vapid,subject:'https://example.test'});
assert.equal(push.headers['content-encoding'],'aes128gcm');assert.match(push.headers.authorization,/^vapid /);assert.equal(push.body.byteLength,4096);
let pushes=[];
const mf=new Miniflare({modules:true,script:compiled.outputFiles[0].text,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'communication-test'},bindings:{VAPID_PUBLIC_KEY:vapid.publicKey,VAPID_PRIVATE_KEY:vapid.privateKey},outboundService:async r=>{pushes.push({url:r.url,encoding:r.headers.get('content-encoding')});return new Response('',{status:201});}});
try{
 const db=await mf.getD1Database('DB');for(const f of(await readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())for(const s of(await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await db.prepare(s).run();
 const req=async(route,body,user='a',extra={})=>{const r=await mf.dispatchFetch('https://unit.test/api/'+route,{method:body?'POST':'GET',headers:{...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{}),'content-type':'application/json',origin:'https://unit.test',...extra},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
 const device=crypto.randomUUID(),otherDevice=crypto.randomUUID();const prefs={shopping:true,tasks:true,expenses:true,calendar:true,calls:true};
 assert.equal((await req('notifications?device='+device,null,null)).status,401);
 assert.equal((await req('calls',null,null)).status,401);
 await req('household',{action:'household',payload:{first:'Alex',second:'Camille',name:'Maison',budget:0,version:0}});
 assert.equal((await req('notifications',{action:'subscribe',deviceId:device,member:1,preferences:prefs,subscription:sub})).status,200);
 assert.equal((await req('notifications?device='+device,null)).body.enabled,true);
 assert.equal((await req('notifications?device='+device,null,'b')).body.enabled,false);
 for(const endpoint of ['https://127.0.0.1/a','http://web.push.apple.com/a','https://web.push.apple.com.evil.test/a','https://fcm.googleapis.com:444/a','https://user@fcm.googleapis.com/a'])assert.equal((await req('notifications',{action:'subscribe',deviceId:otherDevice,member:1,preferences:prefs,subscription:{...sub,endpoint}})).status,400);
 const item={id:crypto.randomUUID(),kind:'shopping',title:'Exemple privé',quantity:'',assignee:1,due:'',priority:0,done:false,version:0};
 assert.equal((await req('household',{action:'item',payload:item},'a',{'x-adeux-member':'0','x-adeux-device':otherDevice})).status,200);
 assert.equal(pushes.length,1);assert.equal(pushes[0].encoding,'aes128gcm');
 assert.equal((await req('notifications?device='+device,null)).body.activity.length,1);
 assert.equal((await req('notifications?device='+device,null,'b')).body.activity.length,0);
 await req('notifications',{action:'preferences',deviceId:device,member:1,preferences:{...prefs,shopping:false}});
 await req('household',{action:'item',payload:{...item,id:crypto.randomUUID()}},'a',{'x-adeux-member':'0'});assert.equal(pushes.length,1,'category disabled');
 await req('notifications',{action:'preferences',deviceId:device,member:0,preferences:prefs});
 await req('household',{action:'item',payload:{...item,id:crypto.randomUUID()}},'a',{'x-adeux-member':'0'});assert.equal(pushes.length,1,'do not notify author');
 await req('notifications',{action:'disable',deviceId:device});assert.equal((await req('notifications?device='+device,null)).body.enabled,false);
 assert.equal((await req('notifications',{action:'test',deviceId:device})).status,400);
 assert.equal((await req('notifications',{action:'disable',deviceId:device},'a',{origin:'https://evil.test'})).status,403);
 const id=crypto.randomUUID(),caller=crypto.randomUUID(),receiver=crypto.randomUUID(),receiver2=crypto.randomUUID(),sdp='v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n';
 const base={id,session:caller,member:0};
 assert.equal((await req('calls',{...base,action:'start',offer:sdp})).status,200);
 assert.equal((await req('calls',{...base,action:'start',id:crypto.randomUUID(),offer:sdp})).status,409,'single active call');
 assert.equal((await req('calls',null,'b')).body.call,null);
 assert.equal((await req('calls',{...base,action:'answer',answer:sdp})).status,409,'caller cannot answer');
 assert.equal((await req('calls',{...base,action:'answer',session:receiver,member:1,answer:sdp})).status,200);
 assert.equal((await req('calls',{...base,action:'answer',session:receiver2,member:1,answer:sdp})).status,409,'only one device answers');
 assert.equal((await req('calls',{...base,action:'end',session:receiver2,member:1})).status,403,'third device cannot end answered call');
 assert.equal((await req('calls',{...base,action:'heartbeat'})).status,200);
 assert.equal((await req('calls',{...base,action:'end',session:receiver,member:1})).status,200);
 assert.equal((await req('calls',null)).body.call,null);
 assert.equal((await req('calls',{...base,action:'heartbeat'})).status,410,'ended call cannot revive');
 assert.equal((await req('calls',{...base,action:'start',id:crypto.randomUUID(),offer:sdp},'a',{origin:'https://evil.test'})).status,403);
 const nextId=crypto.randomUUID();assert.equal((await req('calls',{...base,action:'start',id:nextId,offer:sdp})).status,200);
 await db.prepare('UPDATE calls SET expires_at = 0').run();assert.equal((await req('calls',null)).body.call,null);
 assert.equal((await req('calls',{...base,id:nextId,action:'answer',session:receiver,member:1,answer:sdp})).status,410);
 console.log('PASS: push encryption, endpoint safety, opt-in/opt-out/categories, author exclusion, activity isolation, calls authentication, busy state, single answer, participant enforcement, expiry and hangup.');
}finally{await mf.dispose();}
