// Targeted markup and layout contracts. These do not emulate Safari touch/keyboard behavior.
import assert from 'node:assert/strict';
import {readFileSync,realpathSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{build}=createRequire(realpathSync('node_modules/wrangler/package.json'))('esbuild');
const source=`import React from 'react';import {renderToStaticMarkup as render} from 'react-dom/server';import {HomeOverview} from './app/design-overviews';import HomeMoments from './app/home-moments';import HouseCalendar from './app/house-calendar';import RecipeEditor from './app/recipe-editor';import MealPlanner from './app/meal-planner';import {EventCard,DayStrip} from './design-system/runtime';
const h=React.createElement,noop=()=>{},save=async()=>true;
export const views={home:render(h(HomeOverview,{counts:{shopping:2,tasks:3,matches:2,ideas:1,plants:3},onNavigate:noop})),calendar:render(h(HouseCalendar,{appointments:[],names:['A','B'],onOpen:noop})),recipe:render(h(RecipeEditor,{recipe:null,busy:false,error:'',save,onClose:noop})),planner:render(h(MealPlanner,{catalog:[],plans:[],menus:[],active:0,names:['A','B'],busy:false,error:'',save,onRecipe:noop})),holiday:render(h(EventCard,{title:'Ramadan',tone:'menthe',meta:'Fête musulmane'})),dots:render(h(DayStrip,{days:[{day:1,dow:'Lun',who:['nous'],tones:['menthe']}],selected:1}))};`;
const b=await build({stdin:{contents:source,loader:'tsx',resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',write:false});
const mod={exports:{}};new Function('require','module','exports',b.outputFiles[0].text)(require,mod,mod.exports);const v=mod.exports.views;
assert(v.home.includes('Nos missions'));assert(v.home.includes('2 matchs'));assert(v.home.includes('1 invitation'));assert(!v.home.includes('invitations à ouvrir'));
for(const label of ['Jours fériés français','Fêtes chrétiennes','Fêtes musulmanes'])assert(v.calendar.includes(label));assert(v.calendar.indexOf('Fêtes musulmanes')<v.calendar.indexOf('<details'),'Holiday toggles are visible before advanced settings');assert(v.holiday.includes('nd-tone-menthe'));assert(!v.holiday.includes('nd-tone-rose'));assert(v.dots.includes('var(--menthe)'));
for(const label of ['Le nom du plat','Ingrédients et quantités','Préparation','Calories par portion','Nombre de portions','Ajouter une photo','sans porc'])assert(v.recipe.includes(label));assert(v.planner.includes('Composer mon menu'));assert(v.planner.includes('Nos menus favoris'));
const css=readFileSync('app/application.css','utf8');assert(css.includes('touch-action:pinch-zoom'));assert(!css.includes('touch-action:pan-y pinch-zoom'));assert(css.includes('.swipe-card .nd-dish-visual img{position:absolute;inset:0;'));assert(css.includes('.activity-list{display:flex;flex-direction:column;gap:var(--space-3)}'));assert(css.includes('min-inline-size:0'));assert(css.includes('overscroll-behavior-x:none'));
const root=readFileSync('app/house-app.tsx','utf8');for(const label of ['Une idée','Une plante','Une recette','Un menu'])assert(root.includes(label));assert(root.includes("!['quick-add','install'].includes(modal.kind)&&<fieldset"));
const chat=readFileSync('app/house-chat.tsx','utf8');assert(chat.includes('rows={1}'));assert(chat.includes("addEventListener('focusout',focus)"));assert(chat.includes("removeEventListener('focusout',focus)"));assert(!chat.includes('Seul l’auteur peut modifier ou supprimer son message.'));
console.log('PASS: compact tile labels, visible holiday controls and distinct colors, standardized recipe fields, menu entry points, photo containment, scoped scroll, keyboard cleanup and complete quick-add menu.');
