// Targeted markup and layout contracts. These do not emulate Safari touch/keyboard behavior.
import assert from 'node:assert/strict';
import {readFileSync,realpathSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{build}=createRequire(realpathSync('node_modules/wrangler/package.json'))('esbuild');
const source=`import React from 'react';import {renderToStaticMarkup as render} from 'react-dom/server';import {HomeOverview} from './app/design-overviews';import HomeMoments from './app/home-moments';import HouseCalendar from './app/house-calendar';import RecipeEditor from './app/recipe-editor';import MealPlanner from './app/meal-planner';import {EventCard,DayStrip} from './design-system/runtime';
const h=React.createElement,noop=()=>{},save=async()=>true;
export const views={home:render(h(HomeOverview,{counts:{shopping:2,tasks:3,matches:2,ideas:1,plants:3},onNavigate:noop})),calendar:render(h(HouseCalendar,{appointments:[],names:['A','B'],onOpen:noop})),recipe:render(h(RecipeEditor,{recipe:null,busy:false,error:'',save,onClose:noop})),planner:render(h(MealPlanner,{catalog:[],plans:[],menus:[],active:0,names:['A','B'],busy:false,error:'',save,onRecipe:noop})),holiday:render(h(EventCard,{title:'Ramadan',tone:'menthe',meta:'Fête musulmane'})),dots:render(h(DayStrip,{days:[{day:1,dow:'Lun',who:['nous'],tones:['menthe']}],selected:1}))};`;
const b=await build({stdin:{contents:source,loader:'tsx',resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',write:false});
const mod={exports:{}};new Function('require','module','exports',b.outputFiles[0].text)(require,mod,mod.exports);const v=mod.exports.views;
assert(v.home.includes('Nos missions'));assert(v.home.includes('2 matchs'));assert(v.home.includes('1 invitation'));assert(!v.home.includes('invitations à ouvrir'));
for(const label of ['Jours fériés français','Fêtes chrétiennes','Fêtes musulmanes'])assert(v.calendar.includes(label));assert(v.calendar.indexOf('Fêtes musulmanes')<v.calendar.indexOf('<details'),'Holiday toggles are visible before advanced settings');assert(v.holiday.includes('nd-tone-menthe'));assert(!v.holiday.includes('nd-tone-rose'));assert(v.dots.includes('var(--menthe)'));
for(const label of ['Le nom du plat','Ingrédients et quantités','Préparation','Calories par portion','Nombre de portions','Ajouter une photo','sans porc'])assert(v.recipe.includes(label));assert(v.planner.includes('Composer mon menu'));assert(v.planner.includes('Nos menus favoris'));
const css=readFileSync('app/application.css','utf8');assert(css.includes('touch-action:pinch-zoom'));assert(!css.includes('touch-action:pan-y pinch-zoom'));assert(css.includes('.swipe-card .nd-dish-visual img{position:absolute;inset:0;'));assert(css.includes('.activity-list{display:flex;flex-direction:column;gap:var(--space-3)}'));assert(css.includes('min-inline-size:0'));assert(css.includes('overscroll-behavior-x:none'));
const root=readFileSync('app/house-app.tsx','utf8');for(const label of ['Une idée','Une plante','Une recette','Un menu'])assert(root.includes(label));assert(root.includes("!['quick-add','install'].includes(modal.kind)&&<fieldset"));
const chat=readFileSync('app/house-chat.tsx','utf8');assert(chat.includes('rows={1}'));assert(chat.includes("addEventListener('focusout',focus)"));assert(chat.includes("removeEventListener('focusout',focus)"));assert(!chat.includes('Seul l’auteur peut modifier ou supprimer son message.'));
console.log('PASS: compact tile labels, visible holiday controls and distinct colors, standardized recipe fields, menu entry points, photo containment, scoped scroll, keyboard cleanup and complete quick-add menu.');
// Combined recipe search must remain scoped to the selected author/category.
const features=`import React from 'react';import {renderToStaticMarkup as render} from 'react-dom/server';import {filterRecipes,RecipePicker} from './app/recipe-filters';import DateField from './app/date-field';import HouseWheel from './app/house-wheel';import {RecipeView} from './design-system/runtime';
const rows=[{id:'a',title:'Crème aux œufs',ingredients:['2 œufs'],owner:0,group:'Végétarien'},{id:'b',title:'Crème aux œufs',ingredients:['2 œufs'],owner:1,group:'Végétarien'},{id:'c',title:'Poulet citron',ingredients:['Poulet'],group:'Poulet'},{id:'d',title:'Crème retirée',ingredients:[],owner:0,group:'Végétarien',archived:true}];
export const filters={mine:filterRecipes(rows,'creme oeufs','Végétarien','0').map(r=>r.id),ours:filterRecipes(rows,'','Tous','ours').map(r=>r.id),none:filterRecipes(rows,'','Poulet','1'),builtIn:filterRecipes(rows,'citron','Tous','discovery').map(r=>r.id)};
export const views={date:render(React.createElement('label',null,'Pour quand',React.createElement(DateField,{type:'date',name:'due',defaultValue:'2026-10-09'}))),picker:render(React.createElement(RecipePicker,{catalog:rows,names:['Alex','Camille'],meal:'Lundi midi',onChoose:()=>{},onBack:()=>{}})),wheel:render(React.createElement(HouseWheel,{names:['Alex','Camille'],date:'2026-10-09',initial:{home:{courses:2}}})),recipe:render(React.createElement(RecipeView,{recipe:{name:'Crème',servings:2,time:'15 min',difficulty:'Facile',ingredients:[{name:'Œufs',qty:'2'}],steps:[{title:'Préparer',text:'Mélanger.'}]},favorite:true,onFavorite:()=>{},onAddToList:()=>{}}))};`;
const fb=await build({stdin:{contents:features,resolveDir:process.cwd(),loader:'tsx'},bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',write:false});const fm={exports:{}};new Function('require','module','exports',fb.outputFiles[0].text)(require,fm,fm.exports);const fv=fm.exports;
assert.deepEqual(fv.filters.mine,['a']);assert.deepEqual(fv.filters.ours,['a','b']);assert.deepEqual(fv.filters.none,[]);assert.deepEqual(fv.filters.builtIn,['c']);assert(fv.views.date.includes('value="2026-10-09"'));assert(fv.views.date.includes('temporal-field'));assert(fv.views.picker.includes('Rechercher une recette'));assert(fv.views.wheel.includes('seg-nous'));assert(fv.views.wheel.includes('Nous deux'));assert(fv.views.recipe.includes('nd-recipe-sheet'));assert(fv.views.recipe.includes('aria-label="Recette favorite" aria-pressed="true"'));assert(css.includes('input[type]{position:absolute!important'));assert(css.includes('flex-direction:row!important'));
console.log('PASS: accent-aware combined author/category search, native date field value, searchable picker, supplied recipe sheet, favorites and three-person wheel rendering.');
// New public UI components render without requesting a microphone, network or household session.
const additions=`import React from 'react';import {renderToStaticMarkup as render} from 'react-dom/server';import {PlaceCard,PlacePicker,mapLinks,FavoriteRestaurants} from './app/house-places';import {VoiceMessage,recordingMime,voiceTime} from './app/chat-voice';import InvitationCelebration from './app/invitation-celebration';import {InvitationArrival} from './app/house-ideas';import {BudgetOverview} from './app/design-overviews';
const h=React.createElement,p={name:'Notre table',address:'12 rue Exemple, Paris',lat:48.85,lon:2.35,source:'osm',sourceId:'N123'};export const links=mapLinks(p);export const manual=mapLinks({...p,lat:null,lon:null,name:'A & B'});export const time=voiceTime(65000);export {recordingMime};
export const views={voice:render(h(VoiceMessage,{id:'test',duration:65000})),place:render(h(PlaceCard,{place:p})),picker:render(h(PlacePicker,{value:null,onChange:()=>{},favorites:[{...p,id:'x',owner:0,version:1}]})),confetti:render(h(InvitationCelebration)),arrival:render(h(InvitationArrival,{ideas:[{id:'i',owner:0,status:'pending',version:1,title:'Une table pour deux',description:'',category:'restaurant',date:'',time:'',location:'',place:p}],active:1,names:['A','B'],busy:false,error:'',save:async()=>true,onOpen:()=>{}})),budget:render(h(BudgetOverview,{entries:[],allEntries:[],names:['A','B'],total:0,paid:[0,0],credit:0,budget:0,month:'2026-10',monthPicker:null,onSettle:()=>{},onSettings:()=>{},onBudgets:async()=>true,busy:false,error:''}))};`;
const ab=await build({stdin:{contents:additions,resolveDir:process.cwd(),loader:'tsx'},bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',write:false});const am={exports:{}};new Function('require','module','exports',ab.outputFiles[0].text)(require,am,am.exports);const av=am.exports;
assert.equal(av.time,'1:05');assert(av.views.voice.includes('Écouter le vocal'));assert(!av.views.voice.includes('autoplay'));
assert(av.links.google.endsWith('destination=48.85%2C2.35'));assert(av.links.apple.endsWith('daddr=48.85%2C2.35'));assert(av.manual.google.includes('A%20%26%20B'));assert(av.views.place.includes('Google Maps'));assert(av.views.place.includes('Plans'));assert(!av.views.place.includes('<iframe'),'Map loads only after explicit expansion');assert(av.views.picker.includes('Nos restaurants favoris'));assert(av.views.picker.includes('Saisir l’adresse moi-même'));assert(av.views.confetti.includes('Pause des confettis'));assert(av.views.arrival.includes('Notre table'));assert(av.views.arrival.includes('invitation-confetti'));assert(av.views.budget.includes('id="budget-charts"'));assert(av.views.budget.includes('Nos six derniers mois'));assert(av.views.budget.includes('Le rythme du mois'));assert(!av.views.budget.includes('Masquer les graphiques'));assert(!av.views.budget.includes('Voir les graphiques'));assert(av.views.budget.indexOf('Régler les budgets')<av.views.budget.indexOf('</section>'),'Budget action inside its section');
globalThis.MediaRecorder={isTypeSupported:m=>m==='audio/mp4'};assert.equal(av.recordingMime(),'audio/mp4');globalThis.MediaRecorder={isTypeSupported:m=>m==='audio/webm;codecs=opus'};assert.equal(av.recordingMime(),'audio/webm;codecs=opus');delete globalThis.MediaRecorder;
assert(!css.includes('contain:inline-size'));assert(css.includes('.nd-heat,.nd-heat-dows{grid-template-columns:repeat(7,minmax(0,1fr))'));assert(css.includes('.nd-heat-scale{margin-top:24px'));assert(css.includes('.chat-composer>div.voice-recorder{display:grid'));assert(css.includes('.invitation-confetti,.celebration-toggle{display:none}'));
console.log('PASS: invitation place and pausable decoration, safe map navigation, voice playback entry, MP4/WebM format negotiation and date/heatmap/composer layout regressions.');

assert(!v.home.includes('S’appeler'));assert(!v.home.includes('Nos nouvelles'));assert(!v.home.includes('Notre espace'));assert(av.views.place.includes('place-navigation-links'));assert(av.views.place.includes('Voir sur la carte'));assert(v.calendar.includes('calendar-control-top'));assert(v.calendar.includes('calendar-period-navigation'));
console.log('PASS: always-visible budget charts, contextual header shortcuts, structured place navigation and two-row calendar controls.');
// Invitation category is retained for all five countdown companions, including home/surprise.
const momentsSource=`import React from 'react';import {renderToStaticMarkup as render} from 'react-dom/server';import {momentKind,MomentBuddy} from './app/moment-buddy';import HomeMoments from './app/home-moments';import HouseShopping from './app/house-shopping';import {parisDate} from './lib/life';
const kinds=['restaurant','outing','home','trip','surprise'];const ideas=kinds.map((category,i)=>({id:'idea-'+i,category}));const events=ideas.map((idea,i)=>({id:'event-'+i,sourceIdeaId:idea.id,category:['party','party','home','travel','personal'][i],date:parisDate(),title:'Moment '+i,status:'scheduled',visibility:'shared'}));
export const actual=events.map(event=>momentKind(event,ideas));export const svgs=kinds.map(kind=>render(React.createElement(MomentBuddy,{kind})));export const home=render(React.createElement(HomeMoments,{plants:[],appointments:events.slice(2),ideas,onGarden:()=>{},onCalendar:()=>{}}));export const fallback=momentKind({category:'birthday'});
export const bought=render(React.createElement(HouseShopping,{items:[{id:'i',title:'Bananes',kind:'shopping',weekStart:'2026-10-05',done:true,owner:0,purchasedBy:0,quantity:'',version:1}],templates:[],names:['A','B'],active:0,week:'2026-10-05',setWeek:()=>{},busy:false,online:true,save:async()=>true,onEdit:()=>{},onExpense:()=>{}}));`;
const mb=await build({stdin:{contents:momentsSource,resolveDir:process.cwd(),loader:'tsx'},bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',write:false});const mm={exports:{}};new Function('require','module','exports',mb.outputFiles[0].text)(require,mm,mm.exports);const mv=mm.exports;
assert.deepEqual(mv.actual,['restaurant','outing','home','trip','surprise']);assert.equal(mv.fallback,'birthday');assert.equal(new Set(mv.svgs).size,5);for(const html of mv.svgs)assert(html.includes('moment-pupils'));assert(mv.home.includes('data-moment-kind="home"'));assert(mv.home.includes('data-moment-kind="surprise"'));assert(mv.bought.includes('role="img" aria-label="Acheté"'));assert(!mv.bought.includes('class="purchase-check"'));assert.equal((mv.bought.match(/class="undo-purchase text-link"/g)||[]).length,1);
console.log('PASS: category-specific countdown companions, home/surprise inclusion, travel preservation, animated eyes and a single undo action for purchased groceries.');
