import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {realpathSync} from 'node:fs';
const {build}=createRequire(realpathSync('node_modules/wrangler/package.json'))('esbuild');
const b=await build({entryPoints:['supabase/functions/house-api/recipe-library.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'npm',setup(b){b.onResolve({filter:/^npm:zod@/},()=>({path:realpathSync('node_modules/zod/index.js')}));}}]});
const {recipeMutation:mutate,knownRecipe}=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));
const s={},id=crypto.randomUUID(),recipe={id,version:0,title:'Le riz de Camille',group:'Végétarien',minutes:25,servings:4,ingredients:['200 g de riz','2 carottes'],steps:['Cuire le riz.','Ajouter les carottes.'],photoId:null,calories:420,nutrients:'Vitamine C : 10 mg',porkFree:true,owner:1};
mutate(s,{action:'recipe-save',payload:recipe},0);mutate(s,{action:'recipe-save',payload:recipe},0);assert.equal(s.personalRecipes.length,1);assert.equal(s.personalRecipes[0].owner,0);assert.equal(s.personalRecipes[0].version,1);assert.equal(s.personalRecipes[0].servings,4);assert.equal(s.personalRecipes[0].calories,420);assert(knownRecipe(s,id,true));
assert.throws(()=>mutate(s,{action:'recipe-save',payload:{...recipe,version:1}},1),e=>e.status===403);
assert.throws(()=>mutate(s,{action:'recipe-archive',payload:{id,version:1}},1),e=>e.status===403);
assert.throws(()=>mutate(s,{action:'recipe-save',payload:{...recipe,title:'Ancienne version'}},0),e=>e.status===409);
for(const invalid of [{servings:0},{calories:-1},{minutes:0},{ingredients:[]},{steps:[]},{porkFree:false},{photoId:'https://example.com/photo'},{nutrients:'x'.repeat(701)}])assert.throws(()=>mutate({}, {action:'recipe-save',payload:{...recipe,...invalid}},0));
const planId=crypto.randomUUID(),slots=[{day:0,meal:'lunch',recipeId:id},{day:4,meal:'dinner',recipeId:'shakshuka'}];
const plan={id:planId,version:0,weekStart:'2026-10-05',slots,owner:1};mutate(s,{action:'plan-save',payload:plan},0);assert.equal(s.mealPlans[0].owner,0);
assert.throws(()=>mutate(s,{action:'plan-save',payload:{...plan,id:crypto.randomUUID()}},0),e=>e.status===409);
assert.throws(()=>mutate(s,{action:'plan-save',payload:{...plan,version:1}},1),e=>e.status===403);
assert.throws(()=>mutate(s,{action:'plan-delete',payload:{id:planId,version:1}},1),e=>e.status===403);
assert.throws(()=>mutate(s,{action:'plan-save',payload:{...plan,id:crypto.randomUUID(),weekStart:'2026-10-06'}},0));
assert.throws(()=>mutate(s,{action:'plan-save',payload:{...plan,id:crypto.randomUUID(),slots:[...slots,slots[0]]}},1));
assert.throws(()=>mutate(s,{action:'plan-save',payload:{...plan,id:crypto.randomUUID(),slots:[{day:0,meal:'lunch',recipeId:'made-up'}]}},1),e=>e.status===400);
// Each member may have an independent plan in the same week.
mutate(s,{action:'plan-save',payload:{...plan,id:crypto.randomUUID()}},1);assert.equal(s.mealPlans.length,2);
const menuId=crypto.randomUUID(),menu={id:menuId,title:'Semaine facile',planId,planVersion:1};mutate(s,{action:'menu-save',payload:menu},0);mutate(s,{action:'menu-save',payload:menu},0);assert.equal(s.mealPlanTemplates.length,1);
mutate(s,{action:'plan-save',payload:{...plan,version:1,slots:[{day:1,meal:'dinner',recipeId:id}]}},0);assert.equal(s.mealPlanTemplates[0].slots.length,2,'Template is a snapshot, not a mutable reference');
const copy={id:crypto.randomUUID(),templateId:menuId,weekStart:'2026-10-12'};mutate(s,{action:'menu-apply',payload:copy},1);mutate(s,{action:'menu-apply',payload:copy},1);assert.equal(s.mealPlans.length,3,'Network retry cannot duplicate a week');assert.deepEqual(s.mealPlans[2].slots,slots);assert.equal(s.mealPlans[2].owner,1);
assert.throws(()=>mutate(s,{action:'menu-apply',payload:{...copy,id:crypto.randomUUID()}},1),e=>e.status===409,'Do not overwrite an existing week');
assert.throws(()=>mutate(s,{action:'menu-delete',payload:{id:menuId}},1),e=>e.status===403);
mutate(s,{action:'recipe-archive',payload:{id,version:1}},0);assert(!knownRecipe(s,id,true));assert(knownRecipe(s,id));assert.equal(s.mealPlans[2].slots[0].recipeId,id,'Historical menus keep archived recipes');
mutate(s,{action:'menu-delete',payload:{id:menuId}},0);assert.equal(s.mealPlanTemplates.length,0);assert.equal(s.mealPlans.length,3,'Deleting a favorite preserves all copied weeks');
assert.throws(()=>mutate(s,{action:'plan-save',payload:plan},2),e=>e.status===403);
console.log('PASS: personal recipes, nutrition validation, author-only editing, version conflicts, independent weeks, immutable menu templates, idempotent copies, no overwrite and retained historical recipes.');
