import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {realpathSync} from 'node:fs';
const {build}=createRequire(realpathSync('node_modules/wrangler/package.json'))('esbuild');
const bundle=await build({entryPoints:['supabase/functions/house-api/model.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'npm-prefix',setup(b){b.onResolve({filter:/^npm:zod@/},()=>({path:realpathSync('node_modules/zod/index.js')}));}}]});
const {householdMutation,callMutation,deviceMutation}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const s={household:null,entries:[],items:[],appointments:[],activity:[],devices:[],call:null,sequence:0};
householdMutation(s,{action:'household',payload:{first:'Alex',second:'Camille',name:'Test',budget:0,version:0}},0);
const id=crypto.randomUUID();const entry={id,kind:'expense',title:'Courses',cents:12000,member:0,category:'Courses',date:'2026-10-09',note:'',version:0};
householdMutation(s,{action:'entry',payload:entry},0);assert.equal(s.entries[0].version,1);assert.equal(s.activity.length,1);
assert.throws(()=>householdMutation(s,{action:'entry',payload:entry},0),e=>e.status===409);
householdMutation(s,{action:'entry',payload:{...entry,cents:14000,version:1}},0);assert.equal(s.entries[0].cents,14000);
assert.throws(()=>householdMutation(s,{action:'entry',payload:{...entry,cents:-1}},0));
const aid=crypto.randomUUID();const ap={id:aid,title:'Dentiste',category:'medical',person:0,status:'to_book',date:'',time:'',bookBy:'',location:'',note:'',version:0};householdMutation(s,{action:'appointment',payload:ap},1);householdMutation(s,{action:'appointment',payload:{...ap,status:'scheduled',date:'2026-10-20',time:'10:00',version:1}},1);assert.equal(s.appointments[0].status,'scheduled');
const callId=crypto.randomUUID(),one=crypto.randomUUID(),two=crypto.randomUUID(),third=crypto.randomUUID(),offer='v=0\r\nm=audio 123 RTP/AVP 0\r\n';
callMutation(s,{action:'start',id:callId,session:one,member:0,offer});assert.throws(()=>callMutation(s,{action:'start',id:crypto.randomUUID(),session:third,member:1,offer}),e=>e.status===409);
callMutation(s,{action:'answer',id:callId,session:two,member:1,answer:offer});assert.throws(()=>callMutation(s,{action:'answer',id:callId,session:third,member:1,answer:offer}),e=>e.status===409);
assert.throws(()=>callMutation(s,{action:'end',id:callId,session:third,member:1}),e=>e.status===403);callMutation(s,{action:'end',id:callId,session:two,member:1});assert.equal(s.call.offer,'');
assert.throws(()=>deviceMutation(s,{action:'subscribe',deviceId:crypto.randomUUID(),member:0,preferences:{shopping:true,tasks:true,expenses:true,calendar:true,calls:true},subscription:{endpoint:'http://127.0.0.1/private',keys:{p256dh:'x'.repeat(87),auth:'x'.repeat(22)}}}));
console.log('PASS: expense validation, stale writes, appointment planning, call participants, answer races and push endpoint restrictions.');
// Access control: visibility is shared, writes belong to the authenticated author.
assert.throws(()=>householdMutation(s,{action:'entry',payload:{...entry,version:2,member:1,owner:1}},1),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'delete-entry',payload:{id,version:2}},1),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'entry',payload:{...entry,id:crypto.randomUUID(),version:0,member:1}},0),e=>e.status===403);
const task={id:crypto.randomUUID(),kind:'task',title:'Test auteur',quantity:'',assignee:1,due:'',priority:0,done:false,version:0,owner:1};
householdMutation(s,{action:'item',payload:task},0);assert.equal(s.items[0].owner,0);
assert.throws(()=>householdMutation(s,{action:'item',payload:{...task,version:1,done:true}},1),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'delete-item',payload:{id:task.id,version:1}},1),e=>e.status===403);
householdMutation(s,{action:'item',payload:{...task,version:1,done:true}},0);assert.equal(s.items[0].done,true);
s.items[0].owner=null;assert.throws(()=>householdMutation(s,{action:'delete-item',payload:{id:task.id,version:2}},0),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'delete-appointment',payload:{id:aid,version:2}},0),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'household',payload:{...s.household,second:'Usurpe'}},0),e=>e.status===403);
console.log('PASS: cross-account updates/deletes, forged payer/owner, legacy records and partner profile changes are denied.');
const {visibleAppointments}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const privateId=crypto.randomUUID(),privateEvent={...ap,id:privateId,status:'scheduled',date:'2026-10-10',endDate:'2026-10-15',recurrence:'yearly',visibility:'private',version:0};
let before=s.activity.length;assert.equal(householdMutation(s,{action:'appointment',payload:privateEvent},0),null);assert.equal(s.activity.length,before);
assert(visibleAppointments(s,0).some(a=>a.id===privateId));assert(!visibleAppointments(s,1).some(a=>a.id===privateId));
assert.throws(()=>householdMutation(s,{action:'appointment',payload:{...privateEvent,version:1,visibility:'shared'}},1),e=>e.status===403);
householdMutation(s,{action:'appointment',payload:{...privateEvent,version:1,visibility:'shared'}},0);assert(visibleAppointments(s,1).some(a=>a.id===privateId));assert(s.activity.some(a=>a.appointmentId===privateId));
householdMutation(s,{action:'appointment',payload:{...privateEvent,version:2,visibility:'private'}},0);assert(!s.activity.some(a=>a.appointmentId===privateId));assert(!visibleAppointments(s,1).some(a=>a.id===privateId));
assert.equal(householdMutation(s,{action:'delete-appointment',payload:{id:privateId,version:3}},0),null);
assert.throws(()=>householdMutation(s,{action:'appointment',payload:{...privateEvent,endDate:'2026-10-01'}},0));
console.log('PASS: private events excluded from partner data, activity and notification intents; sharing transitions and date validation.');
// Either member may record a purchase; server-derived attribution is immutable by the partner.
const shop={...task,id:crypto.randomUUID(),kind:'shopping',title:'Bananes',weekStart:'2026-10-05',done:false,version:0};
householdMutation(s,{action:'item',payload:shop},0);
let purchased=s.items.find(i=>i.id===shop.id);
householdMutation(s,{action:'shopping-check',payload:{id:shop.id,version:1,done:true,purchasedBy:0}},1);
assert.equal(purchased.purchasedBy,1);assert.equal(purchased.owner,0);assert.equal(purchased.done,true);
assert.throws(()=>householdMutation(s,{action:'shopping-check',payload:{id:shop.id,version:1,done:true}},0),e=>e.status===409);
assert.throws(()=>householdMutation(s,{action:'shopping-check',payload:{id:shop.id,version:2,done:false}},0),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'item',payload:{...shop,version:2,done:false}},0),e=>e.status===400);
assert.throws(()=>householdMutation(s,{action:'item',payload:{...shop,kind:'task',version:2}},0),e=>e.status===400);
householdMutation(s,{action:'item',payload:{...shop,version:2,done:true,purchasedBy:0}},0);
purchased=s.items.find(i=>i.id===shop.id);assert.equal(purchased.purchasedBy,1);
householdMutation(s,{action:'shopping-check',payload:{id:shop.id,version:3,done:false}},1);assert.equal(purchased.purchasedBy,null);assert.equal(purchased.done,false);
const templateId=crypto.randomUUID();householdMutation(s,{action:'template-create',payload:{id:templateId,title:'Les essentiels',weekStart:'2026-10-05'}},0);
assert.equal(s.templates[0].items[0].title,'Bananes');assert.equal(s.templates[0].owner,0);
const operationId=crypto.randomUUID(),beforeApply=s.items.length;
householdMutation(s,{action:'template-apply',payload:{id:templateId,operationId,weekStart:'2026-10-12',owner:0}},1);
assert.equal(s.items.length,beforeApply+1);assert.equal(s.items.at(-1).owner,1);assert.equal(s.items.at(-1).done,false);assert.equal(s.items.at(-1).weekStart,'2026-10-12');
householdMutation(s,{action:'template-apply',payload:{id:templateId,operationId,weekStart:'2026-10-12'}},1);assert.equal(s.items.length,beforeApply+1);
assert.throws(()=>householdMutation(s,{action:'template-delete',payload:{id:templateId}},1),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'template-apply',payload:{id:templateId,operationId:crypto.randomUUID(),weekStart:'2026-10-13'}},1),e=>e.status===400);
householdMutation(s,{action:'template-delete',payload:{id:templateId}},0);assert.equal(s.templates.length,0);assert.equal(s.items.length,beforeApply+1);
const {authorizeChat,weekMonday}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
assert.equal(weekMonday('2027-01-01'),'2026-12-28');assert.equal(weekMonday('2026-10-11'),'2026-10-05');
assert.throws(()=>authorizeChat({member:0,version:2},1,2),e=>e.status===403);
assert.throws(()=>authorizeChat({member:0,version:2},0,1),e=>e.status===409);
assert.doesNotThrow(()=>authorizeChat({member:0,version:2},0,2));
console.log('PASS: cross-member shopping checks, buyer integrity, status bypasses, weekly template copies, retries and author-only chat changes.');
