import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {realpathSync} from 'node:fs';
const {build}=createRequire(realpathSync('node_modules/wrangler/package.json'))('esbuild');
const bundle=await build({entryPoints:['supabase/functions/house-api/model.ts'],bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'npm-prefix',setup(b){b.onResolve({filter:/^npm:zod@/},()=>({path:realpathSync('node_modules/zod/index.js')}));}}]});
const {householdMutation,callMutation,deviceMutation}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const s={household:null,entries:[],items:[],appointments:[],activity:[],devices:[],call:null,sequence:0};
householdMutation(s,{action:'household',payload:{first:'Alex',second:'Camille',name:'Test',budget:0,version:0}},0);
const id=crypto.randomUUID();const entry={id,kind:'expense',title:'Courses',cents:12000,member:0,category:'Courses',date:'2026-10-09',note:'',version:0};
householdMutation(s,{action:'entry',payload:entry},0);assert.equal(s.entries[0].version,1);assert.equal(s.activity.length,1);
assert.throws(()=>householdMutation(s,{action:'entry',payload:entry},0),e=>e.status===409);
householdMutation(s,{action:'entry',payload:{...entry,cents:14000,version:1}},0);assert.equal(s.entries[0].cents,14000);
assert.throws(()=>householdMutation(s,{action:'entry',payload:{...entry,cents:-1}},0));
const aid=crypto.randomUUID();const ap={id:aid,title:'Dentiste',category:'medical',person:0,status:'to_book',date:'',time:'',bookBy:'',location:'',note:'',version:0};householdMutation(s,{action:'appointment',payload:ap},1);householdMutation(s,{action:'appointment',payload:{...ap,status:'scheduled',date:'2026-10-20',time:'10:00',version:1}},1);assert.equal(s.appointments[0].status,'scheduled');
const callId=crypto.randomUUID(),one=crypto.randomUUID(),two=crypto.randomUUID(),third=crypto.randomUUID(),offer='v=0\r\nm=audio 123 RTP/AVP 0\r\n';
callMutation(s,{action:'start',id:callId,session:one,member:0,offer});assert.throws(()=>callMutation(s,{action:'start',id:crypto.randomUUID(),session:third,member:1,offer}),e=>e.status===409);
callMutation(s,{action:'answer',id:callId,session:two,member:1,answer:offer});assert.throws(()=>callMutation(s,{action:'answer',id:callId,session:third,member:1,answer:offer}),e=>e.status===409);
assert.throws(()=>callMutation(s,{action:'end',id:callId,session:third,member:1}),e=>e.status===403);callMutation(s,{action:'end',id:callId,session:two,member:1});assert.equal(s.call.offer,'');
assert.throws(()=>deviceMutation(s,{action:'subscribe',deviceId:crypto.randomUUID(),member:0,preferences:{shopping:true,tasks:true,expenses:true,calendar:true,calls:true},subscription:{endpoint:'http://127.0.0.1/private',keys:{p256dh:'x'.repeat(87),auth:'x'.repeat(22)}}}));
console.log('PASS: expense validation, stale writes, appointment planning, call participants, answer races and push endpoint restrictions.');
// Access control: visibility is shared, writes belong to the authenticated author.
assert.throws(()=>householdMutation(s,{action:'entry',payload:{...entry,version:2,member:1,owner:1}},1),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'delete-entry',payload:{id,version:2}},1),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'entry',payload:{...entry,id:crypto.randomUUID(),version:0,member:1}},0),e=>e.status===403);
const task={id:crypto.randomUUID(),kind:'task',title:'Test auteur',quantity:'',assignee:1,due:'',priority:0,done:false,version:0,owner:1};
householdMutation(s,{action:'item',payload:task},0);assert.equal(s.items[0].owner,0);
assert.throws(()=>householdMutation(s,{action:'item',payload:{...task,version:1,done:true}},1),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'delete-item',payload:{id:task.id,version:1}},1),e=>e.status===403);
householdMutation(s,{action:'item',payload:{...task,version:1,done:true}},0);assert.equal(s.items[0].done,true);
s.items[0].owner=null;assert.throws(()=>householdMutation(s,{action:'delete-item',payload:{id:task.id,version:2}},0),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'delete-appointment',payload:{id:aid,version:2}},0),e=>e.status===403);
assert.throws(()=>householdMutation(s,{action:'household',payload:{...s.household,second:'Usurpe'}},0),e=>e.status===403);
console.log('PASS: cross-account updates/deletes, forged payer/owner, legacy records and partner profile changes are denied.');
