'use client';
import {apiFetch,APP_BASE} from '../lib/api-client';
import {useEffect,useState} from 'react';
import {Heart,LockKeyhole} from 'lucide-react';
export default function AccessForm(){
 const[member,setMember]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('member')==='1'?1:0);
 const[ready,setReady]=useState(false),[configured,setConfigured]=useState(true),[setupToken,setSetupToken]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const token=new URLSearchParams(location.hash.slice(1)).get('setup')||'';if(token){setSetupToken(token);history.replaceState(null,'',location.pathname);}setReady(false);localStorage.setItem('nous-deux-member',String(member));apiFetch('/api/access?member='+member,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{configured:boolean}>;}).then(d=>{setConfigured(d.configured);setReady(true);}).catch(()=>setError('Connexion indisponible. Actualisez la page.'));},[member]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!configured&&password!==confirm){setError('Les deux mots de passe doivent être identiques.');return;}setBusy(true);try{const r=await apiFetch('/api/access?member='+member,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:configured?'login':'setup',password,setupToken,member})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);location.replace(APP_BASE);}catch(e){setError(e instanceof Error?e.message:'Connexion impossible.');setBusy(false);}}
 return <main className="access-page"><section className="access-card"><div className="access-heart"><img src={APP_BASE+'favicon.svg'} width="72" height="72" alt="À deux"/></div><span className="eyebrow">BIENVENUE CHEZ VOUS</span><h1>Votre quotidien,<br/><em>à deux.</em></h1><p>{configured?'Entrez votre mot de passe personnel.':'Choisissez votre mot de passe personnel. Votre moitié aura le sien.'}</p><label htmlFor="account">Mon compte</label><select id="account" value={member} disabled={!!setupToken} onChange={e=>{setPassword('');setConfirm('');setMember(Number(e.target.value));}}><option value={0}>Abdellah</option><option value={1}>Laura</option></select>{ready&&(configured||setupToken)?<form onSubmit={submit}><label htmlFor="house-password">{configured?'Mon mot de passe':'Votre nouveau mot de passe'}</label><input id="house-password" type="password" autoComplete={configured?'current-password':'new-password'} minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/>{!configured&&<><small>Au moins 12 caractères. Une phrase facile à retenir convient.</small><label htmlFor="house-confirm">Confirmer le mot de passe</label><input id="house-confirm" type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></>}<button className="primary wide" disabled={busy}>{busy?'Ouverture…':configured?'Entrer dans notre maison':'Créer notre accès privé'}</button></form>:<p>{ready?'Ce compte attend son activation. Utilisez votre lien personnel de préparation.':'On prépare votre entrée…'}</p>}{error&&<p role="alert" className="form-error">{error}</p>}<p className="privacy-note"><LockKeyhole size={14}/>Connexion mémorisée sur cet appareil pendant 90 jours.<br/>Aucun compte ChatGPT ou GitHub nécessaire.</p></section></main>;
}
