import {useEffect,useRef,useState} from 'react';
import {FileText,Download,Image as ImageIcon,Send,Trash2,Check,RefreshCw,ExternalLink} from './icons';
import {apiFetch} from '../lib/api-client';
import LifeDialog from './life-dialog';
export const MAX_FILE_BYTES=30*1024*1024;
export const CHAT_FILE_ACCEPT='.jpg,.jpeg,.png,.gif,.webp,.heic,.heif,.avif,.pdf,.docx,.xlsx,.pptx,.txt,.csv';
export const fileSize=(bytes:number)=>bytes<1024*1024?Math.max(1,Math.round(bytes/1024))+' Ko':(bytes/(1024*1024)).toLocaleString('fr-FR',{maximumFractionDigits:1})+' Mo';
type Links={url:string;download:string};
export function AttachmentMessage({id,name,mime,bytes,onLoad}:{id:string;name:string;mime:string;bytes:number;onLoad?:()=>void}){
 const[links,setLinks]=useState<Links|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[broken,setBroken]=useState(false),[view,setView]=useState(false);const generation=useRef(0);
 const isImage=mime.startsWith('image/');
 async function load(){const seq=++generation.current;setBusy(true);setError('');setBroken(false);try{const r=await apiFetch('/api/attachments?id='+id);const d=await r.json();if(!r.ok)throw Error(d.error||'Fichier indisponible.');if(seq===generation.current)setLinks(d);}catch(e){if(seq===generation.current)setError(e instanceof Error?e.message:'Ouverture impossible.');}finally{if(seq===generation.current)setBusy(false);}}
 useEffect(()=>{load();return()=>{++generation.current;};},[id]);
 return <div className="chat-attachment">{isImage&&links&&!broken&&!error&&<button type="button" className="chat-image-preview" onClick={()=>setView(true)} aria-label={'Agrandir '+name}><img src={links.url} alt={name} loading="lazy" onLoad={onLoad} onError={()=>setBroken(true)}/></button>}<div className="chat-file-info">{isImage?<ImageIcon size={23}/>:<FileText size={23}/>}<span><strong>{name}</strong><small>{mime==='application/pdf'?'PDF':name.split('.').at(-1)?.toUpperCase()} · {fileSize(bytes)}</small></span></div>{error?<p className="helper-copy" role="alert">{error}</p>:broken&&<p className="helper-copy">Aperçu indisponible. Vous pouvez ouvrir ou télécharger l’original.</p>}<div className="chat-file-actions">{links&&!error?<><a href={links.url} target="_blank" rel="noopener noreferrer" className="secondary"><ExternalLink size={16}/>Ouvrir</a><a href={links.download} target="_blank" rel="noopener noreferrer" download={name} className="secondary" aria-label={'Télécharger '+name}><Download size={16}/><span>Télécharger</span></a><button type="button" className="icon-button" onClick={load} aria-label="Renouveler le lien du fichier" title="Renouveler le lien du fichier"><RefreshCw size={16}/></button></>:<button type="button" className="secondary" disabled={busy} onClick={load}><RefreshCw size={16}/>{busy?'Chargement…':'Réessayer'}</button>}</div>{view&&links&&<LifeDialog title={name} onClose={()=>setView(false)} className="chat-image-dialog"><img src={links.url} alt={name}/><a className="secondary" href={links.download} target="_blank" rel="noopener noreferrer" download={name}><Download size={18}/>Télécharger l’image</a></LifeDialog>}</div>;
}
type Draft={file:File;id:string;messageId:string;uploaded:boolean;sent:boolean};
function FilePreview({file}:{file:File}){const[url,setUrl]=useState(''),[broken,setBroken]=useState(false);useEffect(()=>{if(!/\.(jpe?g|png|gif|webp|heic|heif|avif)$/i.test(file.name))return;const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);return url&&!broken?<img src={url} alt="" onError={()=>setBroken(true)}/>:<FileText size={26}/>;}
export function AttachmentComposer({files,onClose,onSent}:{files:File[];onClose:()=>void;onSent:()=>Promise<void>}){
 const[drafts,setDrafts]=useState<Draft[]>(()=>files.map(file=>({file,id:crypto.randomUUID(),messageId:crypto.randomUUID(),uploaded:false,sent:false}))),[caption,setCaption]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState('');const running=useRef(false);
 async function send(){if(running.current)return;running.current=true;setBusy(true);setError('');try{
  for(let i=0;i<drafts.length;i++){const draft=drafts[i];if(draft.sent)continue;setStatus(`Envoi ${i+1} sur ${drafts.length}…`);
   if(!draft.uploaded){const query=new URLSearchParams({id:draft.id,name:draft.file.name}),r=await apiFetch('/api/attachment-upload?'+query,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:draft.file,signal:AbortSignal.timeout(180000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Fichier non enregistré.');draft.uploaded=true;}
   const r=await apiFetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'send',id:draft.messageId,attachmentId:draft.id,...(i===0&&caption.trim()?{text:caption.trim()}:{})}),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Envoi impossible.');draft.sent=true;setDrafts([...drafts]);
  }
  await onSent();onClose();
 }catch(e){setError((e instanceof Error?e.message:'Connexion interrompue.')+' Les fichiers restants sont conservés ici pour réessayer.');await onSent();}finally{running.current=false;setBusy(false);setStatus('');}}
 async function close(){if(running.current)return;for(const d of drafts.filter(d=>d.uploaded&&!d.sent)){try{await apiFetch('/api/attachments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'discard',id:d.id})});}catch{/* Drafts remain private. */}}onClose();}
 return <LifeDialog title={files.length===1?'Un fichier pour vous deux':'Quelques fichiers à partager'} busy={busy} onClose={close}><p className="helper-copy">Photos, PDF et documents · 30 Mo par fichier</p><div className="chat-upload-list">{drafts.map((d,i)=><article className="chat-upload-row" key={d.id}><FilePreview file={d.file}/><div><strong>{d.file.name}</strong><small>{fileSize(d.file.size)}{d.sent?' · Envoyé':''}</small></div>{d.sent?<Check size={20}/>:<button type="button" disabled={busy||d.uploaded} className="icon-button" aria-label={'Retirer '+d.file.name} onClick={()=>{const next=drafts.filter((_,n)=>n!==i);if(next.length)setDrafts(next);else onClose();}}><Trash2 size={18}/></button>}</article>)}</div><label className="chat-upload-caption">Un petit mot <span className="optional">(facultatif · accompagne le premier fichier)</span><textarea value={caption} maxLength={2000} disabled={busy||drafts.some(d=>d.sent)} onChange={e=>setCaption(e.target.value)} rows={2}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<p role="status" className="chat-upload-status">{status}</p><div className="chat-upload-actions"><button className="secondary" disabled={busy} onClick={close}>Annuler</button><button className="primary" disabled={busy} onClick={send}><Send size={18}/>{busy?'Envoi…':error?'Réessayer':'Envoyer'}</button></div></LifeDialog>;
}
