import {useState,type ReactNode} from 'react';
import {SlidersHorizontal} from './icons';
import LifeDialog from './life-dialog';
import {HeroCard,CategoryTile,PiggyBank,SplitBar,RankedBars,BillCard,Button,StatTile,BarChart,LineChart,CalendarHeatmap,DivergingBars,GaugeTile} from '../design-system/runtime';
import {categories,money,centsFromInput,today,type Entry} from '../lib/domain';
export function HomeOverview({counts,onNavigate,children}:{counts:{shopping:number;tasks:number;matches:number;ideas:number;plants:number};onNavigate:(tab:string)=>void;children:ReactNode}){
 return <div className="overview"><HeroCard tone="citron" title={<>Notre quotidien,<br/><em>à deux.</em></>} text="Un peu d’organisation, beaucoup de nous." action="Voir notre journée" onAction={()=>onNavigate('calendar')} buddy={{shape:'flower',tone:'lavande',mood:'happy'}}/>
 <section aria-label="Les espaces de notre maison"><div className="section-title"><h2>On fait quoi ?</h2></div><div className="category-grid">
 <CategoryTile title="Les courses" count={`${counts.shopping} à acheter`} tone="menthe" onClick={()=>onNavigate('shopping')}/>
 <CategoryTile title="À table" count={counts.matches?`${counts.matches} match${counts.matches>1?'s':''}`:'À découvrir'} tone="rose" onClick={()=>onNavigate('meals')}/>
 <CategoryTile title="Nos missions" count={`${counts.tasks} à faire`} tone="lavande" onClick={()=>onNavigate('tasks')}/>
 <CategoryTile title="Nos idées" count={counts.ideas?`${counts.ideas} invitation${counts.ideas>1?'s':''}`:'À imaginer'} tone="beurre" onClick={()=>onNavigate('ideas')}/>
 <CategoryTile title="Le jardin" count={`${counts.plants} plante${counts.plants>1?'s':''}`} tone="menthe" onClick={()=>onNavigate('plants')}/>
 <CategoryTile title="Notre argent" count="Notre budget" tone="peche" onClick={()=>onNavigate('expenses')}/>
 </div></section>{children}</div>;
}
export function BudgetOverview({entries,allEntries,names,total,paid,credit,budget,categoryBudgets={},month,monthPicker,onSettle,onSettings,onBudgets,busy,error}:{entries:Entry[];allEntries:Entry[];names:string[];total:number;paid:number[];credit:number;budget:number;categoryBudgets?:Record<string,number>;month:string;monthPicker:ReactNode;onSettle:()=>void;onSettings:()=>void;onBudgets:(budgets:Record<string,number>)=>Promise<boolean>;busy:boolean;error:string}){
 const[editing,setEditing]=useState(false),[localError,setLocalError]=useState('');
 const verdict=credit===0?'On est à l’équilibre.':`${names[credit>0?1:0]} doit ${money(Math.abs(credit))} à ${names[credit>0?0:1]}.`;
 const tones=['menthe','lilas','beurre','rose','peche','lavande'] as const,emojis=['🛒','🏡','🧾','🎟️','🚲','✨'];
 const sums=categories.map((label,i)=>({label,value:entries.filter(e=>e.category===label).reduce((n,e)=>n+e.cents,0)/100,budget:categoryBudgets[label]?categoryBudgets[label]/100:undefined,tone:tones[i],emoji:emojis[i]}));
 const start=new Date(month+'-01T12:00:00Z'),dayCount=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate();
 const days=Array.from({length:dayCount},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return {day:i+1,value:entries.filter(e=>e.date===date).reduce((n,e)=>n+e.cents,0)/100,today:date===today()};});
 const months=Array.from({length:6},(_,i)=>{const date=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()-5+i,1,12)),key=date.toISOString().slice(0,7);return {label:date.toLocaleDateString('fr-FR',{month:'short',year:'2-digit',timeZone:'UTC'}),values:[0,1].map(member=>allEntries.filter(e=>e.kind==='expense'&&e.member===member&&e.date.startsWith(key)).reduce((n,e)=>n+e.cents,0)/100)};});
 const cumul=days.map((_,i)=>days.slice(0,i+1).reduce((n,d)=>n+d.value,0));const limited=sums.filter(c=>c.budget!==undefined);const bills=entries.filter(e=>e.category==='Factures');
 return <div className="budget-overview"><div className="section-title"><h2>Ce mois-ci</h2>{monthPicker}</div><div className="budget-grid">
 {budget>0?<PiggyBank variant="bulle" label="Notre budget commun" value={total/100} goal={budget/100} note={total>budget?`${money(total-budget)} au-delà du budget`:`Il reste ${money(budget-total)} ce mois-ci`}/>:<div className="budget-no-goal"><PiggyBank variant="bulle" label="Nos dépenses du mois" value={total/100} goal={0} note="Notre tirelire veille au grain. Aucun budget fixé."/><Button variant="secondary" onClick={onSettings}>Définir notre budget</Button></div>}
 <div className="budget-detail"><BillCard label="L’équilibre entre nous" amount={money(Math.abs(credit))} status={credit===0?'paid':'unpaid'} statusText={credit===0?'À jour':'À rembourser'}><p>{verdict}</p><p className="helper-copy">Depuis le début, remboursements compris.</p>{credit!==0&&<Button variant="primary" onClick={onSettle}>Noter un retour</Button>}</BillCard>
 {total>0?<SplitBar title="Qui a avancé quoi ?" subtitle="Les dépenses du mois sélectionné" items={names.map((name,i)=>({name,value:paid[i]/100,color:i===0?'data-1':'data-2'}))} verdict={verdict}/>:<StatTile label="Ce que chacun a avancé" value="Aucune dépense" tone="lavande"/>}</div></div>
 <section className="category-budget-card"><RankedBars title="Nos budgets par catégorie" subtitle="Les plafonds mensuels que vous choisissez" items={sums}/><footer><button className="secondary" onClick={()=>setEditing(true)}><SlidersHorizontal size={18}/>Régler les budgets</button></footer></section>
 {bills.length>0&&<section><h2>Les factures réglées</h2><div className="bill-grid">{bills.map(b=><BillCard key={b.id} label={b.title} amount={money(b.cents)} status="paid" statusText="Réglée"><p>{names[b.member]} · {new Date(b.date+'T12:00:00Z').toLocaleDateString('fr-FR',{timeZone:'UTC'})}</p></BillCard>)}</div></section>}
 <div className="budget-charts" id="budget-charts" role="region" aria-label="Nos dépenses en images"><BarChart title="Nos six derniers mois" subtitle="Les dépenses avancées par chacun" data={months} series={names.map((name,i)=>({name,who:i===0?'a':'b',color:i===0?'data-1':'data-2'}))} unit="€"/><CalendarHeatmap title="Le rythme du mois" subtitle="Plus le cercle est marqué, plus on a dépensé" month={start.toLocaleDateString('fr-FR',{month:'long',year:'numeric',timeZone:'UTC'})} startDow={(start.getUTCDay()+6)%7} days={days}/><div className="budget-daily-chart"><LineChart title="Le fil de nos dépenses" subtitle="Le cumul de ce mois, jour après jour" labels={days.map(d=>String(d.day))} series={[{name:'Dépenses cumulées',values:cumul,color:'data-1'}]} goal={budget>0?budget/100:undefined} unit="€" xLabel="Jour" fromZero/></div>{limited.length>0&&<DivergingBars title="La marge par catégorie" subtitle="Plafond choisi moins dépenses du mois" data={limited.map(c=>({label:c.label,value:c.budget!-c.value}))} posLabel="Encore disponible" negLabel="Budget dépassé" unit="€"/>}{budget>0&&<GaugeTile label="Budget encore disponible" emoji="🐷" value={Math.max(0,budget-total)} max={budget} display={money(Math.max(0,budget-total))} caption={total>budget?`Dépassement : ${money(total-budget)}`:'Sur '+money(budget)+' pour le mois'} tone="rose"/>}</div>
 {editing&&<LifeDialog title="Une enveloppe par catégorie" onClose={()=>setEditing(false)} busy={busy}><form className="form" onSubmit={async e=>{e.preventDefault();setLocalError('');try{const f=new FormData(e.currentTarget),values:Record<string,number>={};for(const name of categories){const value=String(f.get(name)||'').trim();if(value)values[name]=centsFromInput(value);}if(await onBudgets(values))setEditing(false);}catch(e){setLocalError(e instanceof Error?e.message:'Montant invalide.');}}}><p>Ces plafonds se répètent chaque mois. Laissez vide pour ne pas fixer de limite. Ils ne changent pas le budget global.</p>{categories.map(name=><label key={name}>{name} (€ / mois)<input inputMode="decimal" name={name} defaultValue={categoryBudgets[name]?String(categoryBudgets[name]/100):''} placeholder="Sans plafond"/></label>)}{(error||localError)&&<p className="form-error" role="alert">{localError||error}</p>}<button className="primary" disabled={busy}>Enregistrer</button></form></LifeDialog>}</div>;
}
