import {useEffect,useState} from 'react';
import {parisTimestamp,countdown} from '../lib/countdown';
import {MomentBuddy,momentKind,momentLabels} from './moment-buddy';
import {Pause,Play} from './icons';
import type {Idea} from '../lib/life';
import {PlantMascot} from './house-plants';
import {plantCare,plantMood,parisDate,type Plant} from '../lib/life';
import {occurrences,addDays,appointmentCategories} from '../lib/calendar';
import type {Appointment} from '../lib/domain';
export default function HomeMoments({plants,appointments,ideas=[],onGarden,onCalendar}:{ideas?:Idea[];plants:Plant[];appointments:Appointment[];onGarden:()=>void;onCalendar:()=>void}){const [paused,setPaused]=useState(false);const date=parisDate();const events=occurrences(appointments.filter(a=>a.status==='scheduled'&&!a.source&&(a.sourceIdeaId||['travel','holiday','birthday','party','family'].includes(a.category))),date,addDays(date,366)).filter(a=>a.date>=date).slice(0,4);return <div className="home-moments">{events.length>0&&<section className={`countdown-section ${paused?'buddies-paused':''}`}><header className="countdown-heading"><h2>Nos prochains grands moments</h2><button className="icon-button buddy-motion-toggle" aria-label={paused?'Animer les personnages':'Mettre les personnages en pause'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={17}/>:<Pause size={17}/>}</button></header><div className="countdown-grid">{events.map(a=>{const kind=momentKind(a,ideas);const days=Math.round((Date.parse(a.date+'T12:00:00Z')-Date.parse(date+'T12:00:00Z'))/86400000);return <button key={a.id+a.date} onClick={onCalendar} className="countdown-card"><MomentBuddy kind={kind}/><span className="countdown-kicker">Le compte à rebours est lancé</span><strong>{days===0?'C’est aujourd’hui !':`Dans ${days} jour${days>1?'s':''}`}</strong><h3>{a.title}</h3><LiveCountdown date={a.date} time={a.time}/><small>{a.sourceIdeaId?momentLabels[kind]:appointmentCategories[a.category]} · {new Date(a.date+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long'})}{a.visibility==='private'?' · Pour moi seulement':''}</small></button>;})}</div></section>}{plants.length>0&&<section className="home-garden"><header><h2>Des nouvelles de nos pousses</h2><button className="text-link" onClick={onGarden}>Le jardin</button></header><div className="plant-parade" role="region" aria-label="Nos plantes, liste défilante" tabIndex={0}>{plants.map(p=>{const due=plantCare(p,date).filter(c=>c.overdue>=0).length;return <button key={p.id} onClick={onGarden}><PlantMascot mood={plantMood(p,date)} name={p.name} species={p.species}/><strong>{p.name}</strong><small>{due?`${due} soin${due>1?'s':''} à faire`:'Soins à jour'}</small></button>;})}</div></section>}</div>;}

function LiveCountdown({date,time}:{date:string;time?:string}){const[now,setNow]=useState(Date.now);useEffect(()=>{const tick=()=>{if(document.visibilityState==='visible')setNow(Date.now());};const timer=setInterval(tick,1000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[]);const target=parisTimestamp(date,time);const values=countdown(target,now);return <span className="live-countdown" aria-label={'Compte à rebours jusqu’au '+date+(time?' à '+time:' à minuit')+', heure de Paris'}>{values.map((value,i)=><span key={i} aria-hidden="true"><b>{String(value).padStart(2,'0')}</b><small>{['jours','heures','min','sec'][i]}</small></span>)}</span>;}
