import {useState,type FormEvent} from 'react';
import {CalendarDays,Check,Heart,MapPin,Plus,Send,Sparkles,Trash2,X} from 'lucide-react';
import type {Idea} from '../lib/life';
import LifeDialog from './life-dialog';
type Save=(a:string,p:unknown,m?:string)=>Promise<boolean>;
const categories={restaurant:{label:'Restaurant',icon:'🍽️'},outing:{label:'Sortie',icon:'🎟️'},home:{label:'À la maison',icon:'🛋️'},trip:{label:'Escapade',icon:'🧳'},surprise:{label:'Surprise',icon:'🎁'}};
function IdeaDetails({idea,names}:{idea:Idea;names:string[]}){return <><span className="invitation-emoji" aria-hidden="true">{categories[idea.category].icon}</span><span className="invitation-kicker">{names[idea.owner]} vous invite</span><h2>{idea.title}</h2>{idea.description&&<p className="invitation-description">{idea.description}</p>}<div className="invitation-meta">{idea.date&&<span><CalendarDays size={16}/>{new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(idea.date+'T12:00:00'))}{idea.time&&` à ${idea.time}`}</span>}{idea.location&&<span><MapPin size={16}/>{idea.location}</span>}</div><p className="invitation-votes"><Check size={15}/>{names[idea.owner]} est déjà partant·e.</p></>;}
export function InvitationArrival({enabled=true,ideas,active,names,busy,error,save,onOpen}:{error:string;enabled?:boolean;ideas:Idea[];active:number;names:string[];busy:boolean;save:Save;onOpen:()=>void}){
 const[dismissed,setDismissed]=useState<string[]>([]),[note,setNote]=useState('');const idea=ideas.filter(i=>i.owner!==active&&i.status==='pending').find(i=>!dismissed.includes(i.id+':'+i.version));
 if(!idea||!enabled)return null;const close=()=>{setDismissed(d=>[...d,idea.id+':'+idea.version]);setNote('');};
 async function respond(status:'accepted'|'declined'){if(await save('idea-response',{id:idea!.id,version:idea!.version,status,responseNote:note},status==='accepted'?'C’est un oui à deux !':'Votre réponse a été transmise.'))close();}
 return <LifeDialog className="invitation-arrival" title="Une invitation pour vous" busy={busy} onClose={close}><div className="invitation-paper"><div className="invitation-confetti" aria-hidden="true">✦ <span>✧</span> ✦ <span>✧</span></div><IdeaDetails idea={idea} names={names}/><label className="invitation-note">Un petit mot en réponse <span>(facultatif)</span><textarea rows={2} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="Avec plaisir ! On peut plutôt à 19 h ?"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="invitation-response"><button className="primary" disabled={busy} onClick={()=>respond('accepted')}><Heart size={17}/>Ça me tente</button><button className="secondary" disabled={busy} onClick={()=>respond('declined')}><X size={17}/>Pas cette fois</button></div><button className="text-link" onClick={close} disabled={busy}>Je répondrai plus tard</button><button className="text-link" onClick={()=>{close();onOpen();}}>Voir toutes nos idées</button></div></LifeDialog>;
}
export default function HouseIdeas({ideas,active,names,busy,error,save}:{ideas:Idea[];active:number;names:string[];busy:boolean;error:string;save:Save}){
 const[editing,setEditing]=useState<Idea|null|undefined>(undefined),[selected,setSelected]=useState<Idea|null>(null),[response,setResponse]=useState(''),[filter,setFilter]=useState('all');
 const current=selected?ideas.find(i=>i.id===selected.id):undefined;
 const pending=ideas.filter(i=>i.status==='pending');const visible=ideas.filter(i=>filter==='all'||i.status===filter).slice().reverse();
 async function respond(status:'accepted'|'declined'){if(!current)return;if(await save('idea-response',{id:current.id,version:current.version,status,responseNote:response},status==='accepted'?'À vous les moments à deux !':'Votre réponse est enregistrée.')){setSelected(null);setResponse('');}}
 return <div className="ideas-space"><div className="life-intro ideas-intro"><span className="life-intro-icon">💌</span><div><h2>Et si on se faisait un petit moment ?</h2><p>Une idée, une invitation. Chacun donne son oui.</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus size={18}/>Proposer une activité</button></div><div className="life-filters" aria-label="Filtrer les invitations">{[['all','Toutes'],['pending',`En attente (${pending.length})`],['accepted','Acceptées'],['declined','Pas cette fois']].map(([id,label])=><button key={id} className={filter===id?'selected':''} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>{visible.length?<div className="ideas-grid">{visible.map(i=><button key={i.id} className={`idea-card idea-${i.category}`} onClick={()=>{setSelected(i);setResponse('');}}><div className="idea-card-top"><span className="idea-emoji">{categories[i.category].icon}</span><span className={`idea-status ${i.status}`}>{i.status==='accepted'?'Deux oui !':i.status==='declined'?'Pas cette fois':i.owner===active?'Réponse attendue':'À vous de répondre'}</span></div><small>{categories[i.category].label} · Proposé par {names[i.owner]}</small><h2>{i.title}</h2><p>{i.description||'Un moment à partager, juste vous deux.'}</p><footer>{i.date?<span><CalendarDays size={15}/>{new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date(i.date+'T12:00:00'))}{i.time&&` · ${i.time}`}</span>:<span>Date à décider ensemble</span>}<span className="idea-votes"><Check size={14}/>{i.status==='accepted'?'2 / 2':'1 / 2'}</span></footer></button>)}</div>:<div className="panel empty"><span className="empty-icon"><Sparkles size={29}/></span><h3>{filter==='all'?'Votre prochaine histoire commence par une idée':'Aucune invitation ici pour le moment'}</h3><p>Un resto, une balade, un film sous le plaid… Les petits moments comptent aussi.</p>{filter==='all'&&<button className="text-link" onClick={()=>setEditing(null)}>Envoyer la première invitation</button>}</div>}
 {editing!==undefined&&<LifeDialog title={editing?'Modifier mon invitation':'Une idée pour nous deux'} onClose={()=>setEditing(undefined)} busy={busy}><IdeaForm key={editing?.id||'new'} idea={editing} busy={busy} error={error} onSave={async p=>{if(await save('idea',p,'Invitation transmise à votre moitié.'))setEditing(undefined);}}/></LifeDialog>}
 {current&&<LifeDialog title="Notre invitation" onClose={()=>setSelected(null)} busy={busy}><div className="invitation-paper"><IdeaDetails idea={current} names={names}/><p className={`idea-status ${current.status}`}>{current.status==='accepted'?'Vous avez dit oui tous les deux 💛':current.status==='declined'?'Pas cette fois. Une autre idée nous attend !':current.owner===active?`En attente de la réponse de ${names[1-active]}.`:'Cette invitation attend votre réponse.'}</p>{current.responseNote&&<blockquote className="idea-response-note"><strong>{names[1-current.owner]}</strong><p>{current.responseNote}</p></blockquote>}{current.owner!==active&&current.status==='pending'&&<><label className="invitation-note">Votre petit mot <span>(facultatif)</span><textarea rows={2} maxLength={500} value={response} onChange={e=>setResponse(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="invitation-response"><button className="primary" disabled={busy} onClick={()=>respond('accepted')}><Check size={18}/>Ça me tente</button><button className="secondary" disabled={busy} onClick={()=>respond('declined')}>Pas cette fois</button></div></>}{current.owner===active&&<div className="idea-owner-actions"><button className="secondary" onClick={()=>{setSelected(null);setEditing(current);}}>Modifier et reproposer</button><button className="text-link" disabled={busy} onClick={async()=>{if(window.confirm('Supprimer cette invitation pour vous deux ?')&&await save('delete-idea',{id:current.id,version:current.version},'Invitation supprimée.'))setSelected(null);}}><Trash2 size={16}/>Supprimer</button></div>}<p className="helper-copy">Une invitation acceptée ne crée pas automatiquement de rendez-vous dans l’agenda.</p></div></LifeDialog>}
 </div>;
}
function IdeaForm({idea,busy,error,onSave}:{idea:Idea|null;busy:boolean;error:string;onSave:(p:unknown)=>Promise<void>}){
 const[id]=useState(()=>idea?.id||crypto.randomUUID());const[localError,setLocalError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setLocalError('');if(f.get('time')&&!f.get('date')){setLocalError('Choisissez une date avec cette heure, ou laissez les deux champs vides.');return;}await onSave({id,version:idea?.version||0,title:String(f.get('title')).trim(),category:String(f.get('category')),description:String(f.get('description')||''),date:String(f.get('date')||''),time:String(f.get('time')||''),location:String(f.get('location')||'')});}
 return <form className="form" onSubmit={submit}><label>Qu’est-ce qu’on pourrait faire ?<input autoFocus name="title" required maxLength={100} defaultValue={idea?.title||''} placeholder="Un resto italien vendredi soir ?"/></label><label>Le genre de moment<select name="category" defaultValue={idea?.category||'restaurant'}>{Object.entries(categories).map(([id,c])=><option key={id} value={id}>{c.icon} {c.label}</option>)}</select></label><label>Racontez votre idée<textarea name="description" rows={3} maxLength={1000} defaultValue={idea?.description||''} placeholder="L’endroit, l’ambiance, pourquoi ça vous ferait plaisir…"/></label><div className="form-grid"><label>Date (facultatif)<input type="date" name="date" defaultValue={idea?.date||''}/></label><label>Heure (facultatif)<input type="time" name="time" defaultValue={idea?.time||''}/></label></div><label>Où ça ?<input name="location" maxLength={150} defaultValue={idea?.location||''} placeholder="Un lieu, une adresse ou « surprise »"/></label><p className="helper-copy">En transmettant, vous donnez votre oui. Votre moitié répondra depuis son compte.{idea&&' Une modification relance une nouvelle demande d’accord.'}</p>{(error||localError)&&<p className="form-error" role="alert">{localError||error}</p>}<button className="primary wide" disabled={busy} type="submit"><Send size={17}/>{busy?'Transmission…':'Transmettre mon invitation'}</button></form>;
}
