import {useEffect,useRef,useState} from 'react';
import {StickerStack,Sticker,Avatar} from '../design-system/runtime';
import {apiFetch} from '../lib/api-client';
import type {Meals} from '../lib/domain';
type Task='cuisine'|'vaisselle'|'courses'|'rangement';
const labels={cuisine:['Cuisine','🍳'],vaisselle:['Vaisselle','🧽'],courses:['Courses','🛒'],rangement:['Rangement','🧺']};
export default function HouseWheel({names,date,recipeId,recipeTitle,initial}:{names:string[];date:string;recipeId?:string;recipeTitle?:string;initial?:Meals['draws']}){
 const[draws,setDraws]=useState(initial||{}),[rotation,setRotation]=useState(0),[spinning,setSpinning]=useState(false),[error,setError]=useState(''),[last,setLast]=useState<Task|null>(null);const alive=useRef(true),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const scope=recipeId||'home',results=draws[scope]||{},tasks:Task[]=recipeId?['cuisine','vaisselle','courses']:['vaisselle','courses','rangement'];const task=tasks.find(t=>results[t]===undefined);const people=[...names,'Nous deux'];
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;clearTimeout(timer.current);};},[]);
 useEffect(()=>{if(initial&&!spinning)setDraws(initial);},[initial]);
 async function spin(){if(spinning||!task)return;setSpinning(true);setError('');try{const r=await apiFetch('/api/meals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'draw',date,task,recipeId}),signal:AbortSignal.timeout(15000)}),data=await r.json();if(!r.ok)throw Error(data.error||'La roue attend la connexion.');const win=data.draws?.[scope]?.[task];if(![0,1,2].includes(win))throw Error('Résultat indisponible. Réessayez.');if(!alive.current)return;setRotation(old=>old+1080+(360-(win*40+20))-(old%360));timer.current=setTimeout(()=>{if(alive.current){setDraws(data.draws);setLast(task);setSpinning(false);}},matchMedia('(prefers-reduced-motion: reduce)').matches?0:1250);}catch(e){if(alive.current){setError(e instanceof Error?e.message:'Connexion perdue.');setSpinning(false);}}}
 return <section className="nd-game house-wheel" aria-label="Qui fait quoi ?"><div className="nd-game-head"><StickerStack size="sm" words={[{text:'qui fait',tone:'citron'},{text:'quoi ?',tone:'lilas'}]}/></div><h3>{recipeTitle||'Les petites missions du jour'}</h3><p>{recipeId?'Pour ce plat, le cuisinier du match est conservé.':'Un tirage partagé pour aujourd’hui.'} Une chance sur trois chacun, une chance sur trois ensemble.</p><div className="nd-wheel-wrap"><span className="nd-wheel-pointer" aria-hidden="true"/><svg className="nd-wheel" viewBox="-100 -100 200 200" aria-hidden="true" style={{transform:`rotate(${rotation}deg)`}}>{Array.from({length:9},(_,i)=>{const w=i%3,a0=(i*40-90)*Math.PI/180,a1=((i+1)*40-90)*Math.PI/180,am=((i+.5)*40-90)*Math.PI/180;return <g key={i}><path className={['seg-a','seg-b','seg-nous'][w]} d={`M0 0L${96*Math.cos(a0)} ${96*Math.sin(a0)}A96 96 0 0 1 ${96*Math.cos(a1)} ${96*Math.sin(a1)}Z`}/><text x={64*Math.cos(am)} y={64*Math.sin(am)+6} textAnchor="middle" transform={`rotate(${(i+.5)*40} ${64*Math.cos(am)} ${64*Math.sin(am)})`}>{w===2?'♥':names[w].charAt(0)}</text></g>;})}<circle r="30" className="hub"/></svg><button className="nd-wheel-btn" type="button" onClick={spin} disabled={spinning||!task}>{spinning?'…':task?'Tourner':'Fini !'}</button></div><div className="nd-game-status" role="status">{spinning?'La roue tourne…':last?<Sticker tone="lilas" rotate={-4}>{people[results[last]]} : {labels[last][0].toLowerCase()} !</Sticker>:task?`On tire au sort : ${labels[task][0].toLowerCase()}.`:'Les rôles sont distribués !'}</div><ul className="nd-game-tasks">{tasks.map(t=><li key={t} className={t===task?'current':''}><span className="nd-game-task"><span aria-hidden="true">{labels[t][1]} </span>{labels[t][0]}</span>{results[t]!==undefined?<span className="nd-game-who"><Avatar name={people[results[t]]} partner={(['a','b','nous'] as const)[results[t]]} size={26}/>{people[results[t]]}</span>:<span className="nd-game-wait">À tirer</span>}</li>)}</ul><p className="helper-copy">Le résultat est enregistré pour vous deux. Fermer la roue ne relance pas le tirage.</p>{error&&<p className="form-error" role="alert">{error}</p>}</section>;
}
