'use client';
import {apiFetch,APP_BASE} from '../lib/api-client';
import {createPortal} from 'react-dom';
import {useState,useEffect,useCallback,useRef,type FormEvent,type ReactNode} from 'react';
import {Home,Wallet,ShoppingBasket,CheckCheck,Settings,Plus,ArrowUpRight,ArrowRight,ArrowLeftRight,ChevronLeft,ChevronRight,X,Check,Trash2,Pencil,RefreshCw,CloudCheck,CloudOff,Heart,Download,Smartphone,CalendarDays,Search,Receipt,Leaf,Lightbulb,Car,Coffee,Shapes,LockKeyhole,LogOut,LoaderCircle,ChevronDown,Flag,Phone,Bell} from 'lucide-react';
import {balance,centsFromInput,money,today,categories,type Data,type Entry,type Item,type Household,type Appointment} from '../lib/domain';
import HouseCalls from './house-calls';
import HouseNotifications from './house-notifications';
import {deviceId} from '../lib/device';
import HouseCalendar,{CalendarSummary,AppointmentForm,type OpenAppointment} from './house-calendar';
type Tab='calls'|'notifications'|'home'|'expenses'|'shopping'|'tasks'|'calendar'|'settings';
type Modal={kind:'expense'|'settlement'|'shopping'|'task'|'delete'|'install'|'appointment';entry?:Entry;item?:Item;appointment?:Appointment;initialDate?:string;initialStatus?:'to_book'|'scheduled'};
const nav=[{id:'home',label:'Chez nous',icon:Home},{id:'expenses',label:'Dépenses',icon:Wallet},{id:'shopping',label:'Courses',icon:ShoppingBasket},{id:'calendar',label:'Calendrier',icon:CalendarDays},{id:'tasks',label:'À faire',icon:CheckCheck},{id:'calls',label:'Appels',icon:Phone},{id:'notifications',label:'Nouveautés',icon:Bell},{id:'settings',label:'Notre espace',icon:Settings}] as const;
const catIcons=[ShoppingBasket,Home,Lightbulb,Coffee,Car,Shapes];
const dateLabel=(date:string)=>new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date(date+'T12:00:00'));
const monthLabel=(month:string)=>new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(month+'-15T12:00:00'));
function Avatar({name,second=false,small=false}:{name:string;second?:boolean;small?:boolean}){return <span className={`avatar ${second?'peach':''} ${small?'small':''}`}>{name.slice(0,1).toUpperCase()}</span>;}
function Empty({icon:Icon,title,children,action}:{icon:typeof Home;title:string;children:ReactNode;action?:ReactNode}){return <div className="empty"><span className="empty-icon"><Icon size={27} strokeWidth={1.5}/></span><h3>{title}</h3><p>{children}</p>{action}</div>;}
function Dialog({title,close,children,busy}:{title:string;close:()=>void;children:ReactNode;busy:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);
 return <dialog aria-labelledby="dialog-title" ref={ref} onCancel={e=>{e.preventDefault();if(!busy)close();}} onClick={e=>{if(e.target===ref.current&&!busy)close();}}><div className="dialog-inner"><div className="dialog-head"><div><span className="eyebrow">NOTRE QUOTIDIEN</span><h2 id="dialog-title">{title}</h2></div><button type="button" className="icon-button" onClick={close} disabled={busy} aria-label="Fermer"><X/></button></div>{children}</div></dialog>;
}
export default function HouseApp(){
 const[data,setData]=useState<Data|null>(null);const[tab,setTab]=useState<Tab>('home');const[modal,setModal]=useState<Modal|null>(null);
 const[active,setActive]=useState(0);const[month,setMonth]=useState(today().slice(0,7));const[search,setSearch]=useState('');const[category,setCategory]=useState('Toutes');const[taskFilter,setTaskFilter]=useState('all');
 const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[online,setOnline]=useState(true);const[error,setError]=useState('');const[formError,setFormError]=useState('');const[notice,setNotice]=useState('');const[synced,setSynced]=useState(false);const[needsAuth,setNeedsAuth]=useState(false);
 const sequence=useRef(0);const mutating=useRef(false);const submitting=useRef(false);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const toast=(message:string)=>{setNotice(message);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setNotice(''),4200);};
 const refresh=useCallback(async(quiet=false)=>{
  if(mutating.current)return false;const requestNumber=++sequence.current;
  try{const response=await apiFetch('/api/household',{cache:'no-store'});if(response.status===401){setNeedsAuth(true);throw new Error('Votre session a expiré. Reconnectez-vous.');}
   if(!response.ok)throw new Error('La synchronisation est interrompue. Réessayez dans un instant.');
   const result=await response.json() as Data;if(requestNumber===sequence.current){setData(result);setActive(result.member??0);setSynced(true);setError('');setNeedsAuth(false);}return true;
  }catch(e){if(requestNumber===sequence.current){setSynced(false);if(!quiet)setError(e instanceof Error?e.message:'Connexion indisponible.');}return false;}
  finally{if(requestNumber===sequence.current)setLoading(false);}
 },[]);
 useEffect(()=>{
  const view=new URLSearchParams(location.search).get('view');if(view&&nav.some(n=>n.id===view))setTab(view as Tab);
  setOnline(navigator.onLine);refresh();
  const wake=()=>{setOnline(navigator.onLine);if(document.visibilityState==='visible')refresh(true);};
  const offline=()=>{setOnline(false);setSynced(false);};
  const timer=setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine)refresh(true);},10000);
  addEventListener('focus',wake);addEventListener('online',wake);addEventListener('offline',offline);document.addEventListener('visibilitychange',wake);
  return()=>{clearInterval(timer);removeEventListener('focus',wake);removeEventListener('online',wake);removeEventListener('offline',offline);document.removeEventListener('visibilitychange',wake);};
 },[refresh]);
 const canEdit=(record?:{owner?:number|null})=>!record||record.owner===active;
 const record=modal?.entry||modal?.item||modal?.appointment;const readOnly=!!record&&!canEdit(record);
 const open=(m:Modal)=>{setFormError('');setModal(m);};
 async function save(action:string,payload:unknown,message='Enregistré dans votre maison.'){
  if(submitting.current)return false;
  if(!navigator.onLine){setFormError('Vous êtes hors ligne. Reconnectez-vous pour enregistrer.');toast('Connexion nécessaire pour enregistrer.');return false;}
  submitting.current=true;mutating.current=true;++sequence.current;setBusy(true);setFormError('');
  try{const response=await apiFetch('/api/household',{method:'POST',headers:{'Content-Type':'application/json','x-adeux-member':String(active),'x-adeux-device':deviceId()},body:JSON.stringify({action,payload})});
   if(response.status===401)setNeedsAuth(true);
   if(!response.ok){const result=await response.json().catch(()=>({})) as {error?:string};if(response.status===409){mutating.current=false;await refresh();}throw new Error(result.error||'Enregistrement impossible. Réessayez.');}
   mutating.current=false;const fresh=await refresh();setModal(null);toast(fresh?message:'Enregistré. Actualisez pour charger la dernière version.');return true;
  }catch(e){const message=e instanceof Error?e.message:'Enregistrement impossible.';setFormError(message);toast(message);return false;}
  finally{mutating.current=false;submitting.current=false;setBusy(false);}
 }
 const home=data?.household;const names=[home?.first||'Vous',home?.second||'Votre moitié'];const all=data?.entries||[];const lists=data?.items||[];
 const appointments=data?.appointments||[];
 const openAppointment=(options:OpenAppointment)=>open({kind:'appointment',...options});
 const credit=balance(all);const owes=credit>0?1:0;const receives=1-owes;
 const monthly=all.filter(e=>e.kind==='expense'&&e.date.startsWith(month));const total=monthly.reduce((s,e)=>s+e.cents,0);
 const paid=[0,1].map(n=>monthly.filter(e=>e.member===n).reduce((s,e)=>s+e.cents,0));
 const shopping=lists.filter(i=>i.kind==='shopping');const tasks=lists.filter(i=>i.kind==='task');const todo=tasks.filter(i=>!i.done);const toBuy=shopping.filter(i=>!i.done);
 const visible=all.filter(e=>e.date.startsWith(month)&&(category==='Toutes'||e.category===category&&e.kind==='expense')&&`${e.title} ${e.note} ${names[e.member]}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const moveMonth=(direction:number)=>{const d=new Date(month+'-15T12:00:00');d.setMonth(d.getMonth()+direction);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);};
 const monthPicker=<div className="month-picker"><button className="icon-button" aria-label="Mois précédent" onClick={()=>moveMonth(-1)}><ChevronLeft size={18}/></button><label className="month-label">{monthLabel(month)}<input aria-label="Choisir le mois" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label><button className="icon-button" aria-label="Mois suivant" onClick={()=>moveMonth(1)}><ChevronRight size={18}/></button></div>;
 const entryRow=(e:Entry)=>{const Icon=e.kind==='settlement'?ArrowLeftRight:catIcons[categories.indexOf(e.category)]||Receipt;return <button className="entry-row" key={e.id} onClick={()=>open({kind:e.kind,entry:e})}><span className={`category-icon cat-${categories.indexOf(e.category)}`}><Icon size={21} strokeWidth={1.7}/></span><span className="row-description"><strong>{e.title}</strong><span>{e.kind==='settlement'?`${names[e.member]} → ${names[1-e.member]}`:`Payé par ${names[e.member]}`}<span className="dot">·</span>{dateLabel(e.date)}</span></span><span className="row-money"><strong>{money(e.cents)}</strong><small>{e.kind==='settlement'?'Remboursement':'50 / 50'}</small></span><ChevronRight className="row-chevron" size={16}/></button>;};
 const toggleItem=(item:Item)=>save('item',{...item,done:!item.done},item.done?'Remis dans la liste.':item.kind==='shopping'?'C’est dans le panier !':'Une chose de faite !');
 const itemRow=(item:Item)=> <div key={item.id} className={`item-row ${item.done?'done':''}`}><button className="checkbox" disabled={busy||!online||!canEdit(item)} onClick={()=>toggleItem(item)} aria-label={`${item.done?'Rouvrir':'Terminer'} : ${item.title}`} aria-pressed={item.done}>{item.done&&<Check size={17}/>}</button><button className="item-detail" onClick={()=>open({kind:item.kind,item})}><strong>{item.title}</strong><span>{item.quantity&&<span>{item.quantity}</span>}{item.due&&<span className={!item.done&&item.due<today()?'overdue':''}><CalendarDays size={12}/>{dateLabel(item.due)}</span>}{item.priority===1&&!item.done&&<span className="priority"><Flag size={11}/> Priorité</span>}</span></button>{item.assignee>=0&&<span title={names[item.assignee]}><Avatar name={names[item.assignee]} second={item.assignee===1} small/></span>}<button className="icon-button subtle" aria-label={`${canEdit(item)?'Modifier':'Voir'} ${item.title}`} onClick={()=>open({kind:item.kind,item})}>{canEdit(item)?<Pencil size={15}/>:<LockKeyhole size={15}/>}</button></div>;
 const exportCsv=()=>{const safe=(v:unknown)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const rows=[['Date','Type','Intitulé','Montant EUR','Personne','Catégorie','Note'],...all.map(e=>[e.date,e.kind==='expense'?'Dépense':'Remboursement',e.title,(e.cents/100).toFixed(2).replace('.',','),names[e.member],e.category,e.note])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`a-deux-depenses-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Votre historique a été exporté.');};
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href={APP_BASE} aria-label="À deux, accueil"><span className="brand-mark"><Heart size={22} strokeWidth={1.8}/></span><span>à deux<span className="brand-dot">.</span></span></a><div className="sidebar-caption">UN PEU DE VOUS, UN PEU DE NOUS.</div><nav aria-label="Navigation principale">{nav.map(({id,label,icon:Icon})=><button key={id} aria-label={label} aria-current={tab===id?'page':undefined} className={`nav-item ${tab===id?'active':''}`} onClick={()=>setTab(id)}><Icon size={20}/><span>{label}</span>{id==='shopping'&&toBuy.length>0&&<span className="nav-count">{toBuy.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="little-note"><Leaf size={22}/><p>Moins de comptes à faire.<br/><strong>Plus de moments à deux.</strong></p></div><span className="private-label"><LockKeyhole size={13}/> Votre maison, en privé.</span></div></aside>
  <div className="workspace"><header className="topbar"><div className="home-label"><span className="home-icon"><Home size={16}/></span><span>{home?.name||'Notre maison'}</span><span className="shared-tag">Espace partagé</span></div><div className="topbar-right"><button className={`sync-status ${!synced?'unsynced':''}`} onClick={()=>refresh()} aria-label="Actualiser les données">{synced?<CloudCheck size={17}/>:<CloudOff size={17}/>}<span>{!online?'Hors ligne':synced?'À jour':'Actualiser'}</span></button>{home&&<label className="profile-picker"><Avatar name={names[active]} second={active===1}/><span>{names[active]}</span><LockKeyhole size={14}/></label>}</div></header>
  <main>
   {(!online||error)&&<div className="banner" role="alert"><CloudOff size={18}/><span>{!online?'Hors ligne · reconnectez-vous pour enregistrer et synchroniser.':error}</span>{needsAuth?<a href={APP_BASE} target="_top">Se reconnecter</a>:<button onClick={()=>refresh()}>Réessayer</button>}</div>}
   {loading&&!data?<div className="loading"><LoaderCircle className="spin"/><h2>On ouvre votre maison…</h2></div>:!data?<Empty icon={CloudOff} title="Votre maison attend votre connexion">{needsAuth?<a className="primary" href={APP_BASE} target="_top">Se connecter</a>:<button className="primary" onClick={()=>refresh()}>Réessayer</button>}</Empty>:!home?<div className="onboarding"><div className="welcome-art"><div className="art-house"><Heart size={45} strokeWidth={1.2}/></div><span className="floating-chip">50 / 50</span><span className="floating-check"><Check size={24}/></span></div><span className="eyebrow">BIENVENUE CHEZ VOUS</span><h1>Le quotidien est plus<br/>doux <em>à deux.</em></h1><p>Les comptes au clair, les courses à portée de main<br className="desktop-break"/> et les petites choses à faire, ensemble.</p><SettingsForm key="onboard" busy={busy} error={formError} onSave={h=>save('household',h,'Bienvenue dans votre maison !')} initial={null}/><p className="privacy-note"><LockKeyhole size={14}/> Vos données restent dans votre espace privé.<br/>Utilisez le mot de passe de votre maison sur vos différents appareils.</p></div>:<>
   <div className="communication-shortcuts"><button className={tab==='calls'?'selected':''} onClick={()=>setTab('calls')}><Phone size={16}/>Appels</button><button className={tab==='notifications'?'selected':''} onClick={()=>setTab('notifications')}><Bell size={16}/>Nouveautés & notifications</button></div><div className="page-heading"><div><span className="eyebrow">{tab==='home'?'LE QUOTIDIEN, ENSEMBLE':tab==='expenses'?'LES BONS COMPTES':tab==='shopping'?'RIEN À OUBLIER':tab==='tasks'?'ON SE PARTAGE AUSSI ÇA':tab==='calendar'?'LES DATES QUI COMPTENT':'VOTRE PETIT CHEZ-VOUS'}</span><h1>{tab==='home'?<>Bonjour, {names[active]}<span className="wave"> ☀</span></>:tab==='expenses'?'Nos dépenses':tab==='shopping'?'La liste de courses':tab==='tasks'?'Les choses à faire':tab==='calendar'?'Notre calendrier':tab==='calls'?'On se parle ?':tab==='notifications'?'Les nouvelles de chez nous':'Notre espace'}</h1><p>{tab==='home'?'Un coup d’œil, et tout est plus clair.':tab==='expenses'?'Chacun sa moitié. Tout simplement.':tab==='shopping'?'Un seul panier dans toutes vos poches.':tab==='tasks'?'Les petites choses font les grandes équipes.':tab==='calendar'?'Nos rendez-vous, nos dates et ce qu’il reste à organiser.':tab==='calls'?'Une voix familière, à portée de main.':tab==='notifications'?'Restez au courant, sans en faire trop.':'Une maison qui vous ressemble.'}</p></div>{tab==='home'||tab==='expenses'?<button className="primary" onClick={()=>open({kind:'expense'})}><Plus size={19}/>Ajouter une dépense</button>:tab==='shopping'||tab==='tasks'?<button className="primary" onClick={()=>open({kind:tab==='shopping'?'shopping':'task'})}><Plus size={19}/>{tab==='shopping'?'Ajouter un article':'Ajouter une tâche'}</button>:tab==='calendar'?<button className="primary" onClick={()=>openAppointment({initialStatus:'scheduled',initialDate:today()})}><Plus size={19}/>Ajouter un rendez-vous</button>:null}</div>
   {(tab==='home'||tab==='expenses')&&<>
    <section className="finance-grid" aria-label="Résumé des comptes"><div className="balance-card"><div className="balance-heading"><span className="label-light">L’ÉQUILIBRE ENTRE NOUS</span><span className="fifty">50 / 50</span></div><div className="balance-amount">{money(Math.abs(credit))}</div><p>{credit===0?'Tout est équilibré. Vous êtes à jour.':<><strong>{names[owes]}</strong> doit à <strong>{names[receives]}</strong></>}</p><div className="balance-bottom"><div className="couple-avatars"><Avatar name={names[0]}/><Avatar name={names[1]} second/><span>Depuis le début</span></div>{credit!==0?<button onClick={()=>open({kind:'settlement'})}>Noter un remboursement<ArrowUpRight size={17}/></button>:<span className="balanced"><Check size={15}/> Bien ensemble</span>}</div><div className="balance-decoration" aria-hidden="true"/></div>
    <div className="month-card"><div className="card-top"><span className="eyebrow">DÉPENSES DU MOIS</span>{monthPicker}</div><div className="month-total">{money(total)}</div><p>de dépenses communes <span>· {monthly.length} dépense{monthly.length!==1?'s':''}</span></p><div className="contribution-track" role="img" aria-label={`${names[0]} a payé ${money(paid[0])}, ${names[1]} a payé ${money(paid[1])}`}><span style={{width:total?`${paid[0]/total*100}%`:'50%'}}/><span/></div><div className="contributions">{names.map((name,i)=><div key={i}><span><i className={i?'peach-dot':''}/>{name}</span><strong>{money(paid[i])}</strong></div>)}</div>{home.budget>0&&<div className={`budget-note ${total>home.budget?'overdue':''}`}>Budget : {money(home.budget)}<span>{total>home.budget?`${money(total-home.budget)} de dépassement`:`${money(home.budget-total)} disponibles`}</span></div>}</div></section>
   </>}
   {tab==='home'&&<><div className="home-grid"><section className="panel recent-panel"><div className="section-title"><h2>Derniers mouvements<span className="mini-dot"/></h2><button className="text-link" onClick={()=>setTab('expenses')}>Tout voir <ArrowUpRight size={15}/></button></div>{all.length?all.slice(0,5).map(entryRow):<Empty icon={Receipt} title="La première dépense, c’est ici">Courses, loyer, sortie… Ajoutez ce que vous avez payé. On s’occupe de la moitié.<button className="text-link empty-action" onClick={()=>open({kind:'expense'})}>Ajouter une dépense <ArrowRight size={16}/></button></Empty>}</section><div className="quick-panels"><button className="quick-card shopping-card" onClick={()=>setTab('shopping')}><div><span className="quick-icon"><ShoppingBasket size={23}/></span><ArrowUpRight size={21}/></div><h2>Dans le panier</h2><p>{toBuy.length?<><strong>{toBuy.length}</strong> article{toBuy.length>1?'s':''} à acheter</>:'La liste est prête pour vos envies.'}</p><div className="mini-chips">{toBuy.slice(0,3).map(i=><span key={i.id}>{i.title}</span>)}{!toBuy.length&&<span>On ajoute quoi ?</span>}</div></button><button className="quick-card tasks-card" onClick={()=>setTab('tasks')}><div><span className="quick-icon"><CheckCheck size={23}/></span><ArrowUpRight size={21}/></div><h2>Un peu d’organisation</h2><p>{todo.length?<><strong>{todo.length}</strong> chose{todo.length>1?'s':''} à faire ensemble</>:'Du temps pour ce qui compte.'}</p><div className="mini-chips">{todo.slice(0,2).map(i=><span key={i.id}>{i.title}</span>)}{!todo.length&&<span>Tout est tranquille</span>}</div></button></div></div><CalendarSummary appointments={appointments} names={names} onOpen={openAppointment} onCalendar={()=>setTab('calendar')}/><div className="footer-note"><Heart size={14}/> Une maison, deux personnes, une équipe.</div></>}
   {tab==='expenses'&&<section className="panel expense-panel"><div className="section-title"><h2>Notre historique</h2><div className="history-actions"><button className="text-link" onClick={()=>open({kind:'settlement'})}><ArrowLeftRight size={16}/>Remboursement</button><button className="icon-button" onClick={exportCsv} aria-label="Exporter tout l’historique en CSV"><Download size={18}/></button></div></div><div className="filters"><label className="search-field"><Search size={17}/><input placeholder="Rechercher une dépense…" aria-label="Rechercher une dépense" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filtrer par catégorie" value={category} onChange={e=>setCategory(e.target.value)}><option>Toutes</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>{visible.length?visible.map(entryRow):<Empty icon={Receipt} title={search||category!=='Toutes'?'Aucun résultat':'Un mois encore tout léger'}>{search||category!=='Toutes'?'Essayez une autre recherche ou une autre catégorie.':'Les dépenses et remboursements de ce mois apparaîtront ici.'}</Empty>}<p className="panel-footnote">Le solde en haut tient compte de tout votre historique, remboursements inclus.</p></section>}
   {(tab==='shopping'||tab==='tasks')&&(()=>{const source=tab==='shopping'?shopping:tasks;const filtered=source.filter(i=>tab!=='tasks'||taskFilter!=='mine'||i.assignee===active);const pending=filtered.filter(i=>!i.done).sort((a,b)=>b.priority-a.priority||(a.due||'9999').localeCompare(b.due||'9999'));const done=filtered.filter(i=>i.done);return <div className="lists-layout"><section className="panel list-panel"><div className="section-title"><h2>{tab==='shopping'?'À acheter':'À faire'}<span className="count-badge">{pending.length}</span></h2>{tab==='tasks'&&<div className="segmented compact"><button className={taskFilter==='all'?'selected':''} onClick={()=>setTaskFilter('all')}>Ensemble</button><button className={taskFilter==='mine'?'selected':''} onClick={()=>setTaskFilter('mine')}>Pour moi</button></div>}</div>{pending.length?pending.map(itemRow):<Empty icon={tab==='shopping'?ShoppingBasket:CheckCheck} title={source.length?'Tout est coché !':tab==='shopping'?'Qu’est-ce qu’il nous manque ?':'On commence par quoi ?'}>{source.length?'Profitez, vous avez fait le tour de la liste.':tab==='shopping'?'Ajoutez les produits au fil de vos envies. La liste est partagée sur tous vos appareils.':'Une lessive, un rendez-vous à prendre, une plante à arroser… Notez-le ici.'}</Empty>}<button className="add-row" onClick={()=>open({kind:tab==='shopping'?'shopping':'task'})}><Plus size={19}/>{tab==='shopping'?'Ajouter un article':'Ajouter une tâche'}</button>{done.length>0&&<details className="completed"><summary>{tab==='shopping'?'Dans le panier':'Terminé'} · {done.length}<ChevronDown size={16}/></summary>{done.map(itemRow)}</details>}</section><aside className="list-aside"><span className="note-icon">{tab==='shopping'?<ShoppingBasket size={30}/>:<Heart size={30}/>}</span><h2>{tab==='shopping'?'Une liste à deux.':'Chacun sa petite part.'}</h2><p>{tab==='shopping'?'Ajoutez, cochez, complétez. Votre liste se met à jour sur vos autres appareils.':'Attribuez les tâches, ajoutez une date et avancez à votre rythme.'}</p>{tab==='shopping'&&<button className="secondary" onClick={()=>open({kind:'expense'})}><Wallet size={17}/>Noter le montant des courses</button>}<span className="aside-caption">{tab==='shopping'?'Cocher un article ne crée pas de dépense.':'Les tâches terminées restent dans l’historique.'}</span></aside></div>;})()}
   <HouseCalls active={active} names={names} expanded={tab==='calls'} onOpen={()=>setTab('calls')}/>
   {tab==='notifications'&&<HouseNotifications active={active} names={names} onNavigate={t=>{if(nav.some(n=>n.id===t))setTab(t as Tab);}}/>}
   {tab==='calendar'&&<HouseCalendar appointments={appointments} names={names} onOpen={openAppointment}/>}
   {tab==='settings'&&<div className="settings-grid"><section className="panel settings-panel"><h2>Les deux de la maison</h2><SettingsForm active={active} key={home.version} initial={home} busy={busy} error={formError} onSave={h=>save('household',h,'Votre espace a été mis à jour.')}/></section><div className="settings-right"><section className="panel settings-panel"><span className="settings-icon"><Smartphone size={23}/></span><h2>Toujours à portée de main</h2><button className="text-link" onClick={()=>setTab('notifications')}><Bell size={17}/>Régler mes notifications</button><p>Ouvrez ce lien sur vos autres appareils et connectez-vous avec votre compte personnel. Vos dépenses et vos listes sont communes.</p><div className="device-profile"><span>Connecté·e en tant que <strong>{names[active]}</strong></span><LockKeyhole size={16}/></div><button className="secondary wide" onClick={()=>open({kind:'install'})}><Plus size={17}/>Ajouter à l’écran d’accueil</button><button className="text-link settings-link" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+APP_BASE);toast('Lien de la maison copié.');}catch{toast('Copiez le lien dans la barre d’adresse de votre navigateur.');}}}>Copier le lien de notre maison <ArrowUpRight size={15}/></button></section><section className="panel settings-panel"><h2>Vos données, au clair</h2><p>Les dépenses sont partagées à 50/50. Pour un centime indivisible, la part de {names[0]} est arrondie au centime supérieur.</p><button className="secondary wide" onClick={exportCsv}><Download size={17}/>Exporter toutes les dépenses</button><button className="text-link settings-link" onClick={async()=>{const r=await apiFetch("/api/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});if(r.ok)location.replace(APP_BASE);else toast("Déconnexion impossible. Réessayez.");}}><LogOut size={16}/>Déconnecter cet appareil</button></section></div></div>}
   </>}
  </main></div>
  {createPortal(<nav className="mobile-nav" aria-label="Navigation mobile">{nav.filter(n=>n.id!=='calls'&&n.id!=='notifications').map(({id,label,icon:Icon})=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={21}/><span>{id==='settings'?'Espace':id==='calendar'?'Agenda':label}</span></button>)}</nav>,document.body)}
  {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
  {modal&&<Dialog busy={busy} close={()=>{setModal(null);setFormError('');}} title={readOnly?'Détail partagé':modal.kind==='appointment'?(modal.appointment?'Notre rendez-vous':'Un nouveau rendez-vous'):modal.kind==='install'?'Votre raccourci à deux':modal.kind==='delete'?'Supprimer cet élément ?':modal.kind==='expense'?(modal.entry?'Modifier la dépense':'Une nouvelle dépense'):modal.kind==='settlement'?(modal.entry?'Modifier le remboursement':'Noter un remboursement'):modal.kind==='shopping'?(modal.item?'Modifier l’article':'À mettre dans le panier'):(modal.item?'Modifier la tâche':'Une petite chose à faire')}>
   {readOnly&&<p className="read-only-note">{record?.owner===0||record?.owner===1?`Publié par ${names[record.owner]}. Seule cette personne peut le modifier.`:'Élément antérieur aux comptes personnels : auteur inconnu, conservé en lecture seule.'}</p>}<fieldset disabled={readOnly} className={readOnly?'record-fields read-only':'record-fields'}>
   {(modal.kind==='expense'||modal.kind==='settlement')&&<EntryForm key={modal.entry?.id||modal.kind} entry={modal.entry} kind={modal.kind} names={names} member={active} initialCents={modal.kind==='settlement'?Math.abs(credit):0} busy={busy} error={formError} onSave={p=>save('entry',p,modal.kind==='settlement'?'Remboursement enregistré.':'Dépense partagée à 50/50.')} onDelete={modal.entry?()=>open({kind:'delete',entry:modal.entry}):undefined}/>}
   {(modal.kind==='shopping'||modal.kind==='task')&&<ItemForm key={modal.item?.id||modal.kind} item={modal.item} kind={modal.kind} names={names} busy={busy} error={formError} onSave={p=>save('item',p)} onDelete={modal.item?()=>open({kind:'delete',item:modal.item}):undefined}/>}
   {modal.kind==='appointment'&&<AppointmentForm appointment={modal.appointment} initialDate={modal.initialDate} initialStatus={modal.initialStatus} names={names} busy={busy} error={formError} onSave={p=>save('appointment',p,'Rendez-vous enregistré dans votre calendrier.')} onDelete={modal.appointment?()=>open({kind:'delete',appointment:modal.appointment}):undefined}/>}
   {modal.kind==='delete'&&<><p className="dialog-description">« {modal.entry?.title||modal.item?.title||modal.appointment?.title} » sera supprimé sur tous vos appareils.{modal.entry&&' Le solde sera recalculé.'}</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="dialog-actions"><button className="secondary" disabled={busy} onClick={()=>setModal(null)}>Annuler</button><button className="danger" disabled={busy} onClick={()=>save(modal.appointment?'delete-appointment':modal.entry?'delete-entry':'delete-item',modal.appointment||modal.entry||modal.item,'Élément supprimé.')}><Trash2 size={17}/>{busy?'Suppression…':'Supprimer'}</button></div></>}
   </fieldset>{modal.kind==='install'&&<div className="install-help"><div className="install-icon"><Heart size={38}/><span>à deux.</span></div><h3>Sur votre iPhone ou iPad</h3><ol><li>Ouvrez cette application dans <strong>Safari</strong>.</li><li>Touchez le bouton <strong>Partager</strong>.</li><li>Choisissez <strong>Sur l’écran d’accueil</strong>, puis <strong>Ajouter</strong>.</li></ol><p>Sur Android, ouvrez le menu de Chrome puis « Ajouter à l’écran d’accueil ».</p><div className="info-box"><LockKeyhole size={19}/><span>Entrez votre mot de passe personnel sur chaque appareil. Une connexion internet est nécessaire.</span></div></div>}
  </Dialog>}
 </div>;
}
function SettingsForm({initial,busy,error,onSave,active=0}:{active?:number;initial:Household|null;busy:boolean;error:string;onSave:(h:Household)=>Promise<boolean>}){
 const[localError,setLocalError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLocalError('');const f=new FormData(e.currentTarget);try{const first=active===1&&initial?initial.first:String(f.get('first')).trim(),second=active===0&&initial?initial.second:String(f.get('second')).trim();if(first.toLocaleLowerCase()===second.toLocaleLowerCase())throw new Error('Choisissez deux prénoms distincts.');await onSave({first,second,name:String(f.get('name')||'Notre maison').trim(),budget:centsFromInput(String(f.get('budget')||'0')),version:initial?.version||0});}catch(e){setLocalError(e instanceof Error?e.message:'Vérifiez les champs.');}}
 return <form onSubmit={submit} className="form"><div className="form-grid"><label>Votre prénom<input disabled={!!initial&&active!==0} name="first" placeholder="Votre prénom" maxLength={24} required defaultValue={initial?.first||'Abdellah'}/></label><label>Son prénom<input disabled={!!initial&&active!==1} name="second" placeholder="Le prénom de votre moitié" maxLength={24} required defaultValue={initial?.second||''}/></label></div>{initial&&<><label>Le nom de votre espace<input name="name" maxLength={50} defaultValue={initial.name} required/></label><label>Budget commun mensuel (facultatif)<div className="amount-input"><input name="budget" inputMode="decimal" placeholder="0,00" defaultValue={initial.budget?String(initial.budget/100):''}/><span>€</span></div><small>Laissez vide si vous ne souhaitez pas définir de budget.</small></label></>}{(localError||error)&&<p className="form-error" role="alert">{localError||error}</p>}<button className="primary wide" disabled={busy} type="submit">{busy?<LoaderCircle size={18} className="spin"/>:initial?<Check size={18}/>:<ArrowRight size={18}/>} {initial?'Enregistrer les changements':'Entrer dans notre maison'}</button></form>;
}
function EntryForm({entry,kind,names,member,initialCents,busy,error,onSave,onDelete}:{entry?:Entry;kind:'expense'|'settlement';names:string[];member:number;initialCents:number;busy:boolean;error:string;onSave:(v:unknown)=>Promise<boolean>;onDelete?:()=>void}){
 const[id]=useState(()=>entry?.id||crypto.randomUUID());const[payer,setPayer]=useState(entry?.member??member);const[amount,setAmount]=useState(entry?String(entry.cents/100):initialCents?String(initialCents/100):'');const[localError,setLocalError]=useState('');const isExpense=kind==='expense';
 let cents=0;try{cents=centsFromInput(amount||'0');}catch{}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLocalError('');const f=new FormData(e.currentTarget);try{const value=centsFromInput(amount);if(value<=0)throw new Error('Le montant doit être supérieur à zéro.');await onSave({id,version:entry?.version||0,kind,title:isExpense?String(f.get('title')).trim():'Remboursement',cents:value,member:payer,category:String(f.get('category')||'Autre'),date:String(f.get('date')),note:String(f.get('note')||'')});}catch(e){setLocalError(e instanceof Error?e.message:'Vérifiez le montant.');}}
 return <form className="form" onSubmit={submit}>{isExpense&&<label>Pour quoi ?<input autoFocus name="title" required maxLength={100} defaultValue={entry?.title||''} placeholder="Les courses de la semaine"/></label>}<label>Montant<div className="amount-input large"><input autoFocus={!isExpense} aria-label="Montant en euros" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" required maxLength={12}/><span>€</span></div></label><fieldset><legend>{isExpense?'Qui a payé ?':'Qui a remboursé ?'}</legend><div className="person-options">{names.map((n,i)=><button type="button" key={i} className={payer===i?'selected':''} disabled={i!==member} onClick={()=>setPayer(i)} aria-pressed={payer===i}><Avatar name={n} second={i===1} small/>{n}{payer===i&&<Check size={15}/>}</button>)}</div></fieldset><div className="form-grid">{isExpense&&<label>Catégorie<select name="category" defaultValue={entry?.category||'Courses'}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>}<label>Date<input name="date" type="date" defaultValue={entry?.date||today()} required/></label></div>{isExpense?<div className="split-preview"><span><ArrowLeftRight size={16}/>Répartition 50 / 50</span><div><span>{names[0]}<strong>{money(Math.ceil(cents/2))}</strong></span><span>{names[1]}<strong>{money(Math.floor(cents/2))}</strong></span></div></div>:<div className="info-box"><ArrowLeftRight size={19}/><span>{names[payer]} a versé <strong>{money(cents)}</strong> à {names[1-payer]}. Ceci enregistre un remboursement déjà effectué, sans transférer d’argent.</span></div>}<label>Une petite note <span className="optional">(facultatif)</span><textarea name="note" rows={2} maxLength={300} defaultValue={entry?.note||''} placeholder={isExpense?'Un détail à garder…':'Virement, espèces…'}/></label>{(error||localError)&&<p role="alert" className="form-error">{localError||error}</p>}<div className="dialog-actions">{onDelete&&<button className="icon-button delete-button" type="button" onClick={onDelete} disabled={busy} aria-label="Supprimer"><Trash2 size={19}/></button>}<button className="primary grow" disabled={busy} type="submit">{busy?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>} {busy?'Enregistrement…':entry?'Enregistrer les modifications':isExpense?'Ajouter la dépense':'Enregistrer le remboursement'}</button></div></form>;
}
function ItemForm({item,kind,names,busy,error,onSave,onDelete}:{item?:Item;kind:'shopping'|'task';names:string[];busy:boolean;error:string;onSave:(v:unknown)=>Promise<boolean>;onDelete?:()=>void}){
 const[id]=useState(()=>item?.id||crypto.randomUUID());async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await onSave({id,version:item?.version||0,kind,title:String(f.get('title')).trim(),quantity:String(f.get('quantity')||''),assignee:Number(f.get('assignee')),due:String(f.get('due')||''),priority:f.get('priority')?1:0,done:item?.done||false});}
 return <form className="form" onSubmit={submit}><label>{kind==='shopping'?'Qu’est-ce qu’on achète ?':'Qu’est-ce qu’on fait ?'}<input autoFocus name="title" required maxLength={100} defaultValue={item?.title||''} placeholder={kind==='shopping'?'Des tomates, du pain…':'Arroser les plantes…'}/></label>{kind==='shopping'&&<label>Quantité ou précision<input name="quantity" maxLength={50} defaultValue={item?.quantity||''} placeholder="1 kg, 2 paquets…"/></label>}<label>{kind==='shopping'?'Qui s’en occupe ?':'Pour qui ?'}<select name="assignee" defaultValue={item?.assignee??-1}><option value={-1}>L’un de nous</option>{names.map((n,i)=><option value={i} key={i}>{n}</option>)}</select></label>{kind==='task'&&<><label>Pour quand ? <span className="optional">(facultatif)</span><input name="due" type="date" defaultValue={item?.due||''}/></label><label className="check-label"><input name="priority" type="checkbox" defaultChecked={item?.priority===1}/><Flag size={16}/>C’est une priorité</label></>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions">{onDelete&&<button className="icon-button delete-button" type="button" aria-label="Supprimer" onClick={onDelete} disabled={busy}><Trash2 size={19}/></button>}<button className="primary grow" type="submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>} {busy?'Enregistrement…':item?'Enregistrer les modifications':kind==='shopping'?'Ajouter à la liste':'Ajouter la tâche'}</button></div></form>;
}
