'use client';
import {useEffect,useRef,useState,type ReactNode,type RefObject} from 'react';
import {useDialog} from './use-dialog';
import {apiFetch} from '../lib/api-client';
import {Phone,PhoneOff,Mic,MicOff,Volume2,Video,VideoOff,SwitchCamera,ChevronDown,Headphones,Clock} from './icons';
import {ProfileAvatar} from './profile-photo';
import {createCallEngine,type CallEngine,type CallMedia} from './daily-engine';
import {useCallRingtone} from './call-ringtone';
import LifeDialog from './life-dialog';
export type Call={id:string;caller:number;mode:'audio'|'video';state:string;mine:boolean;createdAt:number;expiresAt:number;maxExpiresAt:number;connectedAt:number|null;endedAt:number|null;endReason:string|null};
type Result={configured?:boolean;call:Call|null;history?:Call[];estimatedMinutes?:number;join?:{url:string;token:string};ended?:Call;error?:string};
type Props={active:number;names:string[];expanded:boolean;onOpen:()=>void;request?:{mode:'audio'|'video';key:number;actor:number}|null};
const duration=(ms:number)=>{const seconds=Math.max(0,Math.floor(ms/1000));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;};
const endedLabel=(call?:Call)=>call?.state==='missed'?'Appel manqué':call?.state==='declined'?'Appel refusé':call?.state==='failed'?'Connexion perdue':call?.endReason==='time_limit'?'Limite de deux heures atteinte':'Appel terminé';
function Track({track,video=false,muted=false,onBlocked,audioRef}:{track?:MediaStreamTrack;video?:boolean;muted?:boolean;onBlocked?:()=>void;audioRef?:RefObject<HTMLAudioElement|null>}){
 const ref=useRef<HTMLMediaElement|null>(null),blocked=useRef(onBlocked);blocked.current=onBlocked;
 useEffect(()=>{const element=ref.current;if(!element)return;element.srcObject=track?new MediaStream([track]):null;if(track)void element.play().catch(()=>blocked.current?.());return()=>{element.srcObject=null;};},[track]);
 return video?<video ref={el=>{ref.current=el;}} autoPlay playsInline muted={muted}/>:<audio ref={el=>{ref.current=el;if(audioRef)audioRef.current=el;}} autoPlay playsInline/>;
}
function CallModal({children,video,onMinimize}:{children:ReactNode;video:boolean;onMinimize:()=>void}){const ref=useRef<HTMLDialogElement|null>(null);useDialog(ref);return <dialog ref={ref} className={`daily-call-stage daily-call-overlay ${video?'with-video':''}`} aria-label="Appel privé à deux" onCancel={e=>{e.preventDefault();onMinimize();}}>{children}</dialog>;}
function CallSurface({children,video,immersive,onMinimize}:{children:ReactNode;video:boolean;immersive:boolean;onMinimize:()=>void}){return immersive?<CallModal video={video} onMinimize={onMinimize}>{children}</CallModal>:<section className="daily-call-stage" aria-label="Appel privé à deux">{children}</section>;}
export default function HouseCalls({active,names,expanded,onOpen,request}:Props){
 const[call,setCall]=useState<Call|null>(null),[history,setHistory]=useState<Call[]>([]),[configured,setConfigured]=useState<boolean|null>(null),[estimated,setEstimated]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[network,setNetwork]=useState(''),[media,setMedia]=useState<CallMedia>({}),[muted,setMuted]=useState(false),[camera,setCamera]=useState(false),[now,setNow]=useState(Date.now),[audioBlocked,setAudioBlocked]=useState(false),[deviceOpen,setDeviceOpen]=useState(false),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[output,setOutput]=useState('default'),[input,setInput]=useState(''),[minimized,setMinimized]=useState(false);
 const engine=useRef<CallEngine|null>(null),current=useRef<Call|null>(null),localId=useRef(''),session=useRef(''),alive=useRef(true),generation=useRef(0),operation=useRef(false),polling=useRef(false),lastBeat=useRef(0),lastRequest=useRef(0),remotePresent=useRef(false),audio=useRef<HTMLAudioElement|null>(null),ending=useRef(false),pollRef=useRef<()=>Promise<void>>(async()=>{});
 const incoming=!!call&&call.caller!==active&&call.state==='ringing'&&!call.mine;
 const {soundReady,unlock}=useCallRingtone(incoming&&!busy);
 function apply(c:Call|null){current.current=c;setCall(c);}
 async function post(action:string,id:string,extra:Record<string,unknown>={}){const r=await apiFetch('/api/daily-calls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,session:session.current,...extra}),signal:AbortSignal.timeout(45000)});const d=await r.json() as Result;if(!r.ok)throw new Error(d.error||'Appel indisponible.');return d;}
 async function release(){generation.current++;const e=engine.current;engine.current=null;localId.current='';remotePresent.current=false;setMedia({});setCamera(false);setMuted(false);setNetwork('');setAudioBlocked(false);if(e)await e.destroy().catch(()=>{});}
 async function finish(action='end',reason=''){
  if(ending.current)return;ending.current=true;const id=localId.current||current.current?.id;await release();setBusy(false);setStatus(action==='decline'?'Appel refusé':'Appel terminé');apply(null);
  try{if(id){const d=await post(action,id);setStatus(reason||endedLabel(d.ended));}}catch{setStatus('Appel arrêté sur cet appareil. La session distante expirera automatiquement.');}finally{ending.current=false;void pollRef.current();}
 }
 useEffect(()=>{
  alive.current=true;try{session.current=sessionStorage.getItem('nous-deux-call-device')||crypto.randomUUID();sessionStorage.setItem('nous-deux-call-device',session.current);}catch{session.current=crypto.randomUUID();}
  async function poll(){if(!alive.current||polling.current||operation.current||ending.current||document.visibilityState!=='visible'&&!engine.current)return;polling.current=true;const revision=generation.current;
   try{const r=await apiFetch('/api/daily-calls?session='+session.current,{signal:AbortSignal.timeout(12000)});const d=await r.json() as Result;if(!r.ok)throw new Error(d.error||'Appels indisponibles.');if(!alive.current||operation.current||ending.current||revision!==generation.current)return;setConfigured(!!d.configured);setHistory(d.history||[]);setEstimated(d.estimatedMinutes||0);apply(d.call);
    if(localId.current&&(!d.call||d.call.id!==localId.current)){const ended=d.history?.find(c=>c.id===localId.current);await release();setStatus(endedLabel(ended));}
    if(d.call&&engine.current&&localId.current===d.call.id&&Date.now()-lastBeat.current>12000){lastBeat.current=Date.now();await post('heartbeat',d.call.id,{connected:remotePresent.current});}
   }catch(e){if(alive.current&&revision===generation.current&&!ending.current){if(engine.current)setNetwork('reconnecting');else setStatus(e instanceof Error?e.message:'Connexion interrompue.');}}finally{polling.current=false;}}
  pollRef.current=poll;void poll();const timer=setInterval(poll,2000),clock=setInterval(()=>setNow(Date.now()),1000);
  const push=(event:MessageEvent)=>{if(event.data?.type==='nousdeux-call'){void poll();if(event.data.open){setMinimized(false);onOpen();}}};
  document.addEventListener('visibilitychange',poll);window.addEventListener('online',poll);navigator.serviceWorker?.addEventListener('message',push);
  return()=>{alive.current=false;clearInterval(timer);clearInterval(clock);document.removeEventListener('visibilitychange',poll);window.removeEventListener('online',poll);navigator.serviceWorker?.removeEventListener('message',push);const id=localId.current;if(id)void post('end',id).catch(()=>{});void release();};
 // Calls remain mounted across tabs; account changes remount this component.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 useEffect(()=>{if(expanded)setMinimized(false);},[expanded]);
 useEffect(()=>{if(!request||request.actor!==active||request.key===lastRequest.current||configured===null)return;lastRequest.current=request.key;if(!current.current)void dial(request.mode);},[request,configured]);
 async function dial(mode:'audio'|'video',answer=false,rejoin=false){
  if(operation.current||ending.current||engine.current)return;if(!configured){setStatus('Les appels Daily attendent leur activation.');return;}if(!navigator.mediaDevices?.getUserMedia){setStatus('Ouvrez Nous deux dans une version récente de Safari ou Chrome.');return;}
  operation.current=true;setBusy(true);setMinimized(false);setStatus('Autorisez le microphone'+(mode==='video'?' et la caméra':'')+' pour démarrer.');await unlock();const attempt=generation.current;let id=answer||rejoin?current.current?.id:crypto.randomUUID();
  try{
   if(!id)throw new Error('Cet appel n’est plus disponible.');
   const e=await createCallEngine({media:m=>{if(!alive.current||attempt!==generation.current)return;setMedia(m);remotePresent.current=!!m.remote;setMuted(m.local?.audio===false);setCamera(m.local?.video===true);},network:n=>{if(alive.current&&attempt===generation.current)setNetwork(n);},error:(message,fatal)=>{if(attempt!==generation.current)return;setStatus(message);if(fatal)void finish('end',message);},left:()=>{if(attempt===generation.current&&!ending.current)void finish();}});
   if(attempt!==generation.current){await e.destroy();return;}engine.current=e;await e.prepare(mode==='video');if(attempt!==generation.current)return;
   localId.current=id;setStatus(answer?'Connexion…':'Appel en cours…');const d=await post(rejoin?'join':answer?'accept':'start',id,{mode});
   if(attempt!==generation.current){await post('end',id).catch(()=>{});return;}if(!d.join)throw new Error('Accès à l’appel indisponible.');apply(d.call);setStatus(answer?'Connexion…':'Ça sonne…');await e.join(d.join.url,d.join.token);setStatus('');
  }catch(e){await release();if(id)void post('end',id).catch(()=>{});apply(null);setStatus(e instanceof DOMException&&e.name==='NotAllowedError'?'Autorisation refusée. Activez le microphone et, pour la vidéo, la caméra dans les réglages du navigateur.':e instanceof Error?e.message:'L’appel n’a pas pu démarrer.');}finally{operation.current=false;if(alive.current)setBusy(false);void pollRef.current();}
 }
 async function listDevices(){try{setDevices(await navigator.mediaDevices.enumerateDevices());setDeviceOpen(true);}catch{setStatus('Les appareils audio ne sont pas accessibles dans ce navigateur.');}}
 const mine=!!call?.mine,live=mine&&!!engine.current,connected=!!media.remote,showStage=(expanded&&!minimized)||incoming||(live&&!minimized),video=!!media.remote?.video||camera;
 const remoteVideo=media.remote?.tracks.video.state==='playable'?media.remote.tracks.video.persistentTrack:undefined;
 const remoteAudio=media.remote?.tracks.audio.state==='playable'?media.remote.tracks.audio.persistentTrack:undefined;
 const localVideo=media.local?.tracks.video.state==='playable'?media.local.tracks.video.persistentTrack:undefined;
 const label=incoming?'Vous appelle…':network==='reconnecting'?'Connexion perdue · reconnexion…':connected?'Connecté':call?.state==='ringing'?'Ça sonne…':live?'Connexion…':status||`Un moment avec ${names[1-active]}`;
 return <><Track track={remoteAudio} audioRef={audio} onBlocked={()=>setAudioBlocked(true)}/>
 {!showStage&&live&&<button className="call-mini" onClick={()=>{setMinimized(false);onOpen();}}><Phone size={18}/><span>{names[1-active]} · {connected&&call?.connectedAt?duration(now-call.connectedAt):label}</span></button>}
 {showStage&&<CallSurface video={video} immersive={incoming||live} onMinimize={()=>{if(!incoming)setMinimized(true);}}>
 <header className="daily-call-header"><span>{video?'Un tête-à-tête':'Juste votre voix'}</span>{live&&<button className="icon-button" aria-label="Réduire l’appel" onClick={()=>{setMinimized(true);}}><ChevronDown/></button>}</header>
 <div className="daily-call-scene">{remoteVideo&&<div className="daily-remote-video"><Track track={remoteVideo} video muted/></div>}<div className={`daily-caller ${remoteVideo?'over-video':''}`}><ProfileAvatar member={1-active} name={names[1-active]} className="daily-call-avatar"/><h2>{names[1-active]}</h2><p role="status">{label}</p>{connected&&call?.connectedAt&&<time aria-label="Durée de l’appel">{duration(now-call.connectedAt)}</time>}</div>{localVideo&&<div className="daily-local-video"><Track track={localVideo} video muted/><span>Vous</span></div>}</div>
 {configured===false&&<p className="call-notice">Les appels Daily attendent leur activation.</p>}
 {incoming&&!soundReady&&<button className="secondary" onClick={unlock}><Volume2 size={18}/>Activer la sonnerie</button>}
 <div className="daily-call-controls">{incoming?<><button className="call-control accept" disabled={busy} onClick={()=>dial(call!.mode,true)}><Phone/><span>Répondre</span></button><button className="call-control hangup" disabled={busy} onClick={()=>finish('decline')}><PhoneOff/><span>Refuser</span></button></>:live||busy?<><button className={`call-control ${muted?'is-off':''}`} disabled={busy} aria-pressed={muted} onClick={()=>engine.current?.mute(!muted)}>{muted?<MicOff/>:<Mic/>}<span>{muted?'Micro coupé':'Micro'}</span></button><button className={`call-control ${camera?'':'is-off'}`} disabled={busy} aria-pressed={camera} onClick={()=>engine.current?.camera(!camera).catch(()=>setStatus('Autorisez la caméra dans les réglages du navigateur.'))}>{camera?<Video/>:<VideoOff/>}<span>Caméra</span></button>{camera&&<button className="call-control" onClick={()=>engine.current?.flip().catch(()=>setStatus('Impossible de changer de caméra.'))}><SwitchCamera/><span>Retourner</span></button>}<button className="call-control" disabled={busy} onClick={listDevices}><Headphones/><span>Audio</span></button><button className="call-control hangup" onClick={()=>finish()}><PhoneOff/><span>Raccrocher</span></button></>:mine?<button className="primary" onClick={()=>dial(call!.mode,false,true)}><Phone size={18}/>Rejoindre l’appel</button>:<><button className="primary" disabled={!configured||!!call} onClick={()=>dial('audio')}><Phone size={20}/>Appel audio</button><button className="secondary" disabled={!configured||!!call} onClick={()=>dial('video')}><Video size={20}/>Appel vidéo</button></>}</div>
 {call&&!mine&&!incoming&&<p>Un appel est ouvert sur un autre appareil.</p>}
 {audioBlocked&&<button className="secondary" onClick={()=>audio.current?.play().then(()=>setAudioBlocked(false)).catch(()=>setStatus('Touchez à nouveau pour autoriser le son.'))}><Volume2 size={18}/>Écouter l’appel</button>}
 {status&&live&&<p className="call-notice" role="status">{status}</p>}
 <p className="daily-call-note">Gardez l’application ouverte. La sortie audio dépend de votre téléphone et de vos écouteurs. Aucun enregistrement. Limite : 2 h par appel.</p>
 </CallSurface>}
 {expanded&&!live&&!incoming&&<section className="panel call-history"><h2>Nos derniers appels</h2>{history.length?history.map(c=><article key={c.id}><span className={`call-history-icon ${c.state==='missed'?'missed':''}`}>{c.mode==='video'?<Video size={20}/>:<Phone size={20}/>}</span><div><strong>{endedLabel(c)}</strong><small>{c.caller===active?'Sortant':'Entrant'} · {new Date(c.createdAt).toLocaleString('fr-FR',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}{c.connectedAt&&c.endedAt?' · '+duration(c.endedAt-c.connectedAt):''}</small></div><button className="icon-button" aria-label={'Rappeler '+names[1-active]} disabled={!configured||!!call} onClick={()=>dial(c.mode)}><Phone size={18}/></button></article>):<p>Vos appels et vos appels manqués apparaîtront ici.</p>}<p className="helper-copy"><Clock size={14}/> Estimation ce mois : {estimated.toLocaleString('fr-FR')} minutes-participants sur les 10 000 gratuites. Le compteur Daily fait foi.</p>{estimated>=8000&&<p className="form-error">Vous approchez ou dépassez les minutes gratuites. Vérifiez votre consommation Daily avant de poursuivre.</p>}</section>}
 {deviceOpen&&<LifeDialog title="Le son de notre appel" onClose={()=>setDeviceOpen(false)}><div className="form"><label>Microphone<select value={input} onChange={async e=>{const id=e.target.value;try{await engine.current?.microphone(id);setInput(id);}catch{setStatus('Ce microphone n’est pas disponible.');}}}><option value="">Choix du téléphone</option>{devices.filter(d=>d.kind==='audioinput').map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'Microphone'}</option>)}</select></label>{audio.current&&'setSinkId'in audio.current&&devices.filter(d=>d.kind==='audiooutput').length>1?<label>Écouter avec<select value={output} onChange={async e=>{const id=e.target.value;try{await (audio.current as HTMLAudioElement&{setSinkId:(id:string)=>Promise<void>}).setSinkId(id);setOutput(id);}catch{setStatus('Cette sortie audio ne peut pas être sélectionnée dans ce navigateur.');}}}><option value="default">Choix du téléphone</option>{devices.filter(d=>d.kind==='audiooutput'&&d.deviceId!=='default').map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||'Sortie audio'}</option>)}</select></label>:<p>Le navigateur laisse votre téléphone choisir la sortie audio. Pour utiliser vos écouteurs, connectez-les au téléphone. Le passage écouteur interne / haut-parleur n’est pas garanti dans cette version web.</p>}</div></LifeDialog>}</>;
}
