'use client';
import {useState,type FormEvent} from 'react';
import {CalendarDays,ChevronLeft,ChevronRight,Plus,Clock3,MapPin,Stethoscope,Phone,Check,Trash2,LoaderCircle,ArrowUpRight,ChevronDown} from 'lucide-react';
import {today,type Appointment} from '../lib/domain';
import {calendarDays,shiftMonth,sortAppointments,appointmentCategories,editableCategories,occurrences,onDay,addDays} from '../lib/calendar';
import {holidays} from '../lib/holidays';
const longDate=(date:string)=>new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
const shortDate=(date:string)=>new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
const monthName=(month:string)=>new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(month+'-01T12:00:00Z'));
export type OpenAppointment={appointment?:Appointment;initialDate?:string;initialStatus?:'to_book'|'scheduled'};
type CalendarProps={active?:number;appointments:Appointment[];names:string[];onOpen:(options:OpenAppointment)=>void};
function AppointmentRow({appointment:a,names,onClick,showDate=false}:{appointment:Appointment;names:string[];onClick:()=>void;showDate?:boolean}){
 return <button className={`appointment-row ${a.status==='done'?'appointment-done':''}`} onClick={onClick}>
  <span className={`appointment-icon appointment-${a.category}`}>{a.category==='medical'?<Stethoscope size={20}/>:a.status==='to_book'?<Phone size={20}/>:<CalendarDays size={20}/>}</span>
  <span className="appointment-content"><strong>{a.title}</strong><span>{a.source?'Repère du calendrier':a.visibility==='private'?'🔒 Privé · moi uniquement':'Partagé à deux'}{a.recurrence&&a.recurrence!=='none'?' · ↻ Récurrent':''}{a.provisional?' · À confirmer':''}</span><span>{a.person===-1?'Nous deux':names[a.person]}<span>·</span>{appointmentCategories[a.category]}</span>
   {a.status==='to_book'&&a.bookBy&&<span className={a.bookBy<today()?'overdue':''}>À prendre avant le {shortDate(a.bookBy)}</span>}
   {a.endDate&&a.endDate!==a.date&&<span>Du {shortDate(a.date)} au {shortDate(a.endDate)}</span>}{a.location&&<span className="appointment-location"><MapPin size={12}/>{a.location}</span>}
  </span>
  <span className="appointment-when">{a.status==='to_book'?<span className="booking-pill">À prendre</span>:<>{showDate&&<span>{shortDate(a.date)}</span>}<strong>{a.time||'Toute la journée'}</strong>{a.status==='done'&&<small><Check size={12}/>Terminé</small>}</>}</span>
 </button>;
}
export function CalendarSummary({appointments,names,onOpen,onCalendar}:CalendarProps&{onCalendar:()=>void}){
 const pending=appointments.filter(a=>a.status==='to_book');
 const upcoming=occurrences(appointments.filter(a=>a.status==='scheduled'),today(),addDays(today(),366)).slice(0,3);
 return <section className="panel calendar-summary"><div className="section-title"><h2><CalendarDays size={18}/>Nos prochaines dates</h2><button className="text-link" onClick={onCalendar}>Le calendrier <ArrowUpRight size={15}/></button></div>
  {upcoming.length?upcoming.map(a=><AppointmentRow key={a.id+'-'+a.date} appointment={a} names={names} onClick={()=>onOpen({appointment:a})} showDate/>):<div className="calendar-summary-empty"><p>Un rendez-vous, une date importante… gardons-les au même endroit.</p><button className="text-link" onClick={()=>onOpen({initialStatus:'scheduled',initialDate:today()})}><Plus size={15}/>Ajouter une date</button></div>}
  {pending.length>0&&<button className="booking-summary" onClick={onCalendar}><Phone size={16}/>{pending.length} rendez-vous à prendre<ArrowUpRight size={16}/></button>}
 </section>;
}
export default function HouseCalendar({appointments,names,onOpen,active=0}:CalendarProps){
 const[month,setMonth]=useState(today().slice(0,7));
 const[selected,setSelected]=useState(today());const[person,setPerson]=useState('all');
 const[category,setCategory]=useState('all');const[scope,setScope]=useState('all');const[references,setReferences]=useState(true);
 const grid=calendarDays(month);
 const filtered=[...appointments,...(references?holidays:[])].filter(a=>(person==='all'||a.person===Number(person))&&(category==='all'||a.category===category||a.holidayGroups?.includes(category))&&(scope==='all'||!a.source&&(scope==='mine'?a.owner===active:scope==='private'?a.visibility==='private':a.visibility!=='private')));
 const booked=occurrences(filtered,grid[0],grid[grid.length-1]);
 const toBook=filtered.filter(a=>a.status==='to_book').sort((a,b)=>(a.bookBy||'9999').localeCompare(b.bookBy||'9999')||a.createdAt.localeCompare(b.createdAt));
 const byDay=new Map<string,Appointment[]>();grid.forEach(date=>byDay.set(date,booked.filter(a=>onDay(a,date))));
 const dayAppointments=byDay.get(selected)||[];const inMonth=booked.filter(a=>a.date.slice(0,7)<=month&&(a.endDate||a.date).slice(0,7)>=month);
 function changeMonth(step:number){const next=shiftMonth(month,step);setMonth(next);setSelected(next===today().slice(0,7)?today():next+'-01');}
 function selectDate(date:string){setSelected(date);setMonth(date.slice(0,7));}
 return <div className="calendar-page">
  <div className="calendar-filters"><label>Afficher<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">Tout ce que je peux voir</option><option value="mine">Mon calendrier</option><option value="private">Mes événements privés</option><option value="shared">Partagés à deux</option></select></label><label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Toutes les catégories</option>{Object.entries(appointmentCategories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={references} onChange={e=>setReferences(e.target.checked)}/>Fêtes et jours fériés</label></div><p className="calendar-help">Les dates privées ne sont visibles que par leur auteur. Les fêtes préremplies couvrent 2026–2027 ; les dates musulmanes signalées « à confirmer » dépendent de l’observation lunaire.</p><div className="calendar-toolbar"><div className="calendar-person-filter"><label htmlFor="calendar-person">Pour qui ?</label><select id="calendar-person" value={person} onChange={e=>setPerson(e.target.value)}><option value="all">Tout le monde</option><option value="-1">Nous deux</option>{names.map((name,i)=><option key={i} value={i}>{name}</option>)}</select></div><button className="secondary" onClick={()=>onOpen({initialStatus:'to_book'})}><Phone size={16}/>Noter un RDV à prendre</button></div>
  <div className="calendar-layout"><div className="calendar-main"><section className="panel calendar-panel" aria-label="Calendrier mensuel">
   <div className="calendar-month-header"><div className="calendar-month-controls"><button className="icon-button" onClick={()=>changeMonth(-1)} aria-label="Mois précédent"><ChevronLeft size={20}/></button><label className="calendar-month-title"><span>{monthName(month)}</span><input aria-label="Choisir le mois du calendrier" type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setSelected(e.target.value+'-01');}}}/></label><button className="icon-button" onClick={()=>changeMonth(1)} aria-label="Mois suivant"><ChevronRight size={20}/></button></div><button className="calendar-today" onClick={()=>selectDate(today())}>Aujourd’hui</button></div>
   <div className="calendar-weekdays" aria-hidden="true">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=><span key={d}>{d}</span>)}</div>
   <div className="calendar-grid">{calendarDays(month).map(date=>{const events=byDay.get(date)||[];return <button key={date} className={`calendar-day ${!date.startsWith(month)?'outside-month':''} ${date===selected?'selected':''} ${date===today()?'is-today':''}`} aria-pressed={date===selected} aria-current={date===today()?'date':undefined} aria-label={`${longDate(date)}, ${events.length} rendez-vous`} onClick={()=>selectDate(date)}><span className="calendar-day-number">{Number(date.slice(-2))}</span><span className="calendar-day-events">{events.slice(0,2).map(a=><span className={`calendar-event-chip appointment-${a.category} ${a.status==='done'?'calendar-event-done':''}`} key={a.id+'-'+a.date}>{a.time&&<b>{a.time} </b>}{a.title}</span>)}{events.length>2&&<span className="calendar-more">+{events.length-2}</span>}</span><span className="calendar-mobile-dots" aria-hidden="true">{events.slice(0,3).map(a=><i className={`appointment-${a.category}`} key={a.id+'-'+a.date}/>)}{events.length>3&&<small>+</small>}</span></button>;})}</div>
   <div className="calendar-legend">{Object.entries(appointmentCategories).filter(([id])=>filtered.some(a=>a.category===id)).map(([id,label])=><span key={id}><i className={'appointment-'+id}/>{label}</span>)}</div>
  </section>
  <section className="panel calendar-day-panel"><div className="section-title"><h2>{longDate(selected)}</h2><button className="icon-button" aria-label={`Ajouter un rendez-vous le ${longDate(selected)}`} onClick={()=>onOpen({initialStatus:'scheduled',initialDate:selected})}><Plus size={20}/></button></div>
   {dayAppointments.length?dayAppointments.map(a=><AppointmentRow key={a.id+'-'+a.date} appointment={a} names={names} onClick={()=>onOpen({appointment:a})}/>):<div className="calendar-empty"><CalendarDays size={25}/><p>Aucun rendez-vous ce jour-là{person!=='all'?' pour cette sélection':''}.</p><button className="text-link" onClick={()=>onOpen({initialStatus:'scheduled',initialDate:selected})}>Ajouter à cette date <Plus size={15}/></button></div>}
  </section>
  {inMonth.length>0&&<details className="panel calendar-month-list"><summary>Tous les événements du mois · {inMonth.length}<ChevronDown size={16}/></summary>{inMonth.map(a=><AppointmentRow key={a.id+'-'+a.date} appointment={a} names={names} onClick={()=>onOpen({appointment:a})} showDate/>)}</details>}
  </div>
  <aside className="panel booking-panel"><div className="section-title"><h2><Phone size={17}/>À prendre<span className="count-badge">{toBook.length}</span></h2></div><p className="booking-intro">Les rendez-vous à organiser, même sans date pour le moment.</p>
   {toBook.length?toBook.map(a=><div className="booking-card" key={a.id+'-'+a.date}><AppointmentRow appointment={a} names={names} onClick={()=>onOpen({appointment:a})}/><button disabled={a.owner!==active} className="booking-plan" onClick={()=>onOpen({appointment:a,initialStatus:'scheduled'})}>La date est fixée <ArrowUpRight size={15}/></button></div>):<div className="calendar-empty"><Check size={25}/><p>Aucun rendez-vous à prendre{person!=='all'?' pour cette sélection':''}.</p></div>}
   <button className="add-row" onClick={()=>onOpen({initialStatus:'to_book'})}><Plus size={18}/>Ajouter un RDV à prendre</button>
  </aside></div>
 </div>;
}
export function AppointmentForm({active=0,appointment,initialDate,initialStatus,names,busy,error,onSave,onDelete}:{active?:number;appointment?:Appointment;initialDate?:string;initialStatus?:'to_book'|'scheduled';names:string[];busy:boolean;error:string;onSave:(payload:unknown)=>Promise<boolean>;onDelete?:()=>void}){
 const[visibility,setVisibility]=useState<"private"|"shared">(appointment?.visibility||(appointment?'shared':'private'));const[recurrence,setRecurrence]=useState(appointment?.recurrence||'none');const[endDate,setEndDate]=useState(appointment?.endDate||'');const[repeatUntil,setRepeatUntil]=useState(appointment?.repeatUntil||'');
 const[id]=useState(()=>appointment?.id||crypto.randomUUID());
 const[status,setStatus]=useState<Appointment['status']>(initialStatus||appointment?.status||'scheduled');
 const[date,setDate]=useState(appointment?.date||initialDate||today());const[time,setTime]=useState(appointment?.time||'');const[bookBy,setBookBy]=useState(appointment?.bookBy||'');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await onSave({id,visibility,recurrence:status==='to_book'?'none':recurrence,endDate:status==='to_book'?'':endDate,repeatUntil:status==='to_book'||recurrence==='none'?'':repeatUntil,version:appointment?.version||0,title:String(f.get('title')).trim(),category:String(f.get('category')),person:Number(f.get('person')),status,date:status==='to_book'?'':date,time:status==='to_book'?'':time,bookBy:status==='to_book'?bookBy:'',location:String(f.get('location')||'').trim(),note:String(f.get('note')||'').trim()});}
 return <form className="form appointment-form" onSubmit={submit}>
  <label>Quel événement ?<input autoFocus name="title" maxLength={100} required defaultValue={appointment?.title||''} placeholder="Dentiste, anniversaire, voyage, dîner…"/></label>
  <label>Visibilité<select value={visibility} onChange={e=>setVisibility(e.target.value as 'private'|'shared')}><option value="private">Privé · moi uniquement</option><option value="shared">Partagé · visible par nous deux</option></select><small>Partager permet à votre moitié de consulter l’événement, jamais de le modifier.</small></label>
  <label>Où en est-on ?<select value={status} onChange={e=>setStatus(e.target.value as Appointment['status'])}><option value="scheduled">Planifié · la date est fixée</option><option value="to_book">À prendre · pas encore de date</option>{appointment&&<option value="done">Terminé</option>}</select></label>
  <div className="form-grid"><label>Pour qui ?<select name="person" defaultValue={appointment?.person??active}><option value={-1}>Nous deux</option>{names.map((n,i)=><option key={i} value={i}>{n}</option>)}</select></label><label>Catégorie<select name="category" defaultValue={appointment?.category||'medical'}>{(appointment?.source?Object.entries(appointmentCategories):editableCategories).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>
  {status==='to_book'?<label>À prendre avant le <span className="optional">(facultatif)</span><input type="date" value={bookBy} onChange={e=>setBookBy(e.target.value)}/><small>Une date limite pour penser à appeler. Ce n’est pas la date du rendez-vous.</small></label>:<div className="form-grid"><label>Date<input type="date" value={date} required onChange={e=>setDate(e.target.value)}/></label><label>Heure <span className="optional">(facultatif)</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div>}
  {status!=='to_book'&&<><label>Date de fin <span className="optional">(facultatif · voyage, absence…)</span><input type="date" min={date} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label>Répétition<select value={recurrence} onChange={e=>setRecurrence(e.target.value as NonNullable<Appointment['recurrence']>)}><option value="none">Ne pas répéter</option><option value="weekly">Chaque semaine</option><option value="monthly">Chaque mois</option><option value="yearly">Chaque année · anniversaire…</option></select></label>{recurrence!=='none'&&<><label>Répéter jusqu’au <span className="optional">(facultatif · sans limite sinon)</span><input type="date" min={date} value={repeatUntil} onChange={e=>setRepeatUntil(e.target.value)}/></label><small>Les modifications et la suppression concernent toute la série. Une date inexistante est ramenée au dernier jour du mois (29 février → 28 février).</small></>}</>}
  <label>Lieu ou praticien <span className="optional">(facultatif)</span><input name="location" maxLength={150} defaultValue={appointment?.location||''} placeholder="Cabinet, adresse, nom du médecin…"/></label>
  <label>Notes <span className="optional">(facultatif)</span><textarea name="note" rows={3} maxLength={500} defaultValue={appointment?.note||''} placeholder="Numéro à appeler, documents à apporter…"/></label>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <div className="dialog-actions">{onDelete&&<button type="button" className="icon-button delete-button" disabled={busy} onClick={onDelete} aria-label="Supprimer ce rendez-vous"><Trash2 size={19}/></button>}<button type="submit" className="primary grow" disabled={busy}>{busy?<LoaderCircle size={18} className="spin"/>:<Check size={18}/>} {busy?'Enregistrement…':appointment?'Enregistrer le rendez-vous':status==='to_book'?'Ajouter aux rendez-vous à prendre':'Ajouter au calendrier'}</button></div>
 </form>;
}
