import {DishCard,RecipeRow,MatchSticker,HeroCard,foodEmoji} from '../design-system/runtime';
import {useEffect,useRef,useState} from 'react';
import MealSwipeCard from './meal-swipe-card';
import {useRecipeLibrary} from './use-recipe-library';
import RecipeDiscoveryStatus from './recipe-discovery-status';
import {Heart,X,ChefHat,Clock,BookOpen,LockKeyhole,UtensilsCrossed,ArrowRight} from './icons';
import {recipes,type Recipe} from '../lib/recipes';
import {recipePhotos} from '../lib/recipe-photos';
import {parisDate} from '../lib/life';
import type {Meals} from '../lib/domain';
import LifeDialog from './life-dialog';
const chefs=(names:string[])=>[names[0],names[1],'Vous deux, tabliers complices'];
function RecipePhoto({recipe}:{recipe:Recipe}){const[broken,setBroken]=useState(false);const photo=recipe.image||recipePhotos[recipe.photo];return <div className="recipe-photo">{photo&&!broken?<img src={photo.url} alt={recipe.title+' — photo d’illustration'} loading="lazy" referrerPolicy="no-referrer" onError={()=>setBroken(true)}/>:<span className="recipe-placeholder"><UtensilsCrossed size={72} strokeWidth={1.2} aria-hidden="true"/><small>{broken?'Photo indisponible':'Photo à venir'}</small></span>}<span className="recipe-tag">Sans porc · {recipe.group}</span></div>;}
export default function HouseMeals({meals,names,onVote}:{meals?:Meals;names:string[];onVote:(id:string,like:boolean)=>void}){
 const library=useRecipeLibrary();const catalog=[...recipes,...library.extra];
 const[category,setCategory]=useState('Tous'),[detail,setDetail]=useState<Recipe|null>(null),[mode,setMode]=useState<'swipe'|'matches'|'book'>('swipe');
 const date=meals?.date||parisDate(),votes=meals?.myVotes||{},matches=meals?.matches||[];
 const seed=(id:string)=>[...date+id].reduce((n,c)=>Math.imul(n^c.charCodeAt(0),16777619)>>>0,2166136261);
 const candidates=catalog.filter(r=>!Object.hasOwn(votes,r.id)&&(category==='Tous'||category===r.group)).sort((a,b)=>seed(a.id)-seed(b.id));const current=candidates[0];
 useEffect(()=>{for(const r of candidates.slice(1,3)){const url=r.image?.url||recipePhotos[r.photo]?.url;if(url){const img=new Image();img.referrerPolicy='no-referrer';img.src=url;}}},[current?.id,category]);
 const seenMatches=useRef(new Set(matches.map(m=>m.recipeId)));const[matchArrival,setMatchArrival]=useState<string|null>(null);
 useEffect(()=>{const found=matches.find(m=>!seenMatches.current.has(m.recipeId));for(const m of matches)seenMatches.current.add(m.recipeId);if(found)setMatchArrival(found.recipeId);},[matches]);
 const groups=['Tous','Végétarien','Poulet','Bœuf','Poisson'];
 return <div className="meals-space">{mode!=='book'&&library.error&&<p className="ai-status" role="status">{library.error}</p>}<HeroCard tone="rose" title={<>Ce soir,<br/>on se <em>régale.</em></>} text="À gauche, on passe. À droite, on aime. Et si nos envies se retrouvaient ?" buddy={{shape:"pill",tone:"beurre",mood:"happy"}}/><div className="meal-tabs"><button aria-pressed={mode==='swipe'} className={mode==='swipe'?'selected':''} onClick={()=>setMode('swipe')}>Nos envies du jour</button><button aria-pressed={mode==='matches'} className={mode==='matches'?'selected':''} onClick={()=>setMode('matches')}><Heart size={17} aria-hidden="true"/>Nos matchs ({matches.length})</button><button aria-pressed={mode==='book'} className={mode==='book'?'selected':''} onClick={()=>setMode('book')}>Le carnet ({catalog.length})</button></div>{mode!=='matches'&&<div className="life-filters">{groups.map(g=><button key={g} className={g===category?'selected':''} aria-pressed={g===category} onClick={()=>setCategory(g)}>{g}</button>)}</div>}{mode==='swipe'&&<><p className="meal-privacy"><LockKeyhole size={15}/>Vos choix restent secrets jusqu’au match. Nouvelle partie chaque jour.</p><div className="swipe-stage">{current?<><span className="sr-only" role="status">{current.title}</span><MealSwipeCard recipeId={current.id} title={current.title} onVote={like=>onVote(current.id,like)}><DishCard name={current.title} image={current.image?.url||recipePhotos[current.photo]?.url} emoji={foodEmoji(current.title)} tone="peche" tags={[`${current.minutes} min`,'Pour deux','Sans porc',current.group]} actions={false}/><div className="swipe-recipe-action"><button className="text-link" onClick={()=>setDetail(current)}><BookOpen size={18}/>Voir la recette</button></div></MealSwipeCard><p className="helper-copy">{candidates.length} plat{candidates.length>1?'s':''} à découvrir · Choix définitifs pour aujourd’hui.</p></>:<div className="panel empty"><span className="meal-empty" aria-hidden="true">🥰</span><h2>Vos envies sont dans la boîte !</h2><p>{category==='Tous'?'Revenez voir vos matchs quand votre moitié aura joué. Une nouvelle partie vous attend demain.':'Essayez un autre rayon pour découvrir plus de plats.'}</p><button className="primary" onClick={()=>setMode('matches')}>Voir nos matchs</button></div>}</div>{matches.length>0&&<button className="match-banner" onClick={()=>setMode('matches')} ><Heart size={20} aria-hidden="true"/>{matches.length} envie{matches.length>1?'s':''} en commun ! Découvrir nos matchs <ArrowRight size={18} aria-hidden="true"/></button>}</>}
 {mode==='matches'&&<><div className="meal-match-intro">{matches.length>0&&<MatchSticker subtitle="à table, tous les deux"/>}<h2>Le menu qui nous met d’accord</h2><p>Le hasard a choisi le cuisinier : une chance sur trois chacun, une chance sur trois ensemble. Le tirage est conservé pour ce match.</p><small>Matchs du {new Date(date+'T12:00:00').toLocaleDateString('fr-FR')}</small></div>{matches.length?<div className="recipe-grid">{matches.map(m=>{const r=catalog.find(r=>r.id===m.recipeId);return r?<button className="recipe-tile matched" key={m.recipeId} onClick={()=>setDetail(r)}><RecipePhoto recipe={r}/><div><span className="match-label"><Heart size={16} aria-hidden="true"/>C’est un match !</span><h3>{r.title}</h3><p><ChefHat size={18}/>{chefs(names)[m.chef]}</p><span>Ouvrir la recette →</span></div></button>:null;})}</div>:<div className="panel empty"><span className="meal-empty" aria-hidden="true">💌</span><h3>Le premier match se fait désirer</h3><p>Les choix de votre moitié restent secrets. Un plat apparaîtra ici seulement quand vous l’aimerez tous les deux.</p><button className="primary" onClick={()=>setMode('swipe')}>Jouer à mon tour</button></div>}</>}
 {mode==='book'&&<><RecipeDiscoveryStatus discovery={library.discovery} loading={library.loading} error={library.error} onDiscover={()=>void library.load('discover')} onToggle={enabled=>void library.load('toggle',enabled)}/><div className="recipe-book">{catalog.filter(r=>category==='Tous'||r.group===category).map((r,i)=><RecipeRow key={r.id} name={r.title} time={`${r.minutes} min · Pour deux`} tone={(['peche','menthe','rose','beurre'] as const)[i%4]} onClick={()=>setDetail(r)}/>)}</div></>}
 {matchArrival&&!detail&&<LifeDialog title="Une envie en commun" onClose={()=>setMatchArrival(null)} className="match-dialog"><MatchSticker subtitle="on a le menu"/><h2>{catalog.find(r=>r.id===matchArrival)?.title||'Une nouvelle envie en commun'}</h2><p><ChefHat size={24}/> Aux fourneaux : {chefs(names)[matches.find(m=>m.recipeId===matchArrival)?.chef??2]}</p><button className="primary" onClick={()=>{const recipe=catalog.find(r=>r.id===matchArrival);setMatchArrival(null);if(recipe)setDetail(recipe);else setMode('matches');}}>Voir notre recette</button></LifeDialog>}
 {detail&&<LifeDialog title={detail.title} onClose={()=>setDetail(null)} className="recipe-dialog"><RecipePhoto recipe={detail}/><p className="recipe-summary"><Clock size={18} aria-hidden="true"/>{detail.minutes} min · Pour 2 personnes · Sans porc</p>{matches.some(m=>m.recipeId===detail.id)&&<p className="recipe-chef"><ChefHat size={18} aria-hidden="true"/>Aux fourneaux : {chefs(names)[matches.find(m=>m.recipeId===detail.id)!.chef]}</p>}<h3>Dans le panier</h3><ul className="recipe-ingredients nd-ingredients">{detail.ingredients.map(i=><li key={i}><span aria-hidden="true">{foodEmoji(i)}</span>{i}</li>)}</ul><h3>On se lance ?</h3><ol className="recipe-steps">{detail.steps.map(s=><li key={s}>{s}</li>)}</ol><p className="helper-copy">Adaptez les ingrédients à vos allergies et vérifiez les étiquettes des sauces, bouillons et produits préparés.</p>{detail.generatedAt&&<p className="photo-credit">Recette adaptée par IA pour deux personnes · <a href={detail.sourceUrl} target="_blank" rel="noreferrer">Source : {detail.sourceTitle}</a></p>}{(detail.image||recipePhotos[detail.photo])&&<p className="photo-credit">Photo d’illustration, recadrée à l’affichage : <a href={(detail.image||recipePhotos[detail.photo]).source} target="_blank" rel="noreferrer">{(detail.image||recipePhotos[detail.photo]).author}</a> · <a href={(detail.image||recipePhotos[detail.photo]).licenseUrl} target="_blank" rel="noreferrer">{(detail.image||recipePhotos[detail.photo]).license}</a>. La présentation peut varier.</p>}</LifeDialog>}
 </div>;
}
