import {lazy,Suspense} from 'react';
const HouseMeals=lazy(()=>import('./house-meals'));
import ProfilePhoto,{ProfilesContext,ProfileAvatar} from './profile-photo';
import HomeMoments from './home-moments';
import {HomeOverview,BudgetOverview} from './design-overviews';
import {TabBar,Button} from '../design-system/runtime';
import {ThemePicker} from './theme';
import QuickShopping from './quick-shopping';
import {useMealVotes} from './use-meal-votes';
import {useDialog} from './use-dialog';
import HouseIdeas,{InvitationArrival} from './house-ideas';
import HousePlants from './house-plants';
import {plantCare} from '../lib/life';
import ShoppingArticleForm from './shopping-article-form';
'use client';
import {apiFetch,APP_BASE} from '../lib/api-client';
import {createPortal} from 'react-dom';
import {useState,useEffect,useCallback,useRef,type FormEvent,type ReactNode,type ComponentType} from 'react';
import {Home,Wallet,ShoppingBasket,CheckCheck,Settings,Plus,ArrowUpRight,ArrowRight,ArrowLeftRight,ChevronLeft,ChevronRight,X,Check,Trash2,Pencil,RefreshCw,CloudCheck,CloudOff,Heart,Download,Smartphone,CalendarDays,Search,Receipt,Leaf,Lightbulb,Car,Coffee,Shapes,LockKeyhole,LogOut,LoaderCircle,ChevronDown,Flag,Phone,Bell,MessageCircle,BookOpen} from './icons';
import {balance,centsFromInput,money,today,categories,type Data,type Entry,type Item,type Household,type Appointment} from '../lib/domain';
import HouseCalls from './house-calls';
import HouseNotifications from './house-notifications';
import {deviceId} from '../lib/device';
import HouseCalendar,{CalendarSummary,AppointmentForm,type OpenAppointment} from './house-calendar';
import HouseShopping from './house-shopping';
import HouseChat from './house-chat';
import {weekStart} from '../lib/shopping';
type Tab='meals'|'ideas'|'plants'|'chat'|'calls'|'notifications'|'home'|'expenses'|'shopping'|'tasks'|'calendar'|'settings';
type Modal={kind:'quick-add'|'expense'|'settlement'|'shopping'|'task'|'delete'|'install'|'appointment';entry?:Entry;item?:Item;appointment?:Appointment;initialWeek?:string;initialDate?:string;initialStatus?:'to_book'|'scheduled'};
const nav=[{id:'home',label:'Chez nous',icon:Home},{id:'expenses',label:'Budget',icon:Wallet},{id:'shopping',label:'Courses',icon:ShoppingBasket},{id:'calendar',label:'Calendrier',icon:CalendarDays},{id:'tasks',label:'À faire',icon:CheckCheck},{id:'calls',label:'Appels',icon:Phone},{id:'notifications',label:'Nouveautés',icon:Bell},{id:'meals',label:'À table !',icon:Coffee},{id:'ideas',label:'Nos idées',icon:Heart},{id:'plants',label:'Nos plantes',icon:Leaf},{id:'chat',label:'Discussion',icon:MessageCircle},{id:'settings',label:'Notre espace',icon:Settings}] as const;
const catIcons=[ShoppingBasket,Home,Lightbulb,Coffee,Car,Shapes];
const dateLabel=(date:string)=>new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date(date+'T12:00:00'));
const monthLabel=(month:string)=>new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(month+'-15T12:00:00'));
function Avatar({name,second=false,small=false}:{name:string;second?:boolean;small?:boolean}){return <ProfileAvatar member={second?1:0} name={name} className={`avatar ${second?'peach':''} ${small?'small':''}`}/>;}
function Empty({icon:Icon,title,children,action}:{icon:ComponentType<import('lucide-react').LucideProps>;title:string;children:ReactNode;action?:ReactNode}){return <div className="empty"><span className="empty-icon"><Icon size={27} strokeWidth={2}/></span><h3>{title}</h3><p>{children}</p>{action}</div>;}
function Dialog({title,close,children,busy}:{title:string;close:()=>void;children:ReactNode;busy:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useDialog(ref);
 return <dialog aria-labelledby="dialog-title" ref={ref} onCancel={e=>{e.preventDefault();if(!busy)close();}} onClick={e=>{if(e.target===ref.current&&!busy)close();}}><div className="dialog-inner"><div className="dialog-head"><div><h2 id="dialog-title">{title}</h2></div><button type="button" className="icon-button" onClick={close} disabled={busy} aria-label="Fermer"><X/></button></div>{children}</div></dialog>;
}
export default function HouseApp(){
 const[shoppingWeek,setShoppingWeek]=useState(weekStart);const[quickShopping,setQuickShopping]=useState(false);const[createTarget,setCreateTarget]=useState('');
 const[data,setData]=useState<Data|null>(null);const[tab,setTab]=useState<Tab>('home');const[modal,setModal]=useState<Modal|null>(null);
 const[active,setActive]=useState(0);const[month,setMonth]=useState(today().slice(0,7));const[search,setSearch]=useState('');const[category,setCategory]=useState('Toutes');const[taskFilter,setTaskFilter]=useState('all');
 const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(true);const[online,setOnline]=useState(true);const[error,setError]=useState('');const[formError,setFormError]=useState('');const[notice,setNotice]=useState('');const[synced,setSynced]=useState(false);const[needsAuth,setNeedsAuth]=useState(false);
 const sequence=useRef(0);const mutating=useRef(false);const submitting=useRef(false);const toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const toast=(message:string)=>{setNotice(message);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setNotice(''),4200);};
 const refresh=useCallback(async(quiet=false)=>{
  if(mutating.current)return false;const requestNumber=++sequence.current;
  try{const response=await apiFetch('/api/household',{cache:'no-store'});if(response.status===401){setNeedsAuth(true);throw new Error('Votre session a expiré. Reconnectez-vous.');}
   if(!response.ok)throw new Error('La synchronisation est interrompue. Réessayez dans un instant.');
   const result=await response.json() as Data;if(requestNumber===sequence.current){setData(result);setActive(result.member??0);setSynced(true);setError('');setNeedsAuth(false);}return true;
  }catch(e){if(requestNumber===sequence.current){setSynced(false);if(!quiet)setError(e instanceof Error?e.message:'Connexion indisponible.');}return false;}
  finally{if(requestNumber===sequence.current)setLoading(false);}
 },[]);
 useEffect(()=>{
  const view=new URLSearchParams(location.search).get('view');if(view&&nav.some(n=>n.id===view))setTab(view as Tab);
  setOnline(navigator.onLine);refresh();
  const wake=()=>{setOnline(navigator.onLine);if(document.visibilityState==='visible')refresh(true);};
  const offline=()=>{setOnline(false);setSynced(false);};
  const timer=setInterval(()=>{if(document.visibilityState==='visible'&&navigator.onLine)refresh(true);},10000);
  addEventListener('focus',wake);addEventListener('online',wake);addEventListener('offline',offline);document.addEventListener('visibilitychange',wake);
  return()=>{clearInterval(timer);removeEventListener('focus',wake);removeEventListener('online',wake);removeEventListener('offline',offline);document.removeEventListener('visibilitychange',wake);};
 },[refresh]);
 const mealVotes=useMealVotes(active,data?.meals);
 const contentRef=useRef<HTMLElement>(null);
 useEffect(()=>{const node=contentRef.current;node?.closest('.workspace')?.scrollTo({top:0,behavior:'instant'});if(node&&!matchMedia('(prefers-reduced-motion: reduce)').matches)node.animate([{opacity:.6,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:170,easing:'ease-out'});document.title=(nav.find(n=>n.id===tab)?.label||'Notre maison')+' · Nous deux';},[tab]);
 const canEdit=(record?:{owner?:number|null})=>!record||record.owner===active;
 const record=modal?.entry||modal?.item||modal?.appointment;const readOnly=!!record&&!canEdit(record);
 const open=(m:Modal)=>{setFormError('');setModal(m);};
 async function save(action:string,payload:unknown,message='Enregistré dans votre maison.'){
  if(submitting.current)return false;
  if(!navigator.onLine){setFormError('Vous êtes hors ligne. Reconnectez-vous pour enregistrer.');toast('Connexion nécessaire pour enregistrer.');return false;}
  submitting.current=true;mutating.current=true;++sequence.current;setBusy(true);setFormError('');
  try{const response=await apiFetch('/api/household',{method:'POST',headers:{'Content-Type':'application/json','x-adeux-member':String(active),'x-adeux-device':deviceId()},body:JSON.stringify({action,payload})});
   if(response.status===401)setNeedsAuth(true);
   if(!response.ok){const result=await response.json().catch(()=>({})) as {error?:string};if(response.status===409){mutating.current=false;await refresh();}throw new Error(result.error||'Enregistrement impossible. Réessayez.');}
   mutating.current=false;const fresh=await refresh();setModal(null);toast(fresh?message:'Enregistré. Actualisez pour charger la dernière version.');return true;
  }catch(e){const message=e instanceof Error?e.message:'Enregistrement impossible.';setFormError(message);toast(message);return false;}
  finally{mutating.current=false;submitting.current=false;setBusy(false);}
 }
 const home=data?.household;const names=[home?.first||'Vous',home?.second||'Votre moitié'];const all=data?.entries||[];const lists=data?.items||[];
 const appointments=data?.appointments||[];const ideas=data?.ideas||[];const plants=data?.plants||[];const waitingIdeas=ideas.filter(i=>i.owner!==active&&i.status==='pending');const thirstyPlants=plants.filter(p=>plantCare(p).some(c=>c.overdue>=0));
 const openAppointment=(options:OpenAppointment)=>open({kind:'appointment',...options,appointment:options.appointment?.original||options.appointment});
 const credit=balance(all);
 const monthly=all.filter(e=>e.kind==='expense'&&e.date.startsWith(month));const total=monthly.reduce((s,e)=>s+e.cents,0);
 const paid=[0,1].map(n=>monthly.filter(e=>e.member===n).reduce((s,e)=>s+e.cents,0));
 const shopping=lists.filter(i=>i.kind==='shopping');const tasks=lists.filter(i=>i.kind==='task');const todo=tasks.filter(i=>!i.done);const toBuy=shopping.filter(i=>!i.done&&i.weekStart===weekStart());
 const visible=all.filter(e=>e.date.startsWith(month)&&(category==='Toutes'||e.category===category&&e.kind==='expense')&&`${e.title} ${e.note} ${names[e.member]}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const moveMonth=(direction:number)=>{const d=new Date(month+'-15T12:00:00');d.setMonth(d.getMonth()+direction);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`);};
 const monthPicker=<div className="month-picker"><button className="icon-button" aria-label="Mois précédent" onClick={()=>moveMonth(-1)}><ChevronLeft size={18}/></button><label className="month-label">{monthLabel(month)}<input aria-label="Choisir le mois" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label><button className="icon-button" aria-label="Mois suivant" onClick={()=>moveMonth(1)}><ChevronRight size={18}/></button></div>;
 const entryRow=(e:Entry)=>{const Icon=e.kind==='settlement'?ArrowLeftRight:catIcons[categories.indexOf(e.category)]||Receipt;return <button className="entry-row" key={e.id} onClick={()=>open({kind:e.kind,entry:e})}><span className={`category-icon cat-${categories.indexOf(e.category)}`}><Icon size={21} strokeWidth={2}/></span><span className="row-description"><strong>{e.title}</strong><span>{e.kind==='settlement'?`${names[e.member]} → ${names[1-e.member]}`:`Payé par ${names[e.member]}`}<span className="dot">·</span>{dateLabel(e.date)}</span></span><span className="row-money"><strong>{money(e.cents)}</strong><small>{e.kind==='settlement'?'Remboursement':'50 / 50'}</small></span><ChevronRight className="row-chevron" size={16}/></button>;};
 const toggleItem=(item:Item)=>save('item',{...item,done:!item.done},item.done?'Remis dans la liste.':item.kind==='shopping'?'C’est dans le panier !':'Une chose de faite !');
 const itemRow=(item:Item)=> <div key={item.id} className={`nd-todo item-row ${item.done?'done':''}`}><button className="checkbox" disabled={busy||!online||!canEdit(item)} onClick={()=>toggleItem(item)} aria-label={`${item.done?'Rouvrir':'Terminer'} : ${item.title}`} aria-pressed={item.done}>{item.done&&<Check size={17}/>}</button><button className="item-detail" onClick={()=>open({kind:item.kind,item})}><strong>{item.title}</strong><span>{item.quantity&&<span>{item.quantity}</span>}{item.due&&<span className={!item.done&&item.due<today()?'overdue':''}><CalendarDays size={12}/>{dateLabel(item.due)}</span>}{item.priority===1&&!item.done&&<span className="priority"><Flag size={11}/> Priorité</span>}</span></button>{item.assignee>=0&&<span title={names[item.assignee]}><Avatar name={names[item.assignee]} second={item.assignee===1} small/></span>}<button className="icon-button subtle" aria-label={`${canEdit(item)?'Modifier':'Voir'} ${item.title}`} onClick={()=>open({kind:item.kind,item})}>{canEdit(item)?<Pencil size={15}/>:<LockKeyhole size={15}/>}</button></div>;
 const exportCsv=()=>{const safe=(v:unknown)=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const rows=[['Date','Type','Intitulé','Montant EUR','Personne','Catégorie','Note'],...all.map(e=>[e.date,e.kind==='expense'?'Dépense':'Remboursement',e.title,(e.cents/100).toFixed(2).replace('.',','),names[e.member],e.category,e.note])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`a-deux-depenses-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Votre historique a été exporté.');};
 return <ProfilesContext.Provider value={data?.profiles||{}}><a href="#main-content" className="skip-link">Aller au contenu</a><div className={`app-shell ${tab==='chat'?'chat-view':''}`}>
  <div className="workspace"><header className="topbar"><a className="brand" href={APP_BASE} aria-label="Nous deux, accueil" onClick={e=>{e.preventDefault();setTab('home');}}><img className="brand-mark" src={APP_BASE+'logos/nous-deux-symbole.svg'} alt=""/><img className="brand-mark dark-logo" src={APP_BASE+'logos/nous-deux-symbole-blanc.svg'} alt=""/><span>Nous deux</span></a><div className="topbar-right"><button className={`sync-status ${!synced?'unsynced':''}`} onClick={()=>refresh()} aria-label="Actualiser les données">{synced?<CloudCheck size={20}/>:<CloudOff size={20}/>}<span>{!online?'Hors ligne':synced?'À jour':'Actualiser'}</span></button><button className="icon-button" onClick={()=>setTab('notifications')} aria-label="Nos notifications"><Bell/></button>{home&&<button className="profile-picker" onClick={()=>setTab('settings')} aria-label={`Mon espace, ${names[active]}`}><Avatar name={names[active]} second={active===1}/></button>}</div></header>
  <main id="main-content" tabIndex={-1} ref={contentRef}>
   {(mealVotes.pending>0||mealVotes.error)&&<div className="meal-sync-status" role="status"><RefreshCw size={16}/><span>{mealVotes.error||`${mealVotes.pending} choix en cours de synchronisation…`}</span>{mealVotes.error&&<button className="text-link" onClick={mealVotes.retry}>Réessayer</button>}</div>}
   {(!online||error)&&<div className="banner" role="alert"><CloudOff size={18}/><span>{!online?'Hors ligne · reconnectez-vous pour enregistrer et synchroniser.':error}</span>{needsAuth?<a href={APP_BASE} target="_top">Se reconnecter</a>:<button onClick={()=>refresh()}>Réessayer</button>}</div>}
   {loading&&!data?<div className="loading"><LoaderCircle className="spin"/><h2>On ouvre votre maison…</h2></div>:!data?<Empty icon={CloudOff} title="Votre maison attend votre connexion">{needsAuth?<a className="primary" href={APP_BASE} target="_top">Se connecter</a>:<button className="primary" onClick={()=>refresh()}>Réessayer</button>}</Empty>:!home?<div className="onboarding"><div className="welcome-art"><div className="art-house"><Heart size={45} strokeWidth={1.2}/></div><span className="floating-chip">50 / 50</span><span className="floating-check"><Check size={24}/></span></div><span className="eyebrow">Bienvenue chez nous</span><h1>Le quotidien est plus<br/>doux <em>à deux.</em></h1><p>Les comptes au clair, les courses à portée de main<br className="desktop-break"/> et les petites choses à faire, ensemble.</p><SettingsForm key="onboard" busy={busy} error={formError} onSave={h=>save('household',h,'Bienvenue dans votre maison !')} initial={null}/><p className="privacy-note"><LockKeyhole size={14}/> Vos données restent dans votre espace privé.<br/>Utilisez votre compte personnel sur vos différents appareils.</p></div>:<>
   {tab!=='chat'&&<div className="page-heading"><div><h1>{tab==='home'?`${new Date().getHours()>=18?'Bonsoir':'Bonjour'}, ${names[active]} !`:tab==='expenses'?'Notre argent':tab==='shopping'?'Les courses':tab==='tasks'?'Nos missions':tab==='calendar'?'Notre agenda':tab==='meals'?'À table':tab==='ideas'?'Nos idées':tab==='plants'?'Notre jardin':tab==='calls'?'On s’appelle ?':tab==='notifications'?'Nos nouvelles':'Notre espace'}</h1>{tab==='home'&&<p>{new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p>}</div>{tab==='expenses'?<Button icon="plus" onClick={()=>open({kind:'expense'})}>Ajouter une dépense</Button>:tab==='tasks'?<Button icon="plus" onClick={()=>open({kind:'task'})}>Ajouter une tâche</Button>:tab==='calendar'?<Button icon="plus" onClick={()=>openAppointment({initialStatus:'scheduled',initialDate:today()})}>Ajouter un événement</Button>:null}</div>}
   {tab==='home'&&<HomeOverview counts={{shopping:toBuy.length,tasks:todo.length,matches:data.meals?.matches.length||0,ideas:waitingIdeas.length,plants:plants.length}} onNavigate={t=>setTab(t as Tab)}><CalendarSummary appointments={appointments} names={names} onOpen={openAppointment} onCalendar={()=>setTab('calendar')}/><HomeMoments plants={plants} appointments={appointments} onGarden={()=>setTab('plants')} onCalendar={()=>setTab('calendar')}/>{todo.length>0&&<section className="panel"><div className="section-title"><h2>Nos petites missions</h2><button className="text-link" onClick={()=>setTab('tasks')}>Tout voir</button></div>{todo.slice(0,3).map(itemRow)}</section>}</HomeOverview>}
   {tab==='expenses'&&<><BudgetOverview entries={monthly} names={names} total={total} paid={paid} credit={credit} budget={home.budget} monthPicker={monthPicker} onSettle={()=>open({kind:'settlement'})} onSettings={()=>setTab('settings')}/><section className="panel expense-panel"><div className="section-title"><h2>Notre historique</h2><div className="history-actions"><button className="secondary" onClick={()=>open({kind:'settlement'})}><ArrowLeftRight size={18}/>Remboursement</button><button className="icon-button" onClick={exportCsv} aria-label="Exporter tout l’historique en CSV"><Download size={24}/></button></div></div><div className="filters"><label className="search-field"><Search size={24}/><input placeholder="Rechercher une dépense…" aria-label="Rechercher une dépense" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filtrer par catégorie" value={category} onChange={e=>setCategory(e.target.value)}><option>Toutes</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>{visible.length?visible.map(entryRow):<Empty icon={Receipt} title={search||category!=='Toutes'?'Aucun résultat':'Un mois encore tout léger'}>{search||category!=='Toutes'?'Essaie une autre recherche.':'Nos dépenses et remboursements apparaîtront ici.'}</Empty>}<p className="panel-footnote">Le solde tient compte de tout notre historique, remboursements inclus.</p></section></>}
   {tab==='tasks'&&(()=>{const source=tasks;const filtered=source.filter(i=>taskFilter!=='mine'||i.assignee===active);const pending=filtered.filter(i=>!i.done).sort((a,b)=>b.priority-a.priority||(a.due||'9999').localeCompare(b.due||'9999'));const done=filtered.filter(i=>i.done);return <div className="lists-layout"><section className="panel list-panel"><div className="section-title"><h2>{'À faire'}<span className="count-badge">{pending.length}</span></h2>{tab==='tasks'&&<div className="segmented compact"><button className={taskFilter==='all'?'selected':''} onClick={()=>setTaskFilter('all')}>Ensemble</button><button className={taskFilter==='mine'?'selected':''} onClick={()=>setTaskFilter('mine')}>Pour moi</button></div>}</div>{pending.length?pending.map(itemRow):<Empty icon={CheckCheck} title={source.length?'Tout est coché !':'On commence par quoi ?'}>{source.length?'Profitez, vous avez fait le tour de la liste.':'Une lessive, un rendez-vous à prendre, une plante à arroser… Notez-le ici.'}</Empty>}<button className="add-row" onClick={()=>open({kind:'task'})}><Plus size={19}/>{'Ajouter une tâche'}</button>{done.length>0&&<details className="completed"><summary>{'Terminé'} · {done.length}<ChevronDown size={16}/></summary>{done.map(itemRow)}</details>}</section><aside className="list-aside"><span className="note-icon">{<CheckCheck size={30}/>}</span><h2>{'Chacun sa petite part.'}</h2><p>{'Attribuez les tâches, ajoutez une date et avancez à votre rythme.'}</p><span className="aside-caption">{'Les tâches terminées restent dans l’historique.'}</span></aside></div>;})()}
   {tab==='shopping'&&<HouseShopping items={shopping} templates={data.templates||[]} active={active} names={names} week={shoppingWeek} setWeek={setShoppingWeek} busy={busy} online={online} save={save} onEdit={item=>open({kind:'shopping',item})} onExpense={()=>open({kind:'expense'})}/>}
   {tab==='ideas'&&<HouseIdeas create={createTarget==='ideas'} onCreated={()=>setCreateTarget('')} ideas={ideas} active={active} names={names} busy={busy} error={formError} save={save}/>}
   {tab==='plants'&&<HousePlants create={createTarget==='plants'} onCreated={()=>setCreateTarget('')} plants={plants} active={active} names={names} busy={busy} error={formError} save={save} onNotifications={()=>setTab('notifications')}/>}
   {tab==='meals'&&<Suspense fallback={<p role="status">On ouvre le carnet gourmand…</p>}><HouseMeals active={active} create={createTarget==='recipe'} openPlans={createTarget==='menu'} onCreated={()=>setCreateTarget('')} meals={mealVotes.meals} names={names} onVote={mealVotes.vote}/></Suspense>}
   {tab==='chat'&&<HouseChat active={active} names={names}/>}
   <HouseCalls active={active} names={names} expanded={tab==='calls'} onOpen={()=>setTab('calls')}/>
   {tab==='notifications'&&<HouseNotifications active={active} names={names} onNavigate={t=>{if(nav.some(n=>n.id===t))setTab(t as Tab);}}/>}
   {tab==='calendar'&&<HouseCalendar active={active} appointments={appointments} names={names} onOpen={openAppointment}/>}
   {tab==='settings'&&<div className="settings-grid"><section className="panel settings-panel"><h2>Les deux de la maison</h2><ThemePicker/><ProfilePhoto member={active} name={names[active]} busy={busy} save={save}/><SettingsForm active={active} key={home.version} initial={home} busy={busy} error={formError} onSave={h=>save('household',h,'Votre espace a été mis à jour.')}/></section><div className="settings-right"><section className="panel settings-panel"><span className="settings-icon"><Smartphone size={23}/></span><h2>Toujours à portée de main</h2><button className="text-link" onClick={()=>setTab('notifications')}><Bell size={17}/>Régler mes notifications</button><p>Ouvrez ce lien sur vos autres appareils et connectez-vous avec votre compte personnel. Vos dépenses et vos listes sont communes.</p><div className="device-profile"><span>Connecté·e en tant que <strong>{names[active]}</strong></span><LockKeyhole size={16}/></div><button className="secondary wide" onClick={()=>open({kind:'install'})}><Plus size={17}/>Ajouter à l’écran d’accueil</button><button className="text-link settings-link" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+APP_BASE);toast('Lien de la maison copié.');}catch{toast('Copiez le lien dans la barre d’adresse de votre navigateur.');}}}>Copier le lien de notre maison <ArrowUpRight size={15}/></button></section><section className="panel settings-panel"><h2>Vos données, au clair</h2><p>Les dépenses sont partagées à 50/50. Pour un centime indivisible, la part de {names[0]} est arrondie au centime supérieur.</p><button className="secondary wide" onClick={exportCsv}><Download size={17}/>Exporter toutes les dépenses</button><button className="text-link settings-link" onClick={async()=>{const r=await apiFetch("/api/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"logout"})});if(r.ok)location.replace(APP_BASE);else toast("Déconnexion impossible. Réessayez.");}}><LogOut size={16}/>Déconnecter cet appareil</button></section></div></div>}
   </>}
  </main></div>
  {createPortal(<div className="app-tabbar"><TabBar active={tab==='calendar'?'agenda':tab==='expenses'?'argent':tab==='chat'?'nous':'home'} onChange={t=>setTab(({home:'home',agenda:'calendar',argent:'expenses',nous:'chat'} as Record<string,Tab>)[t])} onAdd={()=>open({kind:'quick-add'})}/></div>,document.body)}
  {quickShopping&&<QuickShopping week={shoppingWeek} items={shopping.filter(i=>i.weekStart===shoppingWeek)} busy={busy} save={save} onClose={()=>setQuickShopping(false)}/>}

  {home&&<InvitationArrival error={formError} enabled={!modal&&!quickShopping&&tab!=='ideas'&&tab!=='plants'&&tab!=='meals'} ideas={ideas} active={active} names={names} busy={busy} save={save} onOpen={()=>setTab('ideas')}/>}
  {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
  {modal&&<Dialog busy={busy} close={()=>{setModal(null);setFormError('');}} title={modal.kind==='quick-add'?'On ajoute quoi ?':readOnly?'Détail partagé':modal.kind==='appointment'?(modal.appointment?'Notre rendez-vous':'Un nouveau rendez-vous'):modal.kind==='install'?'Votre raccourci à deux':modal.kind==='delete'?'Supprimer cet élément ?':modal.kind==='expense'?(modal.entry?'Modifier la dépense':'Une nouvelle dépense'):modal.kind==='settlement'?(modal.entry?'Modifier le remboursement':'Noter un remboursement'):modal.kind==='shopping'?(modal.item?'Modifier l’article':'À mettre dans le panier'):(modal.item?'Modifier la tâche':'Une petite chose à faire')}>
   {modal.kind==='quick-add'&&<div className="quick-add-grid"><Button variant="secondary" icon="calendar" onClick={()=>openAppointment({initialStatus:'scheduled',initialDate:today()})}>Un événement</Button><Button variant="secondary" icon="wallet" onClick={()=>open({kind:'expense'})}>Une dépense</Button><Button variant="secondary" icon="cart" onClick={()=>{setModal(null);setQuickShopping(true);}}>Des courses</Button><Button variant="secondary" icon="check" onClick={()=>open({kind:'task'})}>Une mission</Button>{([['ideas','Une idée',Heart],['plants','Une plante',Leaf],['recipe','Une recette',BookOpen],['menu','Un menu',CalendarDays]] as const).map(([target,label,Icon])=><Button key={target} variant="secondary" onClick={()=>{setModal(null);setTab(target==='ideas'?'ideas':target==='plants'?'plants':'meals');setCreateTarget(target);}}><Icon size={24}/>{label}</Button>)}</div>}
   {readOnly&&<p className="read-only-note">{modal.appointment?.source?'Date de référence · calendrier prérempli.':record?.owner===0||record?.owner===1?`Publié par ${names[record.owner]}. Seule cette personne peut le modifier.`:'Élément antérieur aux comptes personnels : auteur inconnu, conservé en lecture seule.'}</p>}{modal.appointment?.source&&<a className="text-link" href={modal.appointment.source} target="_blank" rel="noopener noreferrer">Consulter la source de cette date ↗</a>}{!['quick-add','install'].includes(modal.kind)&&<fieldset disabled={readOnly} className={readOnly?'record-fields read-only':'record-fields'}>
   {(modal.kind==='expense'||modal.kind==='settlement')&&<EntryForm key={modal.entry?.id||modal.kind} entry={modal.entry} kind={modal.kind} names={names} member={active} initialCents={modal.kind==='settlement'?Math.abs(credit):0} busy={busy} error={formError} onSave={p=>save('entry',p,modal.kind==='settlement'?'Remboursement enregistré.':'Dépense partagée à 50/50.')} onDelete={modal.entry?()=>open({kind:'delete',entry:modal.entry}):undefined}/>}
   {modal.kind==='shopping'&&<ShoppingArticleForm key={modal.item?.id||'new-shopping'} item={modal.item} week={shoppingWeek} names={names} busy={busy} error={formError} onSave={p=>save('item',p)} onDelete={modal.item?()=>open({kind:'delete',item:modal.item}):undefined}/>}
   {modal.kind==='task'&&<ItemForm key={modal.item?.id||modal.kind} item={modal.item} initialWeek={shoppingWeek} kind={modal.kind} names={names} busy={busy} error={formError} onSave={p=>save('item',p)} onDelete={modal.item?()=>open({kind:'delete',item:modal.item}):undefined}/>}
   {modal.kind==='appointment'&&<AppointmentForm active={active} appointment={modal.appointment} initialDate={modal.initialDate} initialStatus={modal.initialStatus} names={names} busy={busy} error={formError} onSave={p=>save('appointment',p,'Rendez-vous enregistré dans votre calendrier.')} onDelete={modal.appointment?()=>open({kind:'delete',appointment:modal.appointment}):undefined}/>}
   {modal.kind==='delete'&&<><p className="dialog-description">« {modal.entry?.title||modal.item?.title||modal.appointment?.title} » sera supprimé sur tous vos appareils.{modal.entry&&' Le solde sera recalculé.'}</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="dialog-actions"><button className="secondary" disabled={busy} onClick={()=>setModal(null)}>Annuler</button><button className="danger" disabled={busy} onClick={()=>save(modal.appointment?'delete-appointment':modal.entry?'delete-entry':'delete-item',modal.appointment||modal.entry||modal.item,'Élément supprimé.')}><Trash2 size={17}/>{busy?'Suppression…':'Supprimer'}</button></div></>}
   </fieldset>}{modal.kind==='install'&&<div className="install-help"><div className="install-icon"><img src={APP_BASE+'favicon.svg'} width="72" height="72" alt="Nous deux"/></div><h3>Sur votre iPhone ou iPad</h3><ol><li>Ouvrez cette application dans <strong>Safari</strong>.</li><li>Touchez le bouton <strong>Partager</strong>.</li><li>Choisissez <strong>Sur l’écran d’accueil</strong>, puis <strong>Ajouter</strong>.</li></ol><p>Sur Android, ouvrez le menu de Chrome puis « Ajouter à l’écran d’accueil ».</p><div className="info-box"><LockKeyhole size={19}/><span>Entrez votre mot de passe personnel sur chaque appareil. Une connexion internet est nécessaire.</span></div></div>}
  </Dialog>}
 </div></ProfilesContext.Provider>;
}
function SettingsForm({initial,busy,error,onSave,active=0}:{active?:number;initial:Household|null;busy:boolean;error:string;onSave:(h:Household)=>Promise<boolean>}){
 const[localError,setLocalError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLocalError('');const f=new FormData(e.currentTarget);try{const first=active===1&&initial?initial.first:String(f.get('first')).trim(),second=active===0&&initial?initial.second:String(f.get('second')).trim();if(first.toLocaleLowerCase()===second.toLocaleLowerCase())throw new Error('Choisissez deux prénoms distincts.');await onSave({first,second,name:String(f.get('name')||'Notre maison').trim(),budget:centsFromInput(String(f.get('budget')||'0')),version:initial?.version||0});}catch(e){setLocalError(e instanceof Error?e.message:'Vérifiez les champs.');}}
 return <form onSubmit={submit} className="form"><div className="form-grid"><label>Votre prénom<input disabled={!!initial&&active!==0} name="first" placeholder="Votre prénom" maxLength={24} required defaultValue={initial?.first||'Abdellah'}/></label><label>Son prénom<input disabled={!!initial&&active!==1} name="second" placeholder="Le prénom de votre moitié" maxLength={24} required defaultValue={initial?.second||''}/></label></div>{initial&&<><label>Le nom de votre espace<input name="name" maxLength={50} defaultValue={initial.name} required/></label><label>Budget commun mensuel (facultatif)<div className="amount-input"><input name="budget" inputMode="decimal" placeholder="0,00" defaultValue={initial.budget?String(initial.budget/100):''}/><span>€</span></div><small>Laissez vide si vous ne souhaitez pas définir de budget.</small></label></>}{(localError||error)&&<p className="form-error" role="alert">{localError||error}</p>}<button className="primary wide" disabled={busy} type="submit">{busy?<LoaderCircle size={18} className="spin"/>:initial?<Check size={18}/>:<ArrowRight size={18}/>} {initial?'Enregistrer les changements':'Entrer dans notre maison'}</button></form>;
}
function EntryForm({entry,kind,names,member,initialCents,busy,error,onSave,onDelete}:{entry?:Entry;kind:'expense'|'settlement';names:string[];member:number;initialCents:number;busy:boolean;error:string;onSave:(v:unknown)=>Promise<boolean>;onDelete?:()=>void}){
 const[id]=useState(()=>entry?.id||crypto.randomUUID());const[payer,setPayer]=useState(entry?.member??member);const[amount,setAmount]=useState(entry?String(entry.cents/100):initialCents?String(initialCents/100):'');const[localError,setLocalError]=useState('');const isExpense=kind==='expense';
 let cents=0;try{cents=centsFromInput(amount||'0');}catch{}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLocalError('');const f=new FormData(e.currentTarget);try{const value=centsFromInput(amount);if(value<=0)throw new Error('Le montant doit être supérieur à zéro.');await onSave({id,version:entry?.version||0,kind,title:isExpense?String(f.get('title')).trim():'Remboursement',cents:value,member:payer,category:String(f.get('category')||'Autre'),date:String(f.get('date')),note:String(f.get('note')||'')});}catch(e){setLocalError(e instanceof Error?e.message:'Vérifiez le montant.');}}
 return <form className="form" onSubmit={submit}>{isExpense&&<label>Pour quoi ?<input autoFocus name="title" required maxLength={100} defaultValue={entry?.title||''} placeholder="Les courses de la semaine"/></label>}<label>Montant<div className="amount-input large"><input autoFocus={!isExpense} aria-label="Montant en euros" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" required maxLength={12}/><span>€</span></div></label><fieldset><legend>{isExpense?'Qui a payé ?':'Qui a remboursé ?'}</legend><div className="person-options">{names.map((n,i)=><button type="button" key={i} className={payer===i?'selected':''} disabled={i!==member} onClick={()=>setPayer(i)} aria-pressed={payer===i}><Avatar name={n} second={i===1} small/>{n}{payer===i&&<Check size={15}/>}</button>)}</div></fieldset><div className="form-grid">{isExpense&&<label>Catégorie<select name="category" defaultValue={entry?.category||'Courses'}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>}<label>Date<input name="date" type="date" defaultValue={entry?.date||today()} required/></label></div>{isExpense?<div className="split-preview"><span><ArrowLeftRight size={16}/>Répartition 50 / 50</span><div><span>{names[0]}<strong>{money(Math.ceil(cents/2))}</strong></span><span>{names[1]}<strong>{money(Math.floor(cents/2))}</strong></span></div></div>:<div className="info-box"><ArrowLeftRight size={19}/><span>{names[payer]} a versé <strong>{money(cents)}</strong> à {names[1-payer]}. Ceci enregistre un remboursement déjà effectué, sans transférer d’argent.</span></div>}<label>Une petite note <span className="optional">(facultatif)</span><textarea name="note" rows={2} maxLength={300} defaultValue={entry?.note||''} placeholder={isExpense?'Un détail à garder…':'Virement, espèces…'}/></label>{(error||localError)&&<p role="alert" className="form-error">{localError||error}</p>}<div className="dialog-actions">{onDelete&&<button className="icon-button delete-button" type="button" onClick={onDelete} disabled={busy} aria-label="Supprimer"><Trash2 size={19}/></button>}<button className="primary grow" disabled={busy} type="submit">{busy?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>} {busy?'Enregistrement…':entry?'Enregistrer les modifications':isExpense?'Ajouter la dépense':'Enregistrer le remboursement'}</button></div></form>;
}
function ItemForm({item,initialWeek,kind,names,busy,error,onSave,onDelete}:{item?:Item;initialWeek?:string;kind:'shopping'|'task';names:string[];busy:boolean;error:string;onSave:(v:unknown)=>Promise<boolean>;onDelete?:()=>void}){
 const[id]=useState(()=>item?.id||crypto.randomUUID());async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await onSave({id,weekStart:item?.weekStart||initialWeek,version:item?.version||0,kind,title:String(f.get('title')).trim(),quantity:String(f.get('quantity')||''),assignee:Number(f.get('assignee')),due:String(f.get('due')||''),priority:f.get('priority')?1:0,done:item?.done||false});}
 return <form className="form" onSubmit={submit}><label>{kind==='shopping'?'Qu’est-ce qu’on achète ?':'Qu’est-ce qu’on fait ?'}<input autoFocus name="title" required maxLength={100} defaultValue={item?.title||''} placeholder={kind==='shopping'?'Des tomates, du pain…':'Arroser les plantes…'}/></label>{kind==='shopping'&&<label>Quantité ou précision<input name="quantity" maxLength={50} defaultValue={item?.quantity||''} placeholder="1 kg, 2 paquets…"/></label>}<label>{kind==='shopping'?'Qui s’en occupe ?':'Pour qui ?'}<select name="assignee" defaultValue={item?.assignee??-1}><option value={-1}>L’un de nous</option>{names.map((n,i)=><option value={i} key={i}>{n}</option>)}</select></label>{kind==='task'&&<><label>Pour quand ? <span className="optional">(facultatif)</span><input name="due" type="date" defaultValue={item?.due||''}/></label><label className="check-label"><input name="priority" type="checkbox" defaultChecked={item?.priority===1}/><Flag size={16}/>C’est une priorité</label></>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions">{onDelete&&<button className="icon-button delete-button" type="button" aria-label="Supprimer" onClick={onDelete} disabled={busy}><Trash2 size={19}/></button>}<button className="primary grow" type="submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>} {busy?'Enregistrement…':item?'Enregistrer les modifications':kind==='shopping'?'Ajouter à la liste':'Ajouter la tâche'}</button></div></form>;
}
