import DateField from './date-field';
import {foodEmoji} from '../design-system/runtime';
import QuickShopping from './quick-shopping';
import {productIcon} from '../lib/products';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {Check,ChevronLeft,ChevronRight,Plus,ShoppingBasket,BookmarkPlus,Copy,Trash2,Pencil,LockKeyhole,CalendarDays,Wallet,Camera,MessageSquare,Undo2,LoaderCircle} from './icons';
import {type Item,type ShoppingTemplate} from '../lib/domain';
import {weekStart,shiftWeek,weekLabel} from '../lib/shopping';
type Props={items:Item[];templates:ShoppingTemplate[];active:number;names:string[];week:string;setWeek:(s:string)=>void;busy:boolean;online:boolean;save:(action:string,payload:unknown,message?:string)=>Promise<boolean>;onEdit:(item:Item)=>void;onExpense:()=>void};
export default function HouseShopping({items,templates,active,names,week,setWeek,busy,online,save,onEdit,onExpense}:Props){
 const[quick,setQuick]=useState(false);
 const[motion,setMotion]=useState<{item:Item;done:boolean;phase:'saving'|'leaving'|'arriving';height:number}|null>(null),[feedback,setFeedback]=useState('');
 const locked=useRef(false),alive=useRef(true),timers=useRef<ReturnType<typeof setTimeout>[]>([]),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;timers.current.forEach(clearTimeout);};},[]);
 async function purchase(item:Item,done:boolean,button:HTMLButtonElement,keyboard:boolean){
  if(locked.current||busy||!online)return;locked.current=true;
  const height=button.closest('.shopping-row')?.getBoundingClientRect().height||120;
  setMotion({item,done,phase:'saving',height});setFeedback('');
  let ok=false;try{ok=await save('shopping-check',{id:item.id,version:item.version,done},done?`Achat enregistré au nom de ${names[active]}.`:'Article remis à acheter.');}catch{ok=false;}
  if(!alive.current)return;
  if(!ok){locked.current=false;setMotion(null);setFeedback('Votre achat n’a pas été enregistré. Actualisez puis réessayez.');return;}
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  setMotion({item,done,phase:'leaving',height});
  timers.current.push(setTimeout(()=>{
   if(!alive.current)return;setMotion({item,done,phase:'arriving',height});setFeedback(`${item.title} : ${done?'déplacé dans Acheté':'remis dans À acheter'}.`);
   timers.current.push(setTimeout(()=>{if(!alive.current)return;setMotion(null);locked.current=false;if(keyboard)requestAnimationFrame(()=>{const section=root.current?.querySelector(done?'.shopping-list':'.purchased-list');(section?.querySelector(done?'.purchase-check:not(:disabled)':'button.undo-purchase:not(:disabled)') as HTMLElement||section?.querySelector('h2'))?.focus();});},reduced?0:240));
  },reduced?0:360));
 }
 const actionBusy=busy||!!motion;

 const[templateTitle,setTemplateTitle]=useState(''),[showTemplates,setShowTemplates]=useState(false),[showSave,setShowSave]=useState(false);
 const presented=items.map(i=>motion&&motion.phase!=='arriving'&&motion.item.id===i.id?motion.item:i);
 const source=presented.filter(i=>i.weekStart===week),pending=source.filter(i=>!i.done),done=source.filter(i=>i.done).sort((a,b)=>(b.purchasedAt||'').localeCompare(a.purchasedAt||''));
 const backlog=items.filter(i=>!i.done&&i.weekStart&&i.weekStart<weekStart());const oldWeeks=[...new Set(backlog.map(i=>i.weekStart!))].sort();
 const row=(item:Item)=><div className={`nd-food shopping-row ${item.done?'purchased':''} ${motion?.item.id===item.id?'purchase-'+motion.phase:''}`} key={item.id} data-item-id={item.id} data-purchase-target={motion?.item.id===item.id?(motion.done?'purchased':'pending'):undefined} style={motion?.item.id===item.id?{'--row-height':motion.height+'px'} as CSSProperties:undefined} aria-busy={motion?.item.id===item.id&&motion.phase==='saving'}>{item.done?<span className="purchase-status" role="img" aria-label="Acheté"><Check size={17}/></span>:<button className="purchase-check" disabled={actionBusy||!online} aria-label={`Marquer acheté : ${item.title}`} aria-pressed={motion?.item.id===item.id&&motion.phase==='leaving'} onClick={e=>purchase(item,true,e.currentTarget,e.detail===0)}>{motion?.item.id===item.id&&(motion.phase==='saving'?<LoaderCircle className="spin" size={18}/>:<Check size={20}/>)}</button>}<span className="product-emoji shopping-emoji" aria-hidden="true">{foodEmoji(item.title,productIcon(item.title))}</span><button className="shopping-description" onClick={()=>onEdit(item)}><strong>{item.title}</strong>{(item.note||item.photoId)&&<span className="article-indicators">{item.note&&<><MessageSquare size={12}/>Commentaire</>}{item.photoId&&<><Camera size={12}/>Photo</>}</span>}<span>{item.quantity&&<b>{item.quantity} · </b>}{item.done?(item.purchasedBy===0||item.purchasedBy===1?`Acheté par ${names[item.purchasedBy]}${item.purchasedAt?' · '+new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date(item.purchasedAt)):''}`:'Achat déjà coché · auteur non renseigné'):`Ajouté par ${item.owner===0||item.owner===1?names[item.owner]:'la maison'}${item.assignee>=0?' · Pour '+names[item.assignee]:''}`}</span></button>{item.done&&(item.purchasedBy===active||item.purchasedBy==null)&&<button className="undo-purchase text-link" disabled={actionBusy||!online} aria-label={`Remettre ${item.title} à acheter`} onClick={e=>purchase(item,false,e.currentTarget,e.detail===0)}><Undo2 size={17} aria-hidden="true"/>À acheter</button>}<button className="icon-button" aria-label={`${item.owner===active?'Modifier':'Voir'} ${item.title}`} onClick={()=>onEdit(item)}>{item.owner===active?<Pencil size={16}/>:<LockKeyhole size={16}/>}</button></div>;
 return <div className="shopping-workspace" ref={root}><p className="sr-only" role="status">{feedback}</p>{quick&&<QuickShopping week={week} items={source} busy={busy} save={save} onClose={()=>setQuick(false)}/>} <section className="week-toolbar"><div className="week-switch"><button className="icon-button" aria-label="Semaine précédente" onClick={()=>setWeek(shiftWeek(week,-1))}><ChevronLeft/></button><div><span className="eyebrow">{week===weekStart()?'Cette semaine':'Semaine choisie'}</span><h2>{weekLabel(week)}</h2></div><button className="icon-button" aria-label="Semaine suivante" onClick={()=>setWeek(shiftWeek(week,1))}><ChevronRight/></button></div><div className="week-actions"><label className="week-date"><DateField displayLabel="Choisir une date" type="date" aria-label="Choisir une semaine" value={week} onChange={e=>e.target.value&&setWeek(weekStart(e.target.value))}/></label>{week!==weekStart()&&<button className="text-link" onClick={()=>setWeek(weekStart())}>Aujourd’hui</button>}<button className="secondary" onClick={()=>setShowTemplates(!showTemplates)} aria-expanded={showTemplates}><Copy size={17}/>Listes types<span className="count-badge">{templates.length}</span></button></div></section>
 {oldWeeks.some(w=>w!==week)&&<div className="shopping-backlog"><span>Il reste des articles sur d’autres semaines.</span>{oldWeeks.filter(w=>w!==week).map(w=><button key={w} className="text-link" onClick={()=>setWeek(w)}>{weekLabel(w)} ({backlog.filter(i=>i.weekStart===w).length})</button>)}</div>}
 {showTemplates&&<section className="panel templates-panel"><div className="section-title"><div><h2>Vos listes types</h2><p>Réutilisez vos habitudes dans la semaine sélectionnée.</p></div><button className="text-link" onClick={()=>setShowTemplates(false)}>Fermer</button></div>{templates.length?<div className="template-grid">{templates.map(t=><div className="template-card" key={t.id}><Copy size={22}/><h3>{t.title}</h3><p>{t.items.length} articles · {names[t.owner]}</p><small>{t.items.slice(0,4).map(i=>i.title).join(', ')}{t.items.length>4?'…':''}</small><div><button className="secondary" disabled={busy||!online} onClick={()=>save('template-apply',{id:t.id,operationId:crypto.randomUUID(),weekStart:week},'Liste ajoutée à cette semaine.')}><Plus size={17}/>Ajouter à la semaine</button>{t.owner===active&&<button className="icon-button" disabled={busy} aria-label={`Supprimer le modèle ${t.title}`} onClick={()=>{if(window.confirm(`Supprimer la liste type « ${t.title} » ? Les courses existantes seront conservées.`))save('template-delete',{id:t.id},'Liste type supprimée.');}}><Trash2 size={17}/></button>}</div></div>)}</div>:<div className="empty"><Copy size={30}/><h3>Votre prochaine liste commence ici</h3><p>Ajoutez vos articles, puis enregistrez cette semaine comme liste type.</p></div>}</section>}
 <div className="shopping-columns"><section className="panel shopping-list"><div className="section-title"><h2 tabIndex={-1}>À acheter <span className="count-badge">{pending.length}</span></h2><span className="shared-pill">Partagé à deux</span></div><button className="catalog-add-button" onClick={()=>setQuick(true)}><Plus size={20}/><span><strong>Ajouter un article</strong><small>Touchez plusieurs articles, ajustez les détails ensuite</small></span></button>{pending.length?pending.map(row):<div className="empty"><span className="empty-icon">{source.length?<Check size={30}/>:<ShoppingBasket size={30}/>}</span><h3>{source.length?'Les courses sont faites !':'Qu’est-ce qu’il nous manque ?'}</h3><p>{source.length?'Tous les achats de cette semaine sont visibles juste à côté.':'Ajoutez un article ici, ou reprenez une de vos listes types.'}</p></div>}<div className="shopping-list-footer"><button className="text-link" disabled={!source.length||busy} onClick={()=>setShowSave(!showSave)}><BookmarkPlus size={18}/>Enregistrer comme liste type</button>{showSave&&<form className="save-template" onSubmit={async e=>{e.preventDefault();if(await save('template-create',{id:crypto.randomUUID(),title:templateTitle,weekStart:week},'Liste type enregistrée.')){setShowSave(false);setTemplateTitle('');setShowTemplates(true);}}}><label>Nom de la liste<input value={templateTitle} onChange={e=>setTemplateTitle(e.target.value)} placeholder="Nos essentiels de la semaine" required maxLength={100}/></label><button className="primary" disabled={busy}>Enregistrer</button></form>}</div></section>
 <div className="purchases-column"><section className="panel purchased-list"><div className="section-title"><h2 tabIndex={-1}>Acheté <span className="count-badge">{done.length}</span></h2><Check size={20}/></div><div className="shopping-progress"><div><strong>{done.length} sur {source.length}</strong><span>articles achetés</span></div><progress aria-label="Progression des courses" max={source.length||1} value={done.length}/></div>{done.length?done.map(row):<p className="purchased-empty">Cochez un article après l’achat. Il apparaîtra ici avec le nom de la personne qui l’a acheté.</p>}</section><button className="expense-shortcut" onClick={onExpense}><span><Wallet size={23}/><strong>Noter le montant des courses</strong></span><Plus size={19}/></button><p className="helper-copy">Cocher un achat ne crée pas de dépense. Seule la personne qui l’a coché peut l’annuler.</p></div></div></div>;
}
