import {useCallback,useEffect,useRef,useState} from 'react';
import {MapPin,Search,Heart,Plus,Trash2,X,Navigation,ArrowUpRight,ChevronDown} from './icons';
import {apiFetch} from '../lib/api-client';
import type {Place,FavoritePlace} from '../lib/life';
import LifeDialog from './life-dialog';
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase();
export function usePlaces(){
 const[places,setPlaces]=useState<FavoritePlace[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const alive=useRef(true),saving=useRef(false),sequence=useRef(0);
 const refresh=useCallback(async()=>{const seq=++sequence.current;try{const r=await apiFetch('/api/places');const d=await r.json();if(!r.ok)throw Error(d.error);if(alive.current&&seq===sequence.current)setPlaces(d.places);}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Carnet indisponible.');}},[]);
 useEffect(()=>{alive.current=true;refresh();const t=setInterval(()=>{if(document.visibilityState==='visible'&&!saving.current)refresh();},15000);return()=>{alive.current=false;clearInterval(t);++sequence.current;};},[refresh]);
 async function change(payload:unknown){if(saving.current)return false;saving.current=true;setBusy(true);setError('');++sequence.current;try{const r=await apiFetch('/api/places',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||'Adresse non enregistrée.');if(alive.current)setPlaces(d.places);return true;}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Connexion interrompue.');return false;}finally{saving.current=false;if(alive.current)setBusy(false);}}
 return {places,busy,error,change,refresh};
}
export function mapLinks(place:Place){const destination=place.lat!==null&&place.lon!==null?`${place.lat},${place.lon}`:[place.name,place.address].join(', ');return {google:'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(destination),apple:'https://maps.apple.com/?daddr='+encodeURIComponent(destination)};}
export function PlaceCard({place,compact=false}:{place:Place;compact?:boolean}){
 const[map,setMap]=useState(false),links=mapLinks(place),coordinates=place.lat!==null&&place.lon!==null;
 const bbox=coordinates?[Math.max(-180,place.lon!-.006),Math.max(-90,place.lat!-.004),Math.min(180,place.lon!+.006),Math.min(90,place.lat!+.004)].join(','):'';
 return <div className={`place-card ${compact?'compact':''}`}><div className="place-heading"><span className="place-pin"><MapPin size={21}/></span><div><strong>{place.name}</strong><p>{place.address}</p></div></div>{coordinates&&<button type="button" className="place-map-toggle" aria-expanded={map} onClick={()=>setMap(!map)}><MapPin size={18}/><span>{map?'Fermer la carte':'Voir sur la carte'}</span><ChevronDown size={18}/></button>}{map&&coordinates&&<iframe className="place-map" title={'Carte : '+place.name} loading="lazy" referrerPolicy="no-referrer" src={'https://www.openstreetmap.org/export/embed.html?bbox='+encodeURIComponent(bbox)+'&layer=mapnik&marker='+encodeURIComponent(place.lat+','+place.lon)}/>}<div className="place-directions"><span className="place-directions-label">On y va ?</span><div className="place-navigation-links"><a href={links.google} target="_blank" rel="noopener noreferrer" className="secondary"><Navigation size={16}/>Google Maps<ArrowUpRight size={14}/></a><a href={links.apple} target="_blank" rel="noopener noreferrer" className="secondary"><Navigation size={16}/>Plans<ArrowUpRight size={14}/></a></div></div>{place.source==='osm'&&<small className="place-credit">Adresse : <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap</a></small>}</div>;
}
export function PlacePicker({value,onChange,favorites=[],restaurants=false}:{value:Place|null;onChange:(p:Place|null)=>void;favorites?:FavoritePlace[];restaurants?:boolean}){
 const[query,setQuery]=useState(''),[results,setResults]=useState<Place[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[manual,setManual]=useState(false),[manualName,setManualName]=useState(''),[manualAddress,setManualAddress]=useState(''),[favoriteQuery,setFavoriteQuery]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(value||manual||query.trim().length<3){setResults([]);setSearched(false);setLoading(false);return;}const controller=new AbortController();setLoading(true);setSearched(false);setError('');const timer=setTimeout(async()=>{try{const r=await apiFetch('/api/place-search?q='+encodeURIComponent(query.trim())+'&restaurants='+(restaurants?'1':'0'),{signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error||'Recherche indisponible.');if(!controller.signal.aborted){setResults(d.places);setSearched(true);}}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'Recherche indisponible.');setResults([]);}}finally{if(!controller.signal.aborted)setLoading(false);}},850);return()=>{clearTimeout(timer);controller.abort();};},[query,restaurants,value,manual,retry]);
 if(value)return <div className="selected-place"><PlaceCard place={value} compact/><button type="button" className="secondary" onClick={()=>onChange(null)}><X size={16}/>Retirer l’adresse</button></div>;
 const filtered=favorites.filter(p=>normalize(p.name+' '+p.address).includes(normalize(favoriteQuery)));
 return <fieldset className="place-picker"><legend>Un lieu pour se retrouver <span>(facultatif)</span></legend>{favorites.length>0&&<details className="favorite-place-picker"><summary><Heart size={18}/>Nos restaurants favoris <span>{favorites.length}</span></summary><label>Rechercher dans nos favoris<input value={favoriteQuery} onChange={e=>setFavoriteQuery(e.target.value)} placeholder="Le nom du restaurant…"/></label><div className="place-results">{filtered.map(p=><button type="button" key={p.id} onClick={()=>onChange(p)}><Heart size={18}/><span><strong>{p.name}</strong><small>{p.address}</small></span><Plus size={18}/></button>)}{!filtered.length&&<p>Aucun favori ne correspond.</p>}</div></details>}{!manual?<><label>{restaurants?'Chercher un restaurant et sa ville':'Chercher un lieu ou une adresse'}<div className="place-search-field"><Search size={20}/><input value={query} maxLength={150} onChange={e=>setQuery(e.target.value)} placeholder={restaurants?'Par exemple : Petit Bao, Paris':'Un restaurant, un musée, une adresse…'} autoComplete="off" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();setRetry(r=>r+1);}}}/></div></label><p className="helper-copy place-search-status" role="status">{loading?'On cherche votre petit coin…':searched?(results.length?`${results.length} lieux trouvés`:'Aucun lieu trouvé. Essayez avec la ville ou une adresse.'):'Saisissez au moins 3 caractères. Le nom et la ville aident à trouver le bon lieu.'}</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="place-results">{results.map(p=><button type="button" key={p.sourceId} onClick={()=>onChange(p)}><MapPin size={19}/><span><strong>{p.name}</strong><small>{p.address}</small></span><Plus size={18}/></button>)}</div>{searched&&<small className="place-credit">Recherche Photon · © OpenStreetMap</small>}<button type="button" className="secondary" onClick={()=>{setManual(true);setError('');}}>Saisir l’adresse moi-même</button></>:<div className="manual-place"><label>Le nom du lieu<input value={manualName} maxLength={150} onChange={e=>setManualName(e.target.value)} placeholder="Notre petit resto"/></label><label>Son adresse<textarea rows={2} maxLength={350} value={manualAddress} onChange={e=>setManualAddress(e.target.value)} placeholder="Numéro, rue, ville…"/></label><div className="place-links"><button type="button" className="secondary" onClick={()=>setManual(false)}>Revenir à la recherche</button><button type="button" className="primary" disabled={!manualName.trim()||!manualAddress.trim()} onClick={()=>onChange({name:manualName.trim(),address:manualAddress.trim(),lat:null,lon:null,source:'manual'})}><CheckIcon/>Choisir ce lieu</button></div></div>}</fieldset>;
}
function CheckIcon(){return <MapPin size={16}/>;}
export function FavoriteRestaurants({places,active,names,busy,error,change,onInvite}:{places:FavoritePlace[];active:number;names:string[];busy:boolean;error:string;change:(p:unknown)=>Promise<boolean>;onInvite:(p:Place)=>void}){
 const[adding,setAdding]=useState(false),[selected,setSelected]=useState<Place|null>(null),[query,setQuery]=useState(''),[id,setId]=useState(()=>crypto.randomUUID());
 const visible=places.filter(p=>normalize(p.name+' '+p.address).includes(normalize(query)));
 return <section className="restaurant-space"><header className="restaurant-intro"><div><span className="eyebrow">Nos bonnes adresses</span><h2>Une table pour deux ?</h2><p>Les restos qu’on aime, à retrouver pour notre prochaine invitation.</p></div><button className="primary" onClick={()=>{setId(crypto.randomUUID());setSelected(null);setAdding(true);}}><Plus size={18}/>Un restaurant</button></header><label className="restaurant-filter">Rechercher dans notre carnet<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom ou ville…"/></label>{error&&!adding&&<p className="form-error" role="alert">{error}</p>}<div className="restaurant-grid">{visible.map(p=><article className="restaurant-card" key={p.id}><PlaceCard place={p}/><footer><small>Ajouté par {names[p.owner]}</small><div className="place-links"><button className="primary" onClick={()=>onInvite(p)}><Heart size={17}/>Inviter ici</button>{p.owner===active&&<button className="icon-button" disabled={busy} aria-label={'Retirer '+p.name+' des favoris'} onClick={async()=>{if(window.confirm('Retirer ce restaurant de votre carnet ? Les invitations déjà envoyées garderont leur adresse.'))await change({action:'remove',id:p.id,version:p.version});}}><Trash2 size={18}/></button>}</div></footer></article>)}</div>{!visible.length&&<div className="panel empty"><Heart size={28}/><h3>{places.length?'Aucun resto trouvé':'On garde nos bonnes adresses ?'}</h3><p>{places.length?'Essayez un autre nom ou une ville.':'Cherchez un restaurant, choisissez son adresse, et il sera disponible pour vous deux.'}</p></div>}{adding&&<LifeDialog title="Un resto dans notre carnet" busy={busy} onClose={()=>setAdding(false)}><PlacePicker value={selected} onChange={setSelected} restaurants/>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary wide" disabled={busy||!selected} onClick={async()=>{if(selected&&await change({action:'save',id,version:0,place:selected}))setAdding(false);}}><Heart size={18}/>{busy?'Enregistrement…':'Garder ce restaurant'}</button></LifeDialog>}</section>;
}
