import InvitationCelebration from './invitation-celebration';
import {PlaceCard,PlacePicker,FavoriteRestaurants,usePlaces} from './house-places';
import DateField from './date-field';
import {HeroCard,Buddy} from '../design-system/runtime';
import {useEffect,useState,type FormEvent} from 'react';
import {CalendarDays,Check,Heart,MapPin,Plus,Send,Sparkles,Trash2,X} from './icons';
import type {Idea,Place,FavoritePlace} from '../lib/life';
import LifeDialog from './life-dialog';
type Save=(a:string,p:unknown,m?:string)=>Promise<boolean>;
const categories={restaurant:{label:'Restaurant',icon:'🍽️'},outing:{label:'Sortie',icon:'🎟️'},home:{label:'À la maison',icon:'🛋️'},trip:{label:'Escapade',icon:'🧳'},surprise:{label:'Surprise',icon:'🎁'}};
function IdeaDetails({idea,names,celebrate=false}:{idea:Idea;names:string[];celebrate?:boolean}){return <><div className="invitation-ticket">{celebrate&&<InvitationCelebration/>}<div className="ticket-art" aria-hidden="true"><Buddy shape="flower" tone="rose" mood="love" size={72}/><span>rendez-vous<br/><em>avec nous</em></span><Buddy shape="pill" tone="lavande" mood="happy" size={62}/></div><span className="invitation-kicker">{names[idea.owner]} vous invite</span><h2>{idea.title} <span aria-hidden="true">{categories[idea.category].icon}</span></h2>{idea.description&&<p className="invitation-description">{idea.description}</p>}<div className="invitation-meta">{idea.date&&<span><CalendarDays size={16}/>{new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(idea.date+'T12:00:00'))}{idea.time&&` à ${idea.time}`}</span>}{idea.location&&<span><MapPin size={16}/>{idea.location}</span>}</div>{idea.place&&<PlaceCard place={idea.place} compact/>}<p className="invitation-votes"><Check size={15}/>{names[idea.owner]} a déjà dit oui. Et vous ?</p></div></>;}
export function InvitationArrival({enabled=true,ideas,active,names,busy,error,save,onOpen}:{error:string;enabled?:boolean;ideas:Idea[];active:number;names:string[];busy:boolean;save:Save;onOpen:()=>void}){
 const[dismissed,setDismissed]=useState<string[]>([]),[note,setNote]=useState('');const idea=ideas.filter(i=>i.owner!==active&&i.status==='pending').find(i=>!dismissed.includes(i.id+':'+i.version));
 if(!idea||!enabled)return null;const close=()=>{setDismissed(d=>[...d,idea.id+':'+idea.version]);setNote('');};
 async function respond(status:'accepted'|'declined'){if(await save('idea-response',{id:idea!.id,version:idea!.version,status,responseNote:note},status==='accepted'?'C’est un oui à deux !':'Votre réponse a été transmise.'))close();}
 return <LifeDialog className="invitation-arrival" title="Une invitation pour vous" busy={busy} onClose={close}><div className="invitation-paper celebrating"><IdeaDetails idea={idea} names={names} celebrate/><details className="invitation-reply"><summary>Ajouter un petit mot</summary><label className="invitation-note">Un petit mot en réponse <span>(facultatif)</span><textarea rows={2} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} placeholder="Avec plaisir ! On peut plutôt à 19 h ?"/></label></details>{error&&<p className="form-error" role="alert">{error}</p>}<div className="invitation-response"><button className="primary" disabled={busy} onClick={()=>respond('accepted')}><Heart size={17}/>Oui, embarque-moi</button><button className="secondary" disabled={busy} onClick={()=>respond('declined')}><X size={17}/>Mon plaid m’a réservé·e</button></div><button className="text-link" onClick={close} disabled={busy}>Je laisse le suspense</button><button className="text-link" onClick={()=>{close();onOpen();}}>Nos autres idées</button></div></LifeDialog>;
}
export default function HouseIdeas({create=false,onCreated,ideas,active,names,busy,error,save}:{create?:boolean;onCreated?:()=>void;ideas:Idea[];active:number;names:string[];busy:boolean;error:string;save:Save}){
 const saved=usePlaces();const[space,setSpace]=useState('invitations'),[preset,setPreset]=useState<Place|null>(null);
 const[editing,setEditing]=useState<Idea|null|undefined>(undefined),[selected,setSelected]=useState<Idea|null>(null),[response,setResponse]=useState(''),[filter,setFilter]=useState('all');
 useEffect(()=>{if(create){setSpace('invitations');setPreset(null);setEditing(null);onCreated?.();}},[create,onCreated]);
 const current=selected?ideas.find(i=>i.id===selected.id):undefined;
 const pending=ideas.filter(i=>i.status==='pending');const visible=ideas.filter(i=>filter==='all'||i.status===filter).slice().reverse();
 async function respond(status:'accepted'|'declined'){if(!current)return;if(await save('idea-response',{id:current.id,version:current.version,status,responseNote:response},status==='accepted'?'À vous les moments à deux !':'Votre réponse est enregistrée.')){setSelected(null);setResponse('');}}
 return <div className="ideas-space"><HeroCard tone="beurre" title={<>Une envie,<br/>un <em>nous.</em></>} text="Une idée, une invitation. On dit oui chacun de son côté." action="Proposer une activité" onAction={()=>{setPreset(null);setEditing(null);}} buddy={{shape:'blob',tone:'rose',mood:'love'}}/><div className="life-filters ideas-tabs" aria-label="Choisir un espace"><button className={space==='invitations'?'selected':''} aria-pressed={space==='invitations'} onClick={()=>setSpace('invitations')}>Nos invitations</button><button className={space==='restaurants'?'selected':''} aria-pressed={space==='restaurants'} onClick={()=>setSpace('restaurants')}><Heart size={17}/>Nos restaurants</button></div>{space==='restaurants'?<FavoriteRestaurants {...saved} active={active} names={names} onInvite={p=>{setPreset(p);setEditing(null);}}/>:<><div className="life-filters" aria-label="Filtrer les invitations">{[['all','Toutes'],['pending',`En attente (${pending.length})`],['accepted','Acceptées'],['declined','Pas cette fois, mon cœur']].map(([id,label])=><button key={id} className={filter===id?'selected':''} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>{visible.length?<div className="ideas-grid">{visible.map(i=><button key={i.id} className={`idea-card idea-${i.category}`} onClick={()=>{setSelected(i);setResponse('');}}><div className="idea-card-top"><span className={`idea-status ${i.status}`}>{i.status==='accepted'?'Deux oui !':i.status==='declined'?'Pas cette fois, mon cœur':i.owner===active?'Réponse attendue':'À vous de répondre'}</span></div><small>{categories[i.category].label} · Proposé par {names[i.owner]}</small><h2>{i.title} <span aria-hidden="true">{categories[i.category].icon}</span></h2><p>{i.description||'Un moment à partager, juste vous deux.'}</p><footer>{i.date?<span><CalendarDays size={15}/>{new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date(i.date+'T12:00:00'))}{i.time&&` · ${i.time}`}</span>:<span>Date à décider ensemble</span>}<span className="idea-votes"><Check size={14}/>{i.status==='accepted'?'2 / 2':'1 / 2'}</span></footer></button>)}</div>:<div className="panel empty"><span className="empty-icon"><Sparkles size={29}/></span><h3>{filter==='all'?'Votre prochaine histoire commence par une idée':'Aucune invitation ici pour le moment'}</h3><p>Un resto, une balade, un film sous le plaid… Les petits moments comptent aussi.</p>{filter==='all'&&<button className="text-link" onClick={()=>setEditing(null)}>Envoyer la première invitation</button>}</div>}</>}
 {editing!==undefined&&<LifeDialog title={editing?'Modifier mon invitation':'Une idée pour nous deux'} onClose={()=>setEditing(undefined)} busy={busy}><IdeaForm key={editing?.id||'new'} idea={editing} preset={preset} favorites={saved.places} busy={busy} error={error} onSave={async p=>{if(await save('idea',p,'Invitation transmise à votre moitié.'))setEditing(undefined);}}/></LifeDialog>}
 {current&&<LifeDialog title="Notre invitation" onClose={()=>setSelected(null)} busy={busy}><div className="invitation-paper celebrating"><IdeaDetails idea={current} names={names} celebrate={current.owner!==active&&current.status==='pending'}/><p className={`idea-status ${current.status}`}>{current.status==='accepted'?'On a dit oui tous les deux':current.status==='declined'?'Pas cette fois, mon cœur. Une autre idée nous attend !':current.owner===active?`En attente de la réponse de ${names[1-active]}.`:'Cette invitation attend votre réponse.'}</p>{current.responseNote&&<blockquote className="idea-response-note"><strong>{names[1-current.owner]}</strong><p>{current.responseNote}</p></blockquote>}{current.owner!==active&&current.status==='pending'&&<><label className="invitation-note">Votre petit mot <span>(facultatif)</span><textarea rows={2} maxLength={500} value={response} onChange={e=>setResponse(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="invitation-response"><button className="primary" disabled={busy} onClick={()=>respond('accepted')}><Check size={18}/>Oui, embarque-moi</button><button className="secondary" disabled={busy} onClick={()=>respond('declined')}>Mon plaid m’a réservé·e</button></div></>}{current.owner===active&&<div className="idea-owner-actions"><button className="secondary" onClick={()=>{setSelected(null);setPreset(null);setEditing(current);}}>Modifier et reproposer</button><button className="text-link" disabled={busy} onClick={async()=>{if(window.confirm('Supprimer cette invitation pour vous deux ?')&&await save('delete-idea',{id:current.id,version:current.version},'Invitation supprimée.'))setSelected(null);}}><Trash2 size={16}/>Supprimer</button></div>}<p className="helper-copy">Une invitation acceptée ne crée pas automatiquement de rendez-vous dans l’agenda.</p></div></LifeDialog>}
 </div>;
}
function IdeaForm({idea,preset,favorites,busy,error,onSave}:{idea:Idea|null;preset:Place|null;favorites:FavoritePlace[];busy:boolean;error:string;onSave:(p:unknown)=>Promise<void>}){
 const[place,setPlace]=useState<Place|null>(idea?.place||preset),[category,setCategory]=useState(idea?.category||'restaurant'),[location,setLocation]=useState(idea?.location||''),[reveal,setReveal]=useState(!!idea?.place);const[id]=useState(()=>idea?.id||crypto.randomUUID());const[localError,setLocalError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setLocalError('');if(f.get('time')&&!f.get('date')){setLocalError('Choisissez une date avec cette heure, ou laissez les deux champs vides.');return;}await onSave({id,version:idea?.version||0,title:String(f.get('title')).trim(),category:String(f.get('category')),description:String(f.get('description')||''),date:String(f.get('date')||''),time:String(f.get('time')||''),location,place});}
 return <form className="form" onSubmit={submit}><label>Qu’est-ce qu’on pourrait faire ?<input autoFocus name="title" required maxLength={100} defaultValue={idea?.title||(preset?('Un resto chez '+preset.name).slice(0,100):'')} placeholder="Un resto italien vendredi soir ?"/></label><label>Le genre de moment<select name="category" value={category} onChange={e=>{const next=e.target.value as Idea['category'];setCategory(next);if(next==='surprise'){setPlace(null);setLocation('');setReveal(false);}}}>{Object.entries(categories).map(([id,c])=><option key={id} value={id}>{c.label}</option>)}</select></label><label>Racontez votre idée<textarea name="description" rows={3} maxLength={1000} defaultValue={idea?.description||''} placeholder="L’endroit, l’ambiance, pourquoi ça vous ferait plaisir…"/></label><div className="form-grid"><label>Date (facultatif)<DateField type="date" name="date" defaultValue={idea?.date||''}/></label><label>Heure (facultatif)<DateField type="time" name="time" defaultValue={idea?.time||''}/></label></div><>{category==='surprise'&&<label className="check-label"><input type="checkbox" checked={reveal} onChange={e=>{setReveal(e.target.checked);if(!e.target.checked){setPlace(null);setLocation('');}}}/>Dévoiler quand même le lieu</label>}{(category!=='surprise'||reveal)&&<><PlacePicker value={place} onChange={setPlace} favorites={favorites} restaurants={category==='restaurant'}/><label>Une précision sur le lieu (facultatif)<input name="location" maxLength={150} value={location} onChange={e=>setLocation(e.target.value)} placeholder="Rendez-vous devant la porte, table en terrasse…"/></label></>}</><p className="helper-copy">En transmettant, vous donnez votre oui. Votre moitié répondra depuis son compte.{idea&&' Une modification relance une nouvelle demande d’accord.'}</p>{(error||localError)&&<p className="form-error" role="alert">{localError||error}</p>}<button className="primary wide" disabled={busy} type="submit"><Send size={17}/>{busy?'Transmission…':'Transmettre mon invitation'}</button></form>;
}
