import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Send,MessageCircle,LockKeyhole,Pencil,Trash2,X,RefreshCw} from 'lucide-react';
import {apiFetch} from '../lib/api-client';
type Message={id:string;member:number;text:string;created_at:string;edited_at:string|null;version:number};
export default function HouseChat({active,names}:{active:number;names:string[]}){
 const[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[editing,setEditing]=useState<Message|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[more,setMore]=useState(false);
 const sending=useRef(false),draftId=useRef(crypto.randomUUID()),list=useRef<HTMLDivElement>(null),atBottom=useRef(true),mounted=useRef(true),request=useRef(0),older=useRef<Message[]>([]);
 const refresh=useCallback(async()=>{const seq=++request.current;try{const r=await apiFetch('/api/chat',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Discussion indisponible.');if(!mounted.current||seq!==request.current)return;setMessages([...older.current.filter(m=>!d.messages.some((n:Message)=>n.id===m.id)),...d.messages]);if(!older.current.length)setMore(d.hasMore);setError('');}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Connexion indisponible.');}finally{if(mounted.current)setLoading(false);}},[]);
 useEffect(()=>{mounted.current=true;refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!sending.current)refresh();},3000);return()=>{mounted.current=false;clearInterval(timer);++request.current;};},[refresh]);
 useEffect(()=>{if(atBottom.current)list.current?.scrollTo({top:list.current.scrollHeight,behavior:'smooth'});},[messages]);
 async function olderMessages(){if(!messages[0]||busy)return;setBusy(true);try{const r=await apiFetch('/api/chat?before='+encodeURIComponent(messages[0].created_at)+'&beforeId='+messages[0].id);const d=await r.json();if(!r.ok)throw Error(d.error);atBottom.current=false;older.current=[...d.messages,...older.current];setMessages(prev=>[...d.messages,...prev]);setMore(d.hasMore);}catch(e){setError(e instanceof Error?e.message:'Chargement impossible.');}finally{setBusy(false);}}
 async function change(payload:unknown){if(sending.current)return false;sending.current=true;setBusy(true);++request.current;try{const r=await apiFetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||'Message non enregistré.');return true;}catch(e){setError(e instanceof Error?e.message:'Connexion perdue. Votre texte est conservé.');return false;}finally{sending.current=false;setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();if(!text.trim())return;const edited=editing;if(await change({action:edited?'edit':'send',id:edited?.id||draftId.current,text:text.trim(),version:edited?.version})){if(edited)older.current=older.current.map(m=>m.id===edited.id?{...m,text:text.trim(),version:m.version+1,edited_at:new Date().toISOString()}:m);setText('');setEditing(null);draftId.current=crypto.randomUUID();atBottom.current=true;await refresh();}}
 return <section className="panel chat-panel"><header className="chat-header"><span className="chat-avatar">{names[1-active].slice(0,1)}</span><div><h2>{names[1-active]}</h2><p><LockKeyhole size={13}/>Discussion privée à deux</p></div><button className="icon-button" onClick={refresh} aria-label="Actualiser la discussion"><RefreshCw size={18}/></button></header>{error&&<p className="form-error" role="alert">{error}</p>}<div className="chat-messages" ref={list} onScroll={()=>{const el=list.current;if(el)atBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<90;}}>{more&&<button disabled={busy} className="secondary chat-older" onClick={olderMessages}>Charger les messages précédents</button>}{!messages.length&&<div className="empty"><span className="empty-icon"><MessageCircle size={30}/></span><h3>{loading?'Ouverture de la discussion…':'Un petit mot pour vous deux'}</h3><p>Une idée pour ce soir, une question, un « je t’aime »… Votre discussion reste dans votre maison.</p></div>}{messages.map((m,i)=>{const date=new Date(m.created_at),prev=messages[i-1];return <div key={m.id}>{(!prev||new Date(prev.created_at).toLocaleDateString()!==date.toLocaleDateString())&&<div className="chat-day">{new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(date)}</div>}<article className={`chat-message ${m.member===active?'mine':''}`}><span className="message-author">{names[m.member]}</span><p>{m.text}</p><footer><time dateTime={m.created_at}>{date.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}{m.edited_at?' · modifié':''}</time>{m.member===active&&<><button disabled={busy} aria-label="Modifier mon message" onClick={()=>{setEditing(m);setText(m.text);}}><Pencil size={14}/></button><button disabled={busy} aria-label="Supprimer mon message" onClick={async()=>{if(window.confirm('Supprimer ce message pour vous deux ?')&&await change({action:'delete',id:m.id,version:m.version})){older.current=older.current.filter(x=>x.id!==m.id);if(editing?.id===m.id){setEditing(null);setText('');}await refresh();}}}><Trash2 size={14}/></button></>}</footer></article></div>;})}</div><form className="chat-composer" onSubmit={submit}>{editing&&<div className="editing-message"><Pencil size={14}/>Modification de votre message<button type="button" aria-label="Annuler la modification" onClick={()=>{setEditing(null);setText('');}}><X size={18}/></button></div>}<div><textarea aria-label="Votre message" rows={2} placeholder={`Écrire à ${names[1-active]}…`} value={text} maxLength={2000} disabled={busy} onChange={e=>setText(e.target.value)}/><button className="primary" disabled={busy||!text.trim()} aria-label={editing?'Enregistrer le message':'Envoyer le message'}><Send size={20}/><span>{busy?'Envoi…':editing?'Enregistrer':'Envoyer'}</span></button></div><small>{text.length}/2000 · Seul l’auteur peut modifier ou supprimer son message.</small></form></section>;
}
