import {foodEmoji} from '../design-system/runtime';
import {useRef,useState} from 'react';
import {Check,Plus,Search} from './icons';
import {productCategories,searchProducts,productIcon} from '../lib/products';
import type {Item} from '../lib/domain';
import LifeDialog from './life-dialog';
export default function QuickShopping({week,items,busy,save,onClose}:{week:string;items:Item[];busy:boolean;save:(a:string,p:unknown,m?:string)=>Promise<boolean>;onClose:()=>void}){
 const[query,setQuery]=useState(''),[category,setCategory]=useState('Tous'),[added,setAdded]=useState<string[]>([]),[error,setError]=useState('');const lock=useRef(false),input=useRef<HTMLInputElement>(null),draft=useRef<{title:string;id:string}|null>(null);
 const matches=searchProducts(query,category),pending=items.filter(i=>!i.done);
 async function add(title:string){title=title.trim();if(!title||lock.current||busy)return;if(pending.some(i=>i.title.toLocaleLowerCase()===title.toLocaleLowerCase())){setError('Cet article est déjà à acheter cette semaine.');return;}lock.current=true;setError('');if(draft.current?.title!==title)draft.current={title,id:crypto.randomUUID()};try{if(await save('item',{id:draft.current.id,version:0,kind:'shopping',title,quantity:'',note:'',photoId:null,assignee:-1,due:'',priority:0,done:false,weekStart:week},`${title} ajouté !`)){setAdded(a=>[...a,title]);setQuery('');draft.current=null;input.current?.focus();}else setError('Ajout non confirmé. Réessayez avant de fermer.');}finally{lock.current=false;}}
 return <LifeDialog title="On remplit le panier ?" onClose={onClose} busy={busy} className="quick-shopping"><p>Touchez pour ajouter. Quantités et photos se règlent ensuite.</p><div className="product-search"><Search size={20}/><input ref={input} autoFocus aria-label="Rechercher un article" placeholder="Banane, semoule, céréales…" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add(matches[0]?.title||query);}}}/></div><div className="catalog-categories">{['Tous',...productCategories].map(c=><button key={c} className={c===category?'selected':''} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="quick-products" role="region" aria-label="Articles disponibles" tabIndex={0}>{matches.map(p=>{const exists=pending.some(i=>i.title===p.title)||added.includes(p.title);return <button key={p.title} disabled={busy||exists} onClick={()=>add(p.title)}><span className="product-emoji">{foodEmoji(p.title,p.icon)}</span><span>{p.title}<small>{exists?'Déjà dans la liste':p.category}</small></span>{exists?<Check size={18}/>:<Plus size={18}/>}</button>;})}{query.trim()&&!matches.some(p=>p.title.toLowerCase()===query.trim().toLowerCase())&&<button disabled={busy} onClick={()=>add(query)}><span aria-hidden="true">{foodEmoji(query,productIcon(query))}</span><span>Ajouter « {query.trim()} »</span><Plus size={18}/></button>}</div>{error&&<p role="alert" className="form-error">{error}</p>}<footer className="quick-finish"><span role="status">{added.length} article{added.length!==1?'s':''} ajouté{added.length!==1?'s':''}</span><button className="primary" disabled={busy} onClick={onClose}><Check size={18}/>OK, tout est ajouté</button></footer></LifeDialog>;
}
