import {useState} from 'react';
import {Search,ChevronLeft,BookOpen} from './icons';
import {foodEmoji} from '../design-system/runtime';
import type {Recipe} from '../lib/recipes';
export const recipeGroups=['Tous','Végétarien','Poulet','Bœuf','Poisson','Autre'];
export const normalized=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('fr').replace(/œ/g,'oe');
export function filterRecipes(catalog:Recipe[],query:string,group:string,author:string){const terms=normalized(query).trim().split(/\s+/).filter(Boolean);return catalog.filter(r=>!r.archived&&(group==='Tous'||r.group===group)&&(author==='all'||author==='ours'&&r.owner!==undefined||author==='0'&&r.owner===0||author==='1'&&r.owner===1||author==='discovery'&&r.owner===undefined)&&terms.every(t=>normalized(r.title+' '+r.ingredients.join(' ')).includes(t)));}
export function RecipeFilters({names,query,group,author,onQuery,onGroup,onAuthor,autoFocus=false}:{autoFocus?:boolean;names:string[];query:string;group:string;author:string;onQuery:(s:string)=>void;onGroup:(s:string)=>void;onAuthor:(s:string)=>void}){return <div className="recipe-filters"><label className="search-field"><Search size={20}/><input autoFocus={autoFocus} type="search" aria-label="Rechercher une recette" placeholder="Un plat, un ingrédient…" value={query} onChange={e=>onQuery(e.target.value)}/></label><div className="life-filters" aria-label="Origine des recettes">{[['all','Toutes'],['ours','Nos recettes'],['0',names[0]],['1',names[1]],['discovery','Découvertes']].map(([value,label])=><button type="button" key={value} aria-pressed={author===value} className={author===value?'selected':''} onClick={()=>onAuthor(value)}>{label}</button>)}</div><div className="life-filters" aria-label="Catégorie de recette">{recipeGroups.map(value=><button type="button" key={value} aria-pressed={group===value} className={group===value?'selected':''} onClick={()=>onGroup(value)}>{value}</button>)}</div></div>;}
export function RecipePicker({catalog,names,onChoose,onBack,meal}:{catalog:Recipe[];names:string[];onChoose:(id:string)=>void;onBack:()=>void;meal:string}){const[query,setQuery]=useState(''),[group,setGroup]=useState('Tous'),[author,setAuthor]=useState('all');const results=filterRecipes(catalog,query,group,author);return <section className="recipe-picker"><button type="button" className="secondary" onClick={onBack}><ChevronLeft size={18}/>Mon menu</button><h3>{meal}</h3><RecipeFilters autoFocus {...{names,query,group,author}} onQuery={setQuery} onGroup={setGroup} onAuthor={setAuthor}/><p className="helper-copy" role="status">{results.length} recette{results.length>1?'s':''}</p><button type="button" className="secondary" onClick={()=>onChoose('')}>À improviser</button><div className="recipe-picker-results">{results.map(r=><button type="button" className="recipe-picker-row" key={r.id} onClick={()=>onChoose(r.id)}><span aria-hidden="true">{foodEmoji(r.title)}</span><span><strong>{r.title}</strong><small>{r.minutes} min · {r.owner!==undefined?names[r.owner]:'Découverte'}</small></span><BookOpen size={18}/></button>)}</div>{!results.length&&<p>Aucune recette. Essayez un autre mot ou retirez un filtre.</p>}</section>;}
