import {useRef,useState} from 'react';
import {RecipeView,foodEmoji} from '../design-system/runtime';
import type {Recipe} from '../lib/recipes';
import type {MealMatch} from '../lib/domain';
import {recipePhotos} from '../lib/recipe-photos';
import {ingredientParts,shoppingIngredients} from '../lib/recipe-quantity';
import {apiFetch} from '../lib/api-client';
import {weekStart} from '../lib/shopping';
import {parisDate} from '../lib/life';
import {useRecipePhoto} from './recipe-editor';
import LifeDialog from './life-dialog';
export default function RecipeDetail({recipe:r,names,active,match,favorite,onFavorite,onEdit,onClose,onWheel}:{recipe:Recipe;names:string[];active:number;match?:MealMatch;favorite:boolean;onFavorite:(value:boolean)=>void;onEdit:()=>void;onClose:()=>void;onWheel:()=>void}){
 const photo=useRecipePhoto(r),[adding,setAdding]=useState(false),[notice,setNotice]=useState(''),[added,setAdded]=useState(false);const operation=useRef(crypto.randomUUID());const illustration=r.image||recipePhotos[r.photo];
 async function add(servings:number){if(adding||added)return;setAdding(true);setNotice('');try{const response=await apiFetch('/api/household',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'shopping-batch',payload:{id:operation.current,weekStart:weekStart(parisDate()),note:`Pour ${r.title} · ${servings} personnes`,items:shoppingIngredients(r.ingredients,servings/r.servings)}})});const data=await response.json();if(!response.ok)throw Error(data.error||'Ajout impossible. Réessayez.');setAdded(true);setNotice('Les ingrédients sont dans les courses de cette semaine.');}catch(e){setNotice(e instanceof Error?e.message:'Connexion perdue. Réessayez.');}finally{setAdding(false);}}
 return <LifeDialog title={r.title} onClose={onClose} className="recipe-design-dialog"><RecipeView recipe={{name:r.title,emoji:foodEmoji(r.title),image:r.photoId?photo:illustration?.url,tone:'beurre',matched:!!match,by:r.owner!==undefined?{name:names[r.owner],partner:r.owner===0?'a':'b'}:undefined,time:r.minutes+' min',difficulty:r.difficulty||'Non précisée',servings:r.servings,ingredients:r.ingredients.map(i=>({...ingredientParts(i),emoji:foodEmoji(i)})),steps:r.steps.map((text,i)=>({title:`Préparation ${i+1}`,text}))}} favorite={favorite} onFavorite={onFavorite} onClose={onClose} onAddToList={add} adding={adding||added}/><div className="recipe-detail-notes">{notice&&<p role="status" className="info-box">{notice}</p>}{match&&<button className="primary" onClick={onWheel}>Qui cuisine ?</button>}{r.owner===active&&!r.archived&&<button className="secondary" onClick={onEdit}>Modifier ma recette</button>}{(r.calories!=null||r.nutrients)&&<section className="recipe-nutrition"><h3>Les petits plus du plat</h3>{r.calories!=null&&<strong>{r.calories} kcal par portion</strong>}{r.nutrients&&<p>{r.nutrients}</p>}<small>Indications de l’auteur, sans calcul automatique.</small></section>}<p className="helper-copy">Sans porc · Adaptez les ingrédients à vos allergies. Les quantités sans nombre restent à ajuster selon votre goût.</p>{r.generatedAt&&<p className="photo-credit">Recette adaptée par IA · <a href={r.sourceUrl} target="_blank" rel="noreferrer">Source : {r.sourceTitle}</a></p>}{illustration&&<p className="photo-credit">Photo d’illustration : <a href={illustration.source} target="_blank" rel="noreferrer">{illustration.author}</a> · <a href={illustration.licenseUrl} target="_blank" rel="noreferrer">{illustration.license}</a>.</p>}</div></LifeDialog>;
}
