import {foodEmoji} from '../design-system/runtime';
import {compressPhoto} from '../lib/photos';
import {useEffect,useId,useRef,useState,type FormEvent} from 'react';
import {Camera,Check,ChevronDown,ImagePlus,LoaderCircle,Search,Trash2,X} from './icons';
import {apiFetch} from '../lib/api-client';
import {findProduct,productCategories,productIcon,products,searchProducts,type Product} from '../lib/products';
import type {Item} from '../lib/domain';
export function ProductPicker({value,onChange}:{value:string;onChange:(s:string)=>void}){
 const[open,setOpen]=useState(false),[category,setCategory]=useState('Tous'),[index,setIndex]=useState(0);const id=useId();const root=useRef<HTMLDivElement>(null);
 const matches=searchProducts(value,category);
 useEffect(()=>{if(open)document.getElementById(id+'-'+index)?.scrollIntoView({block:'nearest'});},[index,id]);
 function choose(p:Product){onChange(p.title);setOpen(false);setIndex(0);}
 return <div className="product-picker" ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><label htmlFor={id}>Qu’est-ce qu’on achète ?</label><div className="product-search"><span className="product-emoji" aria-hidden="true">{foodEmoji(value,productIcon(value))}</span><input id={id} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id+'-list'} aria-activedescendant={open&&matches[index]?id+'-'+index:undefined} autoComplete="off" autoFocus maxLength={100} required value={value} placeholder="Rechercher ou écrire un article…" onFocus={()=>setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true);setIndex(0);}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setOpen(false);}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setIndex(i=>Math.max(0,Math.min(matches.length-1,i+(e.key==='ArrowDown'?1:-1))));}if(e.key==='Enter'&&open&&matches[index]){e.preventDefault();choose(matches[index]);}}}/><button type="button" className="icon-button" aria-label={open?'Fermer le catalogue':'Parcourir le catalogue'} onClick={()=>{setOpen(!open);setIndex(0);}}><ChevronDown size={18}/></button></div>{open&&<div className="product-catalog"><div className="catalog-caption"><Search size={14}/><span>{value?`${matches.length} suggestions`:`${products.length} articles à parcourir`}</span><button type="button" onClick={()=>setOpen(false)} aria-label="Fermer les suggestions"><X size={17}/></button></div><div className="catalog-categories" aria-label="Rayons">{['Tous',...productCategories].map(c=><button key={c} type="button" aria-pressed={category===c} className={category===c?'selected':''} onClick={()=>{setCategory(c);setIndex(0);}}>{c}</button>)}</div><div className="catalog-results" id={id+'-list'} role="listbox" aria-label="Articles du catalogue">{matches.map((p,i)=><button key={p.title} id={id+'-'+i} type="button" role="option" aria-selected={i===index} className={i===index?'highlighted':''} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(p)}><span className="product-emoji" aria-hidden="true">{foodEmoji(p.title,p.icon)}</span><span><strong>{p.title}</strong><small>{p.category}</small></span><Check size={16}/></button>)}</div>{!matches.length&&<p className="catalog-empty">Aucune suggestion. Vous pouvez garder « {value} » comme article personnalisé.</p>}<button className="catalog-custom" type="button" onClick={()=>setOpen(false)}>{value?`Garder « ${value} »`:'Saisir mon propre article'}</button></div>}</div>;
}
export function ArticlePhoto({id,title}:{id:string;title:string}){
 const[data,setData]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setData('');setError('');apiFetch('/api/photos?id='+encodeURIComponent(id)).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Photo indisponible.');if(alive)setData(d.data);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[id]);
 return data?<figure className="article-photo"><img src={data} alt={`Photo de référence : ${title}`}/><figcaption>La photo pour trouver le bon produit.</figcaption></figure>:<p className="photo-loading" role="status">{error||'Chargement de la photo…'}</p>;
}
export default function ShoppingArticleForm({item,week,names,busy,error,onSave,onDelete}:{item?:Item;week:string;names:string[];busy:boolean;error:string;onSave:(p:unknown)=>Promise<boolean>;onDelete?:()=>void}){
 const[id]=useState(()=>item?.id||crypto.randomUUID()),[title,setTitle]=useState(item?.title||''),[quantity,setQuantity]=useState(item?.quantity||''),[note,setNote]=useState(item?.note||''),[photoId,setPhotoId]=useState(item?.photoId||null),[photo,setPhoto]=useState(''),[processing,setProcessing]=useState(false),[localError,setLocalError]=useState('');const uploading=useRef(false),photoDraftId=useRef(crypto.randomUUID());
 const presets=findProduct(title)?.presets||['1 pièce','2 pièces','1 paquet','500 g','1 kg'];
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(uploading.current||processing||busy)return;uploading.current=true;setProcessing(true);setLocalError('');const form=new FormData(e.currentTarget);try{let savedPhoto=photoId;if(photo){const r=await apiFetch('/api/photos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:photoDraftId.current,data:photo})});const data=await r.json();if(!r.ok)throw Error(data.error||'Photo non enregistrée.');savedPhoto=data.id;setPhotoId(savedPhoto);setPhoto('');}await onSave({id,version:item?.version||0,kind:'shopping',title:title.trim(),quantity:quantity.trim(),note:note.trim(),photoId:savedPhoto,assignee:Number(form.get('assignee')),due:'',priority:0,done:item?.done||false,weekStart:item?.weekStart||week});}catch(e){setLocalError(e instanceof Error?e.message:'Enregistrement impossible.');}finally{uploading.current=false;setProcessing(false);}}
 return <form className="form article-form" onSubmit={submit}><ProductPicker value={title} onChange={setTitle}/><label>Quantité<input value={quantity} onChange={e=>setQuantity(e.target.value)} maxLength={50} placeholder="Choisir ci-dessous ou saisir librement"/></label><div className="quantity-presets" aria-label="Quantités suggérées">{presets.map(q=><button key={q} type="button" aria-pressed={quantity===q} className={quantity===q?'selected':''} onClick={()=>setQuantity(q)}>{q}</button>)}</div><label>Qui s’en occupe ?<select name="assignee" defaultValue={item?.assignee??-1}><option value={-1}>L’un de nous</option>{names.map((n,i)=><option key={i} value={i}>{n}</option>)}</select></label><label>Un commentaire pour trouver le bon produit <span className="optional">(facultatif)</span><textarea rows={3} value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder="La boîte bleue, version sans sucre, grand format…"/></label><div className="article-photo-field"><span className="field-title"><Camera size={17}/>Photo de référence <span className="optional">(facultatif)</span></span>{photo?<figure className="article-photo"><img src={photo} alt="Photo à joindre à l’article"/></figure>:photoId?<ArticlePhoto id={photoId} title={title}/>:null}<div className="photo-actions"><label className="secondary photo-upload"><ImagePlus size={18}/>{processing?'Préparation…':photo||photoId?'Changer la photo':'Ajouter une photo'}<input type="file" accept="image/*" disabled={busy||processing} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setProcessing(true);setLocalError('');try{setPhoto(await compressPhoto(file));photoDraftId.current=crypto.randomUUID();}catch(err){setLocalError(err instanceof Error&&err.message?err.message:'Photo illisible. Essayez un format JPEG ou PNG.');}finally{setProcessing(false);e.target.value='';}}}/></label>{(photo||photoId)&&<button type="button" className="text-link" disabled={busy||processing} onClick={()=>{setPhoto('');setPhotoId(null);}}><X size={16}/>Retirer</button>}</div><small>Photo de 30 Mo maximum, compressée puis enregistrée en privé dans Supabase. Visible par vous deux.</small></div>{(error||localError)&&<p role="alert" className="form-error">{localError||error}</p>}<div className="dialog-actions">{onDelete&&<button type="button" className="icon-button delete-button" disabled={busy||processing} aria-label="Supprimer l’article" onClick={onDelete}><Trash2 size={18}/></button>}<button className="primary grow" disabled={busy||processing||!title.trim()} type="submit">{busy||processing?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>} {busy||processing?'Enregistrement…':item?'Enregistrer les modifications':'Ajouter à la liste'}</button></div></form>;
}
