import type {Appointment} from './domain';
// Sources verified 2026-10-09; fixed reference data, never private household data.
export const holidays:Appointment[]=[
  {
    "id": "reference-2026-01-01-0",
    "date": "2026-01-01",
    "title": "Jour de l’an",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-04-06-1",
    "date": "2026-04-06",
    "title": "Lundi de Pâques",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-01-2",
    "date": "2026-05-01",
    "title": "Fête du Travail",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-08-3",
    "date": "2026-05-08",
    "title": "Victoire de 1945",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-14-4",
    "date": "2026-05-14",
    "title": "Ascension",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-25-5",
    "date": "2026-05-25",
    "title": "Lundi de Pentecôte",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-07-14-6",
    "date": "2026-07-14",
    "title": "Fête nationale",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-08-15-7",
    "date": "2026-08-15",
    "title": "Assomption",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-11-01-8",
    "date": "2026-11-01",
    "title": "Toussaint",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-11-11-9",
    "date": "2026-11-11",
    "title": "Armistice de 1918",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-12-25-10",
    "date": "2026-12-25",
    "title": "Noël",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-02-18-11",
    "date": "2026-02-18",
    "title": "Mercredi des Cendres · début du Carême",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/02",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-03-29-12",
    "date": "2026-03-29",
    "title": "Dimanche des Rameaux",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/03",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-04-02-13",
    "date": "2026-04-02",
    "title": "Jeudi saint",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/04",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-04-03-14",
    "date": "2026-04-03",
    "title": "Vendredi saint",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/04",
    "note": "Calendrier catholique en France. Le Vendredi saint est férié localement en Alsace-Moselle.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-04-05-15",
    "date": "2026-04-05",
    "title": "Pâques",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/04",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-24-16",
    "date": "2026-05-24",
    "title": "Pentecôte",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/05",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-01-04-17",
    "date": "2026-01-04",
    "title": "Épiphanie (célébration en France)",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/01",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-02-02-18",
    "date": "2026-02-02",
    "title": "Chandeleur",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/02",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-11-29-19",
    "date": "2026-11-29",
    "title": "Premier dimanche de l’Avent",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/11",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-12-26-20",
    "date": "2026-12-26",
    "title": "Saint-Étienne · Alsace-Moselle",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2026/12",
    "note": "Férié en Alsace-Moselle uniquement.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-31-21",
    "date": "2026-05-31",
    "title": "Fête des mères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fete-des-meres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-06-21-22",
    "date": "2026-06-21",
    "title": "Fête des pères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fete-des-peres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-03-01-23",
    "date": "2026-03-01",
    "title": "Fête des grands-mères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fetes-des-grands-meres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-10-04-24",
    "date": "2026-10-04",
    "title": "Fête des grands-pères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fete-des-grands-peres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-02-14-25",
    "date": "2026-02-14",
    "title": "Saint-Valentin",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-04-01-26",
    "date": "2026-04-01",
    "title": "Poisson d’avril",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-06-21-27",
    "date": "2026-06-21",
    "title": "Fête de la musique",
    "category": "culture",
    "source": "https://fetedelamusique.culture.gouv.fr/actualites/presentation-de-la-fete-de-la-musique2",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-10-31-28",
    "date": "2026-10-31",
    "title": "Halloween",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-12-31-29",
    "date": "2026-12-31",
    "title": "Saint-Sylvestre",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-02-17-30",
    "date": "2026-02-17",
    "title": "Mardi gras",
    "category": "culture",
    "source": "https://www.aelf.org/calendrier/romain/2026/02",
    "note": "Veille du mercredi des Cendres · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-01-01-31",
    "date": "2027-01-01",
    "title": "Jour de l’an",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-03-29-32",
    "date": "2027-03-29",
    "title": "Lundi de Pâques",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-01-33",
    "date": "2027-05-01",
    "title": "Fête du Travail",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-06-34",
    "date": "2027-05-06",
    "title": "Ascension",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-08-35",
    "date": "2027-05-08",
    "title": "Victoire de 1945",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-17-36",
    "date": "2027-05-17",
    "title": "Lundi de Pentecôte",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-07-14-37",
    "date": "2027-07-14",
    "title": "Fête nationale",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-08-15-38",
    "date": "2027-08-15",
    "title": "Assomption",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-11-01-39",
    "date": "2027-11-01",
    "title": "Toussaint",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-11-11-40",
    "date": "2027-11-11",
    "title": "Armistice de 1918",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-12-25-41",
    "date": "2027-12-25",
    "title": "Noël",
    "category": "france",
    "source": "https://www.service-public.gouv.fr/particuliers/vosdroits/F2405",
    "note": "Jour férié national · France métropolitaine.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "france",
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-02-10-42",
    "date": "2027-02-10",
    "title": "Mercredi des Cendres · début du Carême",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/02",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-03-21-43",
    "date": "2027-03-21",
    "title": "Dimanche des Rameaux",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/03",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-03-25-44",
    "date": "2027-03-25",
    "title": "Jeudi saint",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/03",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-03-26-45",
    "date": "2027-03-26",
    "title": "Vendredi saint",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/03",
    "note": "Calendrier catholique en France. Le Vendredi saint est férié localement en Alsace-Moselle.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-03-28-46",
    "date": "2027-03-28",
    "title": "Pâques",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/03",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-16-47",
    "date": "2027-05-16",
    "title": "Pentecôte",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/05",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-01-03-48",
    "date": "2027-01-03",
    "title": "Épiphanie (célébration en France)",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/01",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-02-02-49",
    "date": "2027-02-02",
    "title": "Chandeleur",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/02",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-11-28-50",
    "date": "2027-11-28",
    "title": "Premier dimanche de l’Avent",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/11",
    "note": "Calendrier catholique en France.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-12-26-51",
    "date": "2027-12-26",
    "title": "Saint-Étienne · Alsace-Moselle",
    "category": "christian",
    "source": "https://www.aelf.org/calendrier/romain/2027/12",
    "note": "Férié en Alsace-Moselle uniquement.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "christian"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-30-52",
    "date": "2027-05-30",
    "title": "Fête des mères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fete-des-meres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-06-20-53",
    "date": "2027-06-20",
    "title": "Fête des pères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fete-des-peres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-03-07-54",
    "date": "2027-03-07",
    "title": "Fête des grands-mères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fetes-des-grands-meres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-10-03-55",
    "date": "2027-10-03",
    "title": "Fête des grands-pères",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres/fete-des-grands-peres",
    "note": "Fête familiale en France · non fériée.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-02-14-56",
    "date": "2027-02-14",
    "title": "Saint-Valentin",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-04-01-57",
    "date": "2027-04-01",
    "title": "Poisson d’avril",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-06-21-58",
    "date": "2027-06-21",
    "title": "Fête de la musique",
    "category": "culture",
    "source": "https://fetedelamusique.culture.gouv.fr/actualites/presentation-de-la-fete-de-la-musique2",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-10-31-59",
    "date": "2027-10-31",
    "title": "Halloween",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-12-31-60",
    "date": "2027-12-31",
    "title": "Saint-Sylvestre",
    "category": "culture",
    "source": "https://www.laposte.fr/modeles-lettres",
    "note": "Repère culturel · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-02-09-61",
    "date": "2027-02-09",
    "title": "Mardi gras",
    "category": "culture",
    "source": "https://www.aelf.org/calendrier/romain/2027/02",
    "note": "Veille du mercredi des Cendres · non férié.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "culture"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-02-18-62",
    "date": "2026-02-18",
    "title": "Ramadan",
    "category": "islam",
    "source": "https://www.grandemosqueedeparis.fr/post/communique-debut-du-mois-de-ramadan-2026-1447-h-18-fevrier-2026",
    "note": "Repère selon la Grande Mosquée de Paris ; le début peut différer selon l’autorité religieuse suivie.",
    "endDate": "2026-03-19",
    "provisional": false,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-03-20-63",
    "date": "2026-03-20",
    "title": "Aïd al-Fitr",
    "category": "islam",
    "source": "https://www.grandemosqueedeparis.fr/fetes-religieuses",
    "note": "Date publiée par la Grande Mosquée de Paris.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-27-64",
    "date": "2026-05-27",
    "title": "Aïd al-Adha",
    "category": "islam",
    "source": "https://www.grandemosqueedeparis.fr/fetes-religieuses",
    "note": "Date publiée par la Grande Mosquée de Paris.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-08-25-65",
    "date": "2026-08-25",
    "title": "Mawlid",
    "category": "islam",
    "source": "https://www.grandemosqueedeparis.fr/fetes-religieuses",
    "note": "Date publiée par la Grande Mosquée de Paris.",
    "endDate": "",
    "provisional": false,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-05-26-66",
    "date": "2026-05-26",
    "title": "Jour d’Arafat",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Repère du calendrier lunaire, pouvant différer selon l’observation locale.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-06-16-67",
    "date": "2026-06-16",
    "title": "Nouvel an hégirien",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Repère du calendrier lunaire, pouvant différer selon l’observation locale.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-06-25-68",
    "date": "2026-06-25",
    "title": "Achoura",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Repère du calendrier lunaire, pouvant différer selon l’observation locale.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-02-08-69",
    "date": "2027-02-08",
    "title": "Ramadan · prévisionnel",
    "category": "islam",
    "source": "https://www.islamic-relief.org.uk/giving/islamic-giving/ramadan/",
    "note": "Premier jour prévu le 8 février ; fin prévue le 8 ou le 9 mars. À confirmer selon l’observation lunaire.",
    "endDate": "2027-03-09",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-03-09-70",
    "date": "2027-03-09",
    "title": "Aïd al-Fitr · 9 ou 10 mars",
    "category": "islam",
    "source": "https://www.islamic-relief.org.uk/giving/islamic-giving/ramadan/",
    "note": "Date attendue le 9 ou le 10 mars, à confirmer.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-15-71",
    "date": "2027-05-15",
    "title": "Jour d’Arafat · 15 ou 16 mai",
    "category": "islam",
    "source": "https://fr.islamic-relief.org/aid-al-adha/",
    "note": "Date attendue le 15 ou le 16 mai, à confirmer.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-05-16-72",
    "date": "2027-05-16",
    "title": "Aïd al-Adha · 16 ou 17 mai",
    "category": "islam",
    "source": "https://fr.islamic-relief.org/aid-al-adha/",
    "note": "Date attendue le 16 ou le 17 mai, à confirmer.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-06-06-73",
    "date": "2027-06-06",
    "title": "Nouvel an hégirien",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Date indicative, à confirmer selon l’observation lunaire.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-06-15-74",
    "date": "2027-06-15",
    "title": "Achoura",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Date indicative, à confirmer selon l’observation lunaire.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-01-05-75",
    "date": "2027-01-05",
    "title": "Isra et Miraj",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Repère indicatif selon le calendrier lunaire.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-01-23-76",
    "date": "2027-01-23",
    "title": "Mi-Chaabane",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Repère indicatif selon le calendrier lunaire.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2027-08-14-77",
    "date": "2027-08-14",
    "title": "Mawlid · prévisionnel",
    "category": "islam",
    "source": "https://islamic.app/hijri/mawlid/2027",
    "note": "Date calculée indicative, à confirmer selon l’observation lunaire.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-01-16-78",
    "date": "2026-01-16",
    "title": "Isra et Miraj",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Repère indicatif selon le calendrier lunaire.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  },
  {
    "id": "reference-2026-02-03-79",
    "date": "2026-02-03",
    "title": "Mi-Chaabane",
    "category": "islam",
    "source": "https://islamicrelief.org.au/islamic-hijri-calendar/",
    "note": "Repère indicatif selon le calendrier lunaire.",
    "endDate": "",
    "provisional": true,
    "holidayGroups": [
      "islam"
    ],
    "person": -1,
    "status": "scheduled",
    "time": "",
    "bookBy": "",
    "location": "",
    "version": 0,
    "createdAt": "2026-10-09T00:00:00Z",
    "visibility": "shared",
    "recurrence": "none",
    "owner": null
  }
];
